### ISSUE TITLE
自增问题

### ISSUE THREAD

**Issue by summersir** [thx/RAP#1010]
![image](https://user-images.githubusercontent.com/20942887/29345557-398be900-8272-11e7-81d6-81960081c3f8.png)
![image](https://user-images.githubusercontent.com/20942887/29345565-4b1f4ab8-8272-11e7-8ed2-407086a53f61.png)
我设定的time是自增的 mock数据 的时候每次刷新都有自增， 但是在设定setInterval的时候 每秒请求来的time是一样的

**Comment by Bosn** [comment]
这是因为规则是针对每一次访问的。在同一个请求下，有多组数据，才会每组数据自增，不同的请求之间状态是不会共享的哟~~~

不过该问题可以用自定义函数来解决。参考：@mock=functon(){.... window._increment++;}
