### ISSUE TITLE
为什么rap  mock数据不能生成中文呢

### ISSUE THREAD

**Issue by galary** [thx/RAP#1013]
![image](https://user-images.githubusercontent.com/17908869/29400820-56119120-8361-11e7-9d11-9b811428af3d.png)
mock.js那样是可以输出中文的

**Comment by brahmachen** [comment]
同问题

**Comment by dothin** [comment]
更新一下mock.js就可以了

**Comment by Bosn** [comment]
应该是mock.js版本问题，您使用了是较新的mock.js预发，而服务器可能使用的旧的稳定版本，我们会尽快更新至最新。当然，经过测试后。
