### ISSUE TITLE
在提交新的接口时报错 

### ISSUE THREAD

**Issue by lastqxw** [thx/RAP#1014]
具体错误：发生严重错误，请联系维护人员并保留现场
![qq 20170817165439](https://user-images.githubusercontent.com/31094848/29404223-10287d5c-836d-11e7-8e46-a44d9300a9b3.png)

**Comment by Bosn** [comment]
抱歉，维护项目的同事工作变动导致更新不及时，非常抱歉。不过原作者马上就要接回RAP了，稍息片刻问题都会解决哦。
