### ISSUE TITLE
SyntaxError: unterminated string literal

### ISSUE THREAD

**Issue by ken8271** [thx/RAP#102]
当@mock数据里有换行符\r\n的时候，会报这个错误
在javascript里就显示成两行了，js不能容忍这样写就报错了

**Comment by Bosn** [comment]
这应该是JSON数据格式要求的原因，我查查先，看看是转换下，还是只能过滤掉。

**Comment by Bosn** [comment]
测试了一下，@mock=\r\n，如果是字符串类型，则返回：   "test":"\\r\\n"

也就是系统已经做过一次J转义。

如果亲发现数据报错，请看看是否选择了错误的数据类型。例如，如果选择数据类型，系统是不会加双引号，或进行任何转义的。这样可以满足个人的特殊需求。

如果仍有问题，请将错误样本发出来测试一下，谢谢！
