### ISSUE TITLE
视频看不了

### ISSUE THREAD

**Issue by lorelib** [thx/RAP#1020]
http://thx.github.io/RAP/study.html   ， 还有下载的swf也不能看

**Comment by BladeCode** [comment]
[RAP学习中心 内容无法访问](https://github.com/thx/RAP/issues/935)

**Comment by Bosn** [comment]
应该是临时问题，亲测目前已经恢复了哦。

**Comment by yuanhepeng** [comment]
还是打不开2019年05月8号
