### ISSUE TITLE
自己动手，丰衣足食，搭建了个 Rap 服务，欢迎使用～

### ISSUE THREAD

**Issue by YeDaxia** [thx/RAP#1022]
基于 release 分支做了一些修改：

代码在这：https://github.com/YeDaxia/RAP , release 分支。

1. 去掉了验证码，延长了登录失效的时间。
2. 更新了mockjs，支持中文了。

http://rap.yedaxia.me/

**Comment by Bosn** [comment]
支持楼主，不过这个超出issue范围了哦，先close咯
