### ISSUE TITLE
接口文档页的问题

### ISSUE THREAD

**Issue by figoisxjs** [thx/RAP#103]
在未来某个更新的feature是否有能支持上传demo测试数据之类的功能，因为感觉那个response的结构还是不够直观，花花绿绿的，我们的前端工程师们表示看的眼晕，如果给到一个demo的数据，阅读起来会更加直观些。
或者能否一键将response转成json格式之类的？

**Comment by Bosn** [comment]
囧，DEMO数据一直都有啊，而且还提供了接口可以直接调用的。数据是根据分析文档结构自动生成的，支持各种复杂MOCK规则。

http://thx.github.io/RAP/study.html

这是视频教程，请重点关注左边：《Mock工具入门》和《Mock工具进阶》两个小节。
