### ISSUE TITLE
[MODULE:help]中文帮助文档页面空白

### ISSUE THREAD

**Issue by linuxgg** [thx/RAP#1030]
[Environment]
OS: mac pro  10.12.5
Chrome: Version 60.0.3112.113 (Official Build) (64-bit)

[Steps]
1.open link: http://thx.github.io/RAP/study.html

[Expected]
1.the help doc is showing normally.

[Actually]
1.empty.
![snip20170831_2](https://user-images.githubusercontent.com/8160195/29905126-5bdb8456-8e3f-11e7-8e3c-4a72a28b6365.png)

**Comment by Bosn** [comment]
亲测可用哦，会不会是Flash不支持呢？或者打开控制台看下报错信息，如果有问题再reopen哦
