### ISSUE TITLE
release_en 和 release分支比较多问题，求关注。

### ISSUE THREAD

**Issue by channingZhou** [thx/RAP#104]
真的编译不过。。。列几个地方：
（1）ProjectDaoImpl.java
Line7: import com.sun.tools.javac.jvm.Items;   这个貌似是Eclipse中引入的，不用Eclipse IDE的情何以堪。。
（2）AuthCheckFilter.java
Line67:  User logUser = new User(); .....User没定义。
anyway~~ 对上面几个地方修改后，可以编译过。然后发布到tomcat后，变成这样：

![rap](https://cloud.githubusercontent.com/assets/11330083/6588748/12df4800-c7d1-11e4-9953-b2316558bc26.png)

然后用之前注册的账号登录，结果404.。。。。
求关注~

**Comment by Bosn** [comment]
看起来是路径的问题，亲注意ContextRoot要设置为/哦，比如，最后部署应该是：
http://domain/index.do

而不能是：
http://domain/rap/index.do


下面这种需要配置第二层路径的，需要配置几个地方。
亲可以右键查看页面源代码检查一下静态资源是否出错。应该都是路径问题哦~~~~


import com.sun.tools.javac.jvm.Items; 这个问题我检查一下，其实我已经改用IDEA了，HOHOHO。

**Comment by Bosn** [comment]
如果问题已解决，请自己Close。
如果仍然有问题，请跟帖哦

**Comment by channingZhou** [comment]
不建议将应用直接部署在根目录，因为根目录是tomcat的管理页面。 
找了半天发现你在 const.inc.vm 里强制配了上下文路径：#set($projectContext = "$!link.getContextPath()")，你之前的回复也说有几个地方要改，能否把上下文配置统一到一处？ 这样就可以方便修改。

**Comment by Bosn** [comment]
不只这一处修改哦，配置contextRoot的问题我会在v0.11.1~3中修复。
因为刚刚对外开放，此前都是公司内部使用，在配置的易用性方面还有很多地方要做。

**Comment by channingZhou** [comment]
好。坐等 v0.11

**Comment by Bosn** [comment]
不是v0.11，现在就是v0.11了。
后续我会把这个问题在补丁v0.11.1或v0.11.2中修复。
具体请关注issue：https://github.com/thx/RAP/issues/106
