### ISSUE TITLE
哎，什么几把？一直打不开

### ISSUE THREAD

**Issue by zcxzmzy** [thx/RAP#1041]

**Comment by zcxzmzy** [comment]
还什么一直被抄袭，从未被超越。我去

**Comment by xinyu198736** [comment]
@zcxzmzy 可以用一下这个项目，实现的功能类似，但是比这个强大很多 https://github.com/easy-mock/easy-mock

**Comment by Bosn** [comment]
抱歉，作为RAP的作者，因为离开了阿里失去了运维的权限。

不过这个问题本月就可以解决，拿到维护权限稳定性马上会解决。亲可以尝试下自己部署服务自己维护，也可以考虑下楼上其它的工具软件，多多对比，找到适合自己的。

十分抱歉。

**Comment by sx1989827** [comment]
可以参考这个项目，免费开源，专门做接口管理的 https://github.com/sx1989827/DOClever    doclever.cn
