### ISSUE TITLE
CTMD,鸟东西,3天报错2天,提毛高效,日狗了

### ISSUE THREAD

**Issue by JackieCoo** [thx/RAP#1047]

**Comment by Bosn** [comment]
官网是DEMO如果正式用建议自己部署，已经确定9月25日我会入职，收回PE权限尽快解决稳定性问题。在这里为我离职期间，因维护不给力，线上不稳定给大家带来的困扰抱歉。对不起。

另外，咱们写代码的，多少也是有点文化的人，别干没文化的事儿。我最开始做这个RAP，然后做成开源工具，只是作为技术宅的一个兴趣，希望能给别人更多的启发。但真的没收您的钱，没义务帮您。作为原作者我会尽力维护，但这不是您在这儿不要脸的资本。

**Comment by timothyer** [comment]
给作者点赞，要懂得感恩

**Comment by Bosn** [comment]
RAP2源代码已经放出了哦亲，我也在全力维护这个项目。具体见首页README哦
