### ISSUE TITLE
致歉声明

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#1048]
很抱歉，因为去年5月出来创业之后，各种原因，导致RAP站点的维护不给力，频出稳定问题。十分对不起大家。因为公司的管理规定，离职员工自然不能接触生产环境的运维权限，**不过这些问题都将随着我本月底入职阿里解决**。

RAP是我2010年因为当时前后端人员互相传Excel文档管理不便，就想做个RAP，让接口管理更简单更方便。一路走来7年，在木头、思竹、行列、墨智等老师的大力支持帮助下，用零零散散的业余时间把它一点点的完善，到现在有这么多的用户，感激大家对RAP的认可，也真诚的接受大家的批评。不管什么原因，很抱歉过去一年给大家如此糟糕的使用体验，月底回归阿里后我会全力解决这些问题。

并且我会规划用前沿的技术重构RAP，解决项目级锁定的核心问题，随着框架体系的成熟，许多之前想做的自动化测试功能，也时机成熟。具体的工作进展我会及时在Issues/Wiki区和大家同步。

RAP过去7年，感谢大家的认可和支持。
未来我们会更加努力的为大家带来更多更好的开源项目。

谢谢

Bosn

**Comment by callmepeanut** [comment]
目前能给个去掉登录验证码或者加长session时间的临时方案吗（使用war包部署）？内网使用频繁登录很繁琐，谢谢~

**Comment by Bosn** [comment]
@callmepeanut 官方版本因为安全原因肯定不适合，去掉验证，后续可以考虑使用token的方式进行验证。

如果是自己部署的服务，把验证码相关逻辑删掉重新打包部署即可。

**Comment by yi-ge** [comment]
支持！

**Comment by francisoliverlee** [comment]
理解

**Comment by sunOpar** [comment]
⛽️

**Comment by xuqisheng** [comment]
谢谢作者?

**Comment by 327** [comment]
感谢付出

**Comment by leeyesong** [comment]
加油

**Comment by kajweb** [comment]
刚刚试用RAp，感觉不太友好。功能对我来说貌似不太明确。
