### ISSUE TITLE
自己搭建的rap，mock数据报错

### ISSUE THREAD

**Issue by linavv1** [thx/RAP#1049]
自己搭建的mock服务器，在接口详情后面的红色mock数据按钮，点进去后，点mock数据，报错？提示为：{"errMsg":"\"Mock\" is not defined.","isOk":false}，官网的这样操作没有问题

**Comment by Bosn** [comment]
Mock.min.js文件没有被正确加载，应该是不同操作系统的路径问题。可以检查一下文件的路径搜索一下这个名字。

**Comment by linavv1** [comment]
我是使用的windows server 2012 r2标准版，我在tomcat下的webapps下搜索没有Mock.min.js的文件，只有一个mock-min.js文件，是在webapps\ROOT\stat\js\util目录下面，我使用的是war包部署的，是需要把mock-min.js改成你说的那个名字吗？或者自己使用源码编译打包更好？

**Comment by Bosn** [comment]
当时我在测试的时候没有试过所有的操作系统，尤其windows没有部署过我觉得应该是源代码在载入路径的时候没有做好兼容性处理。建议您还是用源代码修改一下这个文件的引入的路径。

**Comment by linavv1** [comment]
好的，谢谢，我先尝试修改下文件路径，我想达到前端直接使用那个mock数据的url就能拿到mock后的数据

**Comment by linavv1** [comment]
应该是window和linux下获取SystemConstant.ROOT路径的差异，windows下获取到的路径最后没有"/符号"
