### ISSUE TITLE
Rap 自动化测试怎么使用？

### ISSUE THREAD

**Issue by rom1c77** [thx/RAP#1051]
有没有rap交流群啊，别给旺旺群号，一脑补我下载旺旺进群，支付宝扫码5块资料打包就好笑。 
Rap怎么做自动化测试？

**Comment by Bosn** [comment]
我会考虑建立一个钉钉群

**Comment by Bosn** [comment]
企业文化没办法呀你懂得

**Comment by softxiang** [comment]
@Bosn 钉钉群建了吗，群号多少？

**Comment by Bosn** [comment]
@softxiang 丁丁群号码“RAP用户群”群的钉钉群号： 11789704

**Comment by wh-Coder** [comment]
@Bosn 怎么搜不到这个号？需要扫码吗？

**Comment by jiangqqlmj** [comment]
已经发送申请

**Comment by moconcc** [comment]
刚刚发送了申请

**Comment by Bosn** [comment]
已经过期了同志们，哈哈哈。RAP1不维护了哟
