### ISSUE TITLE
文档被锁定能不能按照模块锁定

### ISSUE THREAD

**Issue by ArvinChen9539** [thx/RAP#1055]
一个人改文档整个项目都会被锁定, 这样多人协作上影响太大了,通常项目是按照模块划分开发人员的 能不能在编辑的时候只锁定当前的模块其他的模块还可以编辑呢

**Comment by Bosn** [comment]
底层API改动会比较大，所以RAP1暂时不做大的改动了。我们会在RAP2解决。

RAP2目前大部分功能已经开发完成，采用的是node + react的架构。
对外推送还需要少量测试。
