### ISSUE TITLE
请求参数名称设置为id时  请求mock数据传中文报错

### ISSUE THREAD

**Issue by ArvinChen9539** [thx/RAP#1057]
设置某接口的请求参数名为id 类型为string
![u8oz qfo9_7w 9lj 9 m 6](https://user-images.githubusercontent.com/20532645/31420928-fcb7bef6-ae76-11e7-8c39-33cf079aa12a.png)

测试mock返回的数据
![o_jw3jcxw 9cl p3ppgll9k](https://user-images.githubusercontent.com/20532645/31421157-5ccba6a8-ae78-11e7-86f7-190d11e4be41.png)

参数名称修改为其他名称返回正常 比如改成uid
另外我试了一下 从页面控制台里面测试接口是可以的

**Comment by Bosn** [comment]
id.... 只匹配数字哦

**Comment by ArvinChen9539** [comment]
说明id这个属性名称做了特别的处理吧 我已经把接口参数类型改为字符串了  理论上传中文也没问题而且控制台里面调试是可以的
