### ISSUE TITLE
验证码只有背景没有数字

### ISSUE THREAD

**Issue by JohnTao** [thx/RAP#1060]

**Comment by JohnTao** [comment]
[https://user-images.githubusercontent.com/24917984/31620243-090b2a66-b297-11e7-826a-8767cefeda90.png](url)

**Comment by JohnTao** [comment]
![31620243-090b2a66-b297-11e7-826a-8767cefeda90](https://user-images.githubusercontent.com/1073365/31621726-06123b48-b2cd-11e7-8add-a95532c492fd.png)

**Comment by Bosn** [comment]
刷新下，应该是套用组件的BUG
