### ISSUE TITLE
不能登录！密码错误一百年......

### ISSUE THREAD

**Issue by Qu000** [thx/RAP#1061]
昨天注册的，网页记住密码后，退出了就不能登录了，然后再注册一个，昨天退出了，今天登录的时候竟然又说密码错误！！！！我试了N次啊！！！！

**Comment by zhangyihao** [comment]
强烈建议提供密码找回功能

**Comment by Bosn** [comment]
临时解决办法：加旺旺群或钉钉群来找我重置密码。

钉钉群ID:11789704
