### ISSUE TITLE
总是各种进入不了页面，能不能稳定些、、、、、、

### ISSUE THREAD

**Issue by wzpziyi1** [thx/RAP#1063]

**Comment by zhangyihao** [comment]
自己搭个服务算了

**Comment by Bosn** [comment]
不好意思，我在拿回运营权限。目前权限已经在我手里了，稳定性问题我会立刻改进哈。

**Comment by Bosn** [comment]
刚才做权限配置的时候重启了下。抱歉抱歉。

**Comment by wzpziyi1** [comment]
还是的自己搭、、今天又挂了

**Comment by Bosn** [comment]
@wzpziyi1  已恢复。。。 Sorry，这两天在研究Docker自动重启。
另外RAP2新重构的，还在研发中。我们会尽快放出。
