### ISSUE TITLE
验证码到底该怎样才能填对！

### ISSUE THREAD

**Issue by sdoq19** [thx/RAP#1068]
RAP的登录及注册的验证码，到底该怎么填才能填对呀！这也太难认了吧

**Comment by Bosn** [comment]
还好啦，比较通用的验证码组件。现在各大网站里其实不算难认的。。。
只能怪现在的机器人都太厉害。。。简单验证码一样水到底。。。

**Comment by sdoq19** [comment]
原来是因为Kaptcha生成的字符乱码了哈，我说怎么一个字符都认不到
