### ISSUE TITLE
rap.js函数generateId函数

### ISSUE THREAD

**Issue by arebya** [thx/RAP#107]
![image](https://cloud.githubusercontent.com/assets/1525048/6652475/da17b5e8-caaa-11e4-9760-da0ec91ed6a1.png)
![image](https://cloud.githubusercontent.com/assets/1525048/6652476/f26bea1a-caaa-11e4-9afe-2db8920fb8d7.png)

这样在反序列化json到Project时id字段会出现类型错误

**Comment by Bosn** [comment]
不会出现的。这里的generateId仅用于新增某一实体时设置不重复的临时ID所用。

因为RAP仅在提交文档时将数据传到服务器，Client创建的实体ID都以generateId生成，到服务器提交时会判断出这种ID并进行实体新增，而后再返回真实的ID。
