### ISSUE TITLE
rap服务器端备份问题

### ISSUE THREAD

**Issue by shenmou98** [thx/RAP#1072]
目前在wiki文档上没有看到跟备份有关的内容。
请问 官方是否有什么推荐的方法可以定期备份rap服务器？ （我们这边目前发生了部分文档打不开的事故）

**Comment by Bosn** [comment]
mysql备份和rap没关系啊，搜下mysqldump，很简单。

**Comment by shenmou98** [comment]
谢谢。 意思是只要把数据库备份了就可以了吗?
