### ISSUE TITLE
 控制台暂时不支持正则RESTful API(也就是包含reg:的URL)

### ISSUE THREAD

**Issue by 359257840** [thx/RAP#1078]
控制台暂时不支持正则RESTful API(也就是包含reg:的URL)    哎·······

**Comment by 359257840** [comment]
![image](https://user-images.githubusercontent.com/11308580/32204573-08e44218-be25-11e7-9238-f5b42c84a602.png)

**Comment by Bosn** [comment]
RAP插件支持

**Comment by Bosn** [comment]
控制台我也会支持哈，不过是在RAP2。哈哈哈。
