### ISSUE TITLE
http://rapapi.org/是不是挂了整个站点都访问不了

### ISSUE THREAD

**Issue by kingcaigen** [thx/RAP#1087]
请问下http://rapapi.org/ 这个站点是不是挂了？
整个站点都访问不了阿。明天就要拿来演示了，现在测试接口都直接调用的rapapi上的，访问不了，不知咋整阿。
求大神给个答复 T_T

**Comment by nikomal** [comment]
的确是挂了,昨天下午就连不上了

**Comment by Bosn** [comment]
正在处理，服务器无法正常登陆。联系PE一直发信息不回，打电话拒接...  醉了

**Comment by linwenchao** [comment]
已经整整一天了，阿里云说好的高可用性呢？

**Comment by Bosn** [comment]
@linwenchao  这和阿里云没关系...  RAP1 DEMO站点现在用的人太多了，服务器配置跟不上，老是内存out of memory。

自己团队使用，建议采用Docker部署。阿里内部的RAP也是要单独自己部署的，一直运转良好。
rap.taobao.org主要是DEMO使用，并不建议用于实际生产开发。

**Comment by guoyudong** [comment]
至少让我将数据导出来

**Comment by Bosn** [comment]
@guoyudong 数据不会丢的

**Comment by Bosn** [comment]
已经确认，系双11安全相关规则导致的无法访问，已经恢复。

**Comment by kingcaigen** [comment]
@Bosn  谢谢，可以访问了
