### ISSUE TITLE
rap设置的数据类型和实际返回的不同

### ISSUE THREAD

**Issue by naij** [thx/RAP#110]
响应字段我设置成了string，对应的值是一个数组，期望返回的数据类型是字符串类型，但是实际返回的是数组类型

![2015-03-30 15 23 00](https://cloud.githubusercontent.com/assets/1192570/6891926/6edf7e8e-d6f1-11e4-8410-9a218b2da2e3.png)

![2015-03-30 15 23 55](https://cloud.githubusercontent.com/assets/1192570/6891927/75377dae-d6f1-11e4-8e44-9cb2ced12c5c.png)

**Comment by Bosn** [comment]
hi, 亲，考虑到MockJS有这样的模板语法：
```javascript
{
    "val|1" : ["a", "b", "c"]
}
```
意思是，在数组["a", "b", "c"]中随机取一个，作为val的值。

为了确保该种情况正常被识别，当@mock=[这样以数组开头时，RAP不会加双引号。

亲如果需要string类型，需要手动在收尾加上双引号，即：
@mock="[....]";

**Comment by Bosn** [comment]
如果使用@mock=""，会被自动加引号，也是不行的。
且@{mock}禁止转义语法失效了。

### TODO
[ ] 修复@{mock}禁止转义的功能
[ ] 在@mock="时，不再添加多重双引号

**Comment by Bosn** [comment]
已在commit cadf4cd 中修复了该问题，现在@{mock}标签不仅可以防止转义，也会防止自动化处理""字符串。

而string类型当检测到mock模板值以双引号开头结尾时，不会重复则更加双引号。

该需求预计清明节假期上线。
