### ISSUE TITLE
RAP restful问题 

### ISSUE THREAD

**Issue by angular-moon** [thx/RAP#112]
RAP 可以区分出 post, put, delete吗

**Comment by Bosn** [comment]
因为MOCK数据是JSONP，所以目前标记的GET/POST其实只是出于给人看的文档的目的。

但是我们后续会做的借口测试、自动化测试等功能，都可能会用到这个信息。

只是目前，已实现功能里，还未受该参数影响。作为文档，这个信息还是要正确填写的哟
