### ISSUE TITLE
RAP1无法访问

### ISSUE THREAD

**Issue by weelh** [thx/RAP#1125]
http://rap.taobao.org/  无法访问.  持续时间已经很久了,麻烦能不能看下?  

跪谢!

**Comment by it-hero** [comment]
http://rapapi.org/org/index.do 无法访问，已经两天了，很着急

**Comment by Bosn** [comment]
抱歉，服务已更新。

RAP1确实已经停止升级更新了，目前主要精力会放在RAP2上。
钉钉群：11789704

有问题请在群里反馈哦
