### ISSUE TITLE
RAP mock function

### ISSUE THREAD

**Issue by angular-moon** [thx/RAP#113]
数据类型为string的时候怎么使用 @mock=function(){}

**Comment by Bosn** [comment]
string类型和其它类型一样。在使用function时，function返回的是什么，就是什么。不会做特别处理。
亲可以试试哦~~~
例如：@mock=function(){return "123";}  返回字符串类型"123"
如果是@mock=function(){return 567;} 返回数字类型567

**Comment by angular-moon** [comment]
@mock=function(){return "135" + Random.string("number",8);}
类型为number 的时候生成的数据是正确的
类型为string 的时候生成的数据是: "phone":"function(){return \"135\" + Random.string(\"number\",8);}"

**Comment by Bosn** [comment]
刚才旺旺里联系的就是你吧？

亲的版本过低，这个问题我们已经修复了，我们会在最近2天经过测试后把v0.11.1版本合入到release，就可以修复该问题了。
