### ISSUE TITLE
rap登录的验证码是哪国语言，完全看不懂

### ISSUE THREAD

**Issue by gongstring** [thx/RAP#1136]
rap部署完成，在注册和登录的时候，验证码内容过于复杂，虽然安全性得到了保障，但是似乎已经超过了人类可识别的极限，属于哪个语种，如何才能愉快的登录成功？

**Comment by shang7053** [comment]
3D英文和数字

**Comment by gongstring** [comment]
@shang7053  确定？我怎么看着都是大于符号、小于符号之类，完全看不懂

**Comment by gongstring** [comment]
刚试了下，是因为centos服务器上面导致的
