### ISSUE TITLE
rap登入不了

### ISSUE THREAD

**Issue by xcqweb** [thx/RAP#1137]
RAP出错啦！
当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T

上面是提示的错误信息帮忙解决一下,谢谢

**Comment by krystalcl** [comment]
同

**Comment by elesos** [comment]
一样，看来没人维护了。
