### ISSUE TITLE
服务怎么会停这么久

### ISSUE THREAD

**Issue by wdjcodestyle** [thx/RAP#1169]
用rap有很长时间了，不是号称阿里淘宝也在用吗? 这次怎么停这么久，有没有考虑到用户感受啊？

**Comment by Bosn** [comment]
抱歉，服务已更新。

RAP1确实已经停止升级更新了，目前主要精力会放在RAP2上。
钉钉群：11789704

有问题请在群里反馈哦

**Comment by Bosn** [comment]
阿里内部也在用，但是我们是分开部署。对外部署的站点主要用于DEMO，并不建议投入使用。
RAP是MIT协议的开源免费软件，可以自行部署和维护。谢谢。
