### ISSUE TITLE
RESTful风格的API通过method区分不同接口

### ISSUE THREAD

**Issue by cctestss** [thx/RAP#118]
路径相同的接口，通过Method来区分不同的get,post,delete所对应的不同的接口

**Comment by Bosn** [comment]
## 技术设计
与该客户QQ交流，进行方案设计如下。
### iOS/Android App
对于该情况，会直接通过GET/PUT/DELETE/POST协议对接口类型进行区分和辨别。
辨别方式采用弱辨别，在通过URL模式匹配结果不唯一时再进行协议判断。

### 浏览器
通过升级RAP plugin，在发现ajax调用方式不为get时，传特殊参数__method__={{method}}，{{method}}取值有GET/PUT/DELETE/POST，默认为GET。

后端在发现有__method__方法时，使用iOS/Android App中提到的弱判断办法进行处理

**Comment by dotnil** [comment]
浏览器的话，method 一般可以从参数或者请求头里面拿，一般是 `req.body._method` 和 `X-HTTP-METHOD-OVERRIDE`。如果支持从这两个地方自动获取，就不需要专门给 RAP 插件传 `method` 了。后者适合作为替代方案。

**Comment by Bosn** [comment]
后端判断已加，commit c55b1e684db24c800cb3f1aceac42278a358dc36
现在在action pick时会考虑到request的method。

**Comment by Bosn** [comment]
已满足客户需求，插件更新放到日常去做，issue closed
