### ISSUE TITLE
发现如果url中出现多个REST参数时报错

### ISSUE THREAD

**Issue by kazaff** [thx/RAP#119]
发现如果url中出现多个rest参数，如下：

> /data/:id/:offset/:total

就会提示：

```
{
    "errMsg":"no matched action","isOk":false
}
```

只有一个参数(:id)是可以的~~如何解决？

**Comment by kazaff** [comment]
**/data/:id**貌似也不行，必须有个后缀~

**Comment by Bosn** [comment]
这是BUG我改一下哈啊

**Comment by Bosn** [comment]
咦？这个bug我修复过。。。你用release分支最新代码试试

**Comment by kazaff** [comment]
rap_release_v0.11.0_20141202这个是最新版本么？

**Comment by Bosn** [comment]
这是打的包啊，你我可以自己clone出来拿到最新代码。
release包也会定期打包，但是会慢一些

**Comment by kazaff** [comment]
ok~谢谢解惑~~回头自己打包一个~

**Comment by Bosn** [comment]
经复现确实存在问题，修复中...

**Comment by Bosn** [comment]
问题已修复 commit 67b4dc9a387e21b95695b32f907d18b8592ed651

**Comment by Bosn** [comment]
请关注下一个release版本

**Comment by kazaff** [comment]
我关注的就是release，但是你这个修复只针对master啊~

**Comment by Bosn** [comment]
不要急，一会儿到公司我合入release，reopen，合好了我再close

**Comment by kazaff** [comment]
ok~

**Comment by Bosn** [comment]
master合入release 完成，请留意：commit 1d07e1750e38c505525f15d757e1c9b3ed9eeeac

**Comment by FinalDream1991** [comment]
在最新的 release 中，该 BUG 依然存在
