### ISSUE TITLE
如何实现根据请求参数中设置的total来输出对应条数的json数组

### ISSUE THREAD

**Issue by kazaff** [thx/RAP#120]
在列表页面，通常是在请求中携带如：total，count等参数用来指定获取对应数目的结果，请问这个需求如何在RAP中实现？

**Comment by Bosn** [comment]
看文档... [https://github.com/thx/RAP/wiki/user_manual_cn#根据请求参数来动态生成mockjs模板](https://github.com/thx/RAP/wiki/user_manual_cn#根据请求参数来动态生成mockjs模板)

**Comment by kazaff** [comment]
我指的是循环输出指定个数的返回结果，而不是入参和出参简单的绑定啊，文档里只有这一部分和我的需求i相关：https://github.com/thx/RAP/wiki/user_manual_cn#%E6%9C%80%E5%A4%96%E5%B1%82%E4%B8%BA%E6%95%B0%E7%BB%84%E7%9A%84%E6%8E%A5%E5%8F%A3

但是，这也是写死的length

**Comment by Bosn** [comment]
懂了，@nuysoft 呼叫墨汁老师，虚拟根什么时候支持哇？最外层结构类似问题多到要哭了。。。。跪求支持虚拟根啊

**Comment by Bosn** [comment]
最外层结构问题我会尽快推进解决，但不得不说楼主直接返回数组不太明智，好歹给自己留个接口处理错误信息和错误码啊，还有页码信息。。。直接返回数组结果集的做法非常不推荐

**Comment by kazaff** [comment]
恩，谢谢提醒，如果是返回对象，那这个场景目前存在解决方案么？

**Comment by Bosn** [comment]
如果返回对象就不存在这个问题了啊，直接通过字段key利用Mock.js语法就可以实现，例如："arr|10"。

但最外层的Mock规则的设置确实是个问题，这个我们会尽快解决。

**Comment by kazaff** [comment]
这个字段"arr|10"的“10”可以根据入参进行设定么？我已经看过mock.js的DTD和DPD，也仔细看过RAP的文档，确实还是不清楚要咋做啊~请别嫌我啰嗦~~

**Comment by Bosn** [comment]
根据入参值动态生成规则是我这边RAP处理的，一会儿我看下，不支持加上就好。

**Comment by kazaff** [comment]
恩，谢谢，我想当然的会怎么写：

> arr|@mock=${total}

**Comment by Bosn** [comment]
NONONO，这里不需要@mock，@mock=只是为了区分备注和规则。。。这块儿是我的设计失误。下一个大版本我会把备注和mock规则分拆。

你写arr|${page} 就可以，不过这个key我好像没处理。一会儿我再看看，你先歇会儿。。。。

**Comment by kazaff** [comment]
sorry，测试按照如下写法是管用的：

> arr|${total}

我只是没有在文档上找到类似的示例，包括像@DATE，@TITLE等语法，不知道官方文档这部分的介绍放在哪里？

**Comment by kazaff** [comment]
好的，我等你消息~

**Comment by Bosn** [comment]
这块儿文档我补充下

**Comment by Bosn** [comment]
文档已更新：commit f5857f0676d2d05026e7eeaa0f608a0dcab88a85
