### ISSUE TITLE
描述能否支持Markdown?以及如何更好的添加枚举值定义

### ISSUE THREAD

**Issue by GrayLuo** [thx/RAP#123]
HI,各位，首先感觉各位无私的贡献，我们团队在使用RAP的过程中有时候会添加很多描述说明，而且有一定的格式，所以希望能够支持Markdown。
   其中这个问题来源于如何在某个接口参数中描述多个错误码和相关信息。比如
   {"response":{"code":1,"msg":"权限受限"}}
   我要描述code的几种错误码分别是什么，我不知道在哪里添加为好。
   希望能够得到您们的解答 @nunnly, @xinglie

**Comment by Bosn** [comment]
已加入到下个版本的需求中，这是很好的提议。
用户体验是RAP每个版本都要考虑的问题。


其实现在已有简单的办法实现代码高亮和格式化，在请求描述里用@code和@end：
```
@code [{"selectd_shop_name":"shaocui49","shop_name":"妖精emma"},{"selectd_shop_name":"","shop_name":"妖精emma"}] @end
```

可以暂时先用@code @end 试试哈，后续markdown我也会加进去。
