### ISSUE TITLE
有详细的java项目部署教程吗？部署教程太简洁了。不会Java部署呀

### ISSUE THREAD

**Issue by Osub** [thx/RAP#128]

**Comment by Osub** [comment]
部署办法
====

将war包修改为ROOT.war后放入tomcat webapps文件夹中

startup.sh(.bat)启动tomcat，该war包自动部署到文件夹ROOT

停掉服务器，打开ROOT中得WEB-INF`/classes/mysql.local.properties` 来修改数据库配置

启动tomcat，完成部署。

具体部署请查看GitHub [Wiki](https://github.com/thx/RAP/wiki)中得部署手册。

**Comment by Bosn** [comment]
Java应用开发和tomcat部署，超出支持范围... 

精力有限，十分抱歉。相关知识请自行学习，谢谢！

**Comment by Osub** [comment]
弄好了，这个war包藏得太深了，终于找到了，哈哈，谢谢，辛苦了

**Comment by KevinOfNeu** [comment]
@Osub 怎么做到的？

**Comment by Osub** [comment]
@KevinOfNeu   看这里https://github.com/thx/RAP/issues/134  。不过好像不是最新的

**Comment by Bosn** [comment]
@KevinOfNeu @Osub 最新的版本就是https://github.com/thx/RAP/issues/134   啊，也就是v0.11.2
最新的发布版本是的，版本发布定期发，relesae分支中的代码是最新的。

根据自己喜好选择更新方式...

**Comment by Osub** [comment]
@Bosn  我下载的是 rap_release_v0.11.2_20150430.war   部署之后，版本让然是v0.1
![2015-05-07 12 01 26](https://cloud.githubusercontent.com/assets/7599190/7508318/ec3ceaf6-f4b0-11e4-8e68-fd39a23c5008.png)
我已经重新部署3次了

**Comment by Bosn** [comment]
不用纠结这里显示的版本号，包的内容正确功能正确。这里显示问题下午我会check

**Comment by Bosn** [comment]
@Osub 已经查过了，这里显示的位置rap.template.vm并没有修改所以还是v0.10，但是不影响该版本的功能修复。
下一个版本会注意检查显示的版本号，先忽略即可。

**Comment by Osub** [comment]
ok,谢谢，但是mock的一些函数不能使用  比如@mock=@chineseName   生成的 是 “@chineseName”

**Comment by Bosn** [comment]
@Osub 不是一个问题不要在一个issue里讨论。。。会乱。。。

@mock如果是字符串类型，你写@mock=@chineseName生成的模板自然就是"key" : "@chineseName"  剩下的模板=>数据是由Mock.js解析的，如果解析错误仔细看下Mock.js上的规则文档，另外也看一下版本，如果是版本问题，可以自己升级下mock*.js文件。
