### ISSUE TITLE
Tab 切换添加路由

### ISSUE THREAD

**Issue by jasonslyvia** [thx/RAP#129]
![image](https://cloud.githubusercontent.com/assets/1336484/7343576/7f1cb3f6-ecf5-11e4-9e49-0a84644995be.png)

**Comment by Bosn** [comment]
在 commit 7cd186f 中已添加hash，用于定位action

**Comment by Bosn** [comment]
该问题已在commit a0fc80d 和 commit  7cd186f  中修复，因为涉及action id的类型改动，影响面非常大。

目前仅在master提交，合并到release还需要大量测试。
