### ISSUE TITLE
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致

### ISSUE THREAD

**Issue by 1742284240** [thx/RAP#1302]
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致
登录rap之后,隔一会儿刷新又要输验证码登录，烦死了，用户体验很差，差到极致

**Comment by gouguoyin** [comment]
欢迎体验phprap，http://www.phprap.com/
