### ISSUE TITLE
急需要支持导出swagger.json格式的功能！！！

### ISSUE THREAD

**Issue by Just2015** [thx/RAP#1316]
急需要支持导出swagger.json格式的功能，辛苦尽快支持这个功能吧，感谢！

**Comment by Just2015** [comment]
提前感谢RAP技术人员，快支持支持吧。全国技术人员苦不堪言。

**Comment by Just2015** [comment]
有人关注吗，有人关注吗

**Comment by bigfengyu** [comment]
不好意思，RAP1 已经停止维护了，建议用 RAP2 https://github.com/thx/rap2-delos
