### ISSUE TITLE
将projectDataOriginal以jsonp形式提供给外部使用

### ISSUE THREAD

**Issue by keyapril** [thx/RAP#132]
如题

**Comment by Bosn** [comment]
本来是v0.12的需求，要提前做了...

之前做了JSON SCHEMA的API，我自己都奇怪为什么要用奇葩的JSON SCHEMA。

需增加标准的JSON接口输出RAP文档数据结构，方便业务插件自行定制各种功能。

已加急处理...

**Comment by Bosn** [comment]
sorry sorry sorry

仔细看了下，这个在实现OpenAPI的时候，已经有了。
```
/api/queryRAPModel.do?projectId=652
```

直接用就好。
