### ISSUE TITLE
大家好，请教一个RAP系统 接口无法保存的问题‏

### ISSUE THREAD

**Issue by chudaozhe** [thx/RAP#136]
环境: linux, tomcat8, jdk8, mysql5.6.20

今天我装上了RAP系统，登陆注册等其他功能都正常，只有编辑完接口参数，无法保存，
提示Request URL:http://localhost:8080/workspace/checkIn.action 404错误，求指点，谢谢！

![rap20150503](http://test.cuiwei.net/rap20150503.png)

**Comment by Bosn** [comment]
亲是升级还是新安装呢？

如果是升级，很有可能亲没有执行迁移所需的数据更新脚本，请检查数据库更新脚本（详见版本发布的手册）

如果是新安装的，请提供下错误日志。
错误日志在tomcat的/logs/catalina.out中。

**Comment by chudaozhe** [comment]
@Bosn 谢谢回答，我的是新装，刚我观察了下日志，
[root@fedora logs]# pwd
/data/apps/tomcat/logs
[root@fedora logs]# echo ''> catalina.out 
[root@fedora logs]# tail -f catalina.out 

在点“秒存”的时侯没有日志输出
别的操作会有

应该是安装问题，明天我再到公司装一遍，3q

**Comment by Bosn** [comment]
亲，如果不在catalina.out里，请查看logs/localhost.out还有log/error***.log(注意log没有s）
如果以上均不行，修改log4j2.xml，将第二行WARN修改为DEBUG。

保存失败且404一定是后端错误，从现象来看应该是亲升级了RAP版本，但没有执行数据库更新，导致数据库结构错误而报错。请仔细检查版本手册中的**老用户迁移**部分，执行数据库迁移脚本。

**Comment by chudaozhe** [comment]
谢谢，果然是数据库的问题，重新clone一份，倒入initialize.sql就可以了，再次感谢～～

**Comment by ldh19816** [comment]
大牛，为什么sql文件搞这么多html代码，非要更改扩展名成html然后才能执行？？为什么要这么设计
