### ISSUE TITLE
ajax方法没有返回defer的问题

### ISSUE THREAD

**Issue by xiehuiqi220** [thx/RAP#137]
若使用promise的方式调用ajax，提示fail方法找不到。

**Comment by Bosn** [comment]
已加入到v0.12插件升级需求

**Comment by Bosn** [comment]
又有一个同学提了这个需求，优先级升高....

**Comment by fanhc019** [comment]
是的 遇到了同样的问题

**Comment by Bosn** [comment]
已经在 https://github.com/thx/RAP/commit/d8c1de7e5d013ece56f3e8f228f7479037054d34
中解决该问题，不过还木有测试哦.... 下一个版本会发布。敬请期待啦。

### 解决方法
使用$.ajaxPrefilter实现对异步方法的拦截，而不是此前覆盖$.ajax的方式。

感谢墨智@nuysoft 老师的指导。
