### ISSUE TITLE
出现无权限导致log创建不了cpu升高的问题

### ISSUE THREAD

**Issue by colincatsu** [thx/RAP#138]
解决办法是调整相应的权限。可以让rap创建log/文件夹

**Comment by Bosn** [comment]
这个问题我也遇到了，除了手动设置权限，还有别的更好的办法吗？
似乎是log4j2的问题。我参照文档做了log4j=>log4j2的升级，之后也遇到过权限错误。

**Comment by colincatsu** [comment]
我觉得不要把log放在 /apache-tomcat-7.0.52/bin下

**Comment by Bosn** [comment]
那放在logs里？毕竟程序发布要全量更新，所以放webApps肯定不合适

**Comment by colincatsu** [comment]
全量更新也无所谓吧 以前的日志肯定不能要了，否则出现这么不可预期的bug确实是个问题

**Comment by Bosn** [comment]
日志要一直保存，不能因为应用更新而废弃，这个我再研究下，可以放到logs里。

**Comment by colincatsu** [comment]
![Uploading image.png…]()

**Comment by colincatsu** [comment]
%Cpu(s): 46.8 us,  0.1 sy,  0.0 ni, 53.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   8098872 total,  1986580 used,  6112292 free,    21656 buffers
KiB Swap:  8306684 total,        0 used,  8306684 free.   229668 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND    
 1493 root      20   0 6754684 1.074g  12400 S 378.6 13.9  19:58.35 java       
    1 root      20   0   33476   2776   1472 S   0.0  0.0   0:02.15 init       
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd   
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+
    7 root      20   0       0      0      0 S   0.0  0.0   0:00.47 rcu_sched  
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.15 rcuos/0    
    9 root      20   0       0      0      0 S   0.0  0.0   0:00.02 rcuos/1    
   10 root      20   0       0      0      0 S   0.0  0.0   0:00.01 rcuos/2    
   11 root      20   0       0      0      0 S   0.0  0.0   0:00.01 rcuos/3    
   12 root      20   0       0      0      0 S   0.0  0.0   0:00.01 rcuos/4    
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.02 rcuos/5    
   14 root      20   0       0      0      0 S   0.0  0.0   0:00.02 rcuos/6

**Comment by colincatsu** [comment]
cpu 一直很高

**Comment by Bosn** [comment]
@colincatsu 表格有些乱啊，能确定是RAP服务占用CPU较高吗？
或者是否有什么服务在持续的访问RAP MOCK？

目前RAP服务在阿里的部署，服务460+业务项目还没有出现过CPU飙高的问题。
也可能是我的服务器太好了，哈哈。

**Comment by colincatsu** [comment]
还是那个写日志的问题，时好时坏的

**Comment by colincatsu** [comment]
可能是我们服务器太渣了
