### ISSUE TITLE
程序目录结构以及打包方式

### ISSUE THREAD

**Issue by KevinOfNeu** [thx/RAP#139]
首先承认RAP做的很贴心，就是我想要的，但是目前感觉目录结构不是很清晰，尤其是打包的时候，我觉得最好不要依赖这些IDE，应该有一些像maven之类的构建管理

**Comment by Bosn** [comment]
@KevinOfNeu 这个我有考虑，因为此前都是支持阿里巴巴自己的业务，绝大多数`用户`，都是直接使用部署好RAP系统的用户，我既是RAP的作者也是服务运维，所以部署的便捷性这块儿一直没有考虑。

后续为了更好的服务外网用户，这一块儿有计划在完善，具体的细节点，请提交到issues v0.12需求征集帖。Maven引入需求已采纳。
