### ISSUE TITLE
HTTP Method 校验

### ISSUE THREAD

**Issue by KevinOfNeu** [thx/RAP#140]
定义一个接口支持POST请求，但是GET请求也同样能用，有些业务场景是一个接口仅支持一种方法，这样无法做Method的校验、这算是一个enhancement吧

**Comment by Bosn** [comment]
你确定你试过了么？

现在因为实际链路走的是JSONP，不管定义的是什么协议，MOCK数据都是可以正常使用的。

**Comment by KevinOfNeu** [comment]
试过了，对于定义的POST请求的接口，我把链接+参数直接放在浏览器做GET请求，都OK的，小缺陷就是不做method检查，前端很有可能写错method调试的时候却浑然不知

**Comment by Bosn** [comment]
method后端会做校验，实际上后端已经通过http method做区分，但是为了迎合大部分用户（好多人根本不关心method字段），method错了也能产出mock数据，但是如果其它都一模一样只有method不一样的，也可以根据method精准匹配到正确的请求（restful）
