### ISSUE TITLE
有没有后台管理地址？

### ISSUE THREAD

**Issue by majian0331** [thx/RAP#143]
看到数据库是有角色之分，但是没有看到哪里有后台的入口，来控制成员的权限

**Comment by Bosn** [comment]
我还没做后台管理。。。
现在改角色是通过修改数据库表，见部署手册，搜关键字“管理员”

**Comment by majian0331** [comment]
修改了之后有什么功能上的变化么？我在tb_role_and _user中加了记录，但是登陆进去没发现有什么区别

**Comment by Bosn** [comment]
你都用一个账号，自己创建的项目当然自己能编辑了。。。。

你不用管理员账号，进别人创建的项目试试。。。


RAP暂时都是公司内部部署，所以权限管理比较弱。v0.12下个版本会加强。
