### ISSUE TITLE
如果我的接口是给手机客户端使用，并且不是跟rap在同一个服务器上，该如何处理来显示真实数据呢？

### ISSUE THREAD

**Issue by majian0331** [thx/RAP#144]
能不能实现我填写一个绝对的url地址，不同于rap所在服务器的地址，比如我的rap地址是:http://192.168.1.1:8080；但是我提供给客户端开发人员调试的接口是http://192.168.1.2:8080/api/user/register 这种情况下，怎么能通过rap得到真实的请求结果呢。

**Comment by Bosn** [comment]
RAP不会提供真实的请求结果.... RAP只能根据接口文档的格式生成模拟数据（即Mock数据）

而Mock数据的路径，请参照视频:[http://thx.github.com/RAP/study.html](http://thx.github.com/RAP/study.html)
中的Mock工具部分，有非常详细、清晰的视频讲解。

谢谢！

**Comment by majian0331** [comment]
哦，明白了，谢谢~
