### ISSUE TITLE
接口不支持批量转移

### ISSUE THREAD

**Issue by nunnly** [thx/RAP#145]
RT，目前接口可以单个的 *复制* || *转移*
今天发现页面太挤了，拖动起来阅读特别不方便，之前在0.12需求中也有提到。。
竟然发现不支持 *批量转移* ，当时第一感觉就是！`（╯‵□′）╯┴─┴  `
> 
霍雍 (15:42:10): 
亲可以提到issue，但是优先级目测一定最低。。。。-  。- 

啦啦啦，我来提了
(￣.￣)+

**Comment by Bosn** [comment]
都不带我超神，万年黄金5，天天打人机...
还好意思提issue！还卖萌！！！哼！！！！

**Comment by Bosn** [comment]
已加入RAP v100.1需求列表
