### ISSUE TITLE
无法注册，action 404

### ISSUE THREAD

**Issue by yanyu0517** [thx/RAP#147]
部署方式：war包部署
版本：rap_release_v0.11.2_20150430
tomcat：6.0.35
jdk：1.7.0_15
部署后，首页能够正常访问，但是无法注册用户
注册用户的action /account/doRegister.action 报404，然后页面就是大白板了

**Comment by Bosn** [comment]
数据库配置不对，正确初始化了么？按照部署手册操作。。。执行正确的初始化脚本。

**Comment by Bosn** [comment]
可以用登陆随便输入尝试，不熟正确告诉你密码错误或用户不存在，如果404说明系统错误，基本都是数据库配置有问题

**Comment by yanyu0517** [comment]
没有做数据库初始化，跑了脚本好了，非常感谢
我是用的war包部署，https://github.com/thx/RAP/tree/release/release这块没有关于初始化数据库脚本的说明
建议加上

顺便问下，release的war，部署后，WEB-INF/classes/database/initialize.sql是不是也是正确的数据库初始化脚本

**Comment by Bosn** [comment]
哈哈，抱歉，war包我后加的，我改下哈
