### ISSUE TITLE
后端小白如何进行部署

### ISSUE THREAD

**Issue by Chener** [thx/RAP#148]
之前捣鼓半天，后来在开发大大的帮助下终于搞好了。感觉像我这种对后端不太懂的小白安装起来可能还是有点困惑的，所以下面说明下：

既然是后端小白了，那么暂时就不需要关注源码或者使用最新的 release 版本，直接用[war包部署](https://github.com/thx/RAP/tree/release/release)就好。不用管那个部署手册的，因为不需要打包编译源码之类的。

当然以下条件还是要满足：
JDK 1.7+
MySQL 5.6.12+ // 太老的MySQL运行initialize.sql会报多timestamp错误
Tomcat 6.*+

如果你原来是 JDK1.6 的话，安装JDK1.7+后记得改环境变量并重启！（或者使用不需重启使环境变量更改有效的方法，具体谷歌百度都行）

其他的就按照 war包部署 里面的说明即可。

**Comment by Bosn** [comment]
非常感谢亲分享安装经验
Share给对J2EE开发/部署比较陌生的同学参考


谢谢！
