### ISSUE TITLE
RAP 数据库问题

### ISSUE THREAD

**Issue by Chener** [thx/RAP#150]
由于某些原因，我想把【项目A】下面的【模块a】移到【项目B】下面，因为【模块a】涉及接口较多，不想做那些枯燥的复制粘贴。

于是我把数据库表【tb_module】里面【模块a】对应的【project_id】由【项目A】改为了【项目B】，以为这样就好了，但是没有任何效果，把浏览器对应的 local storage, session, cookies 都删除了也不行。

请问这是为啥呢，难道还有其他关联的表么，没找到啊。

**Comment by Bosn** [comment]
NO NO NO NO.....

tb_module  / tb_page 等等这些对象模型，只是用于解析文档数据并生成MOCK数据等功能的。

而实际用于接口文档编辑的数据，存在于tb_project的project_data字段里...

所以你这样操作是没用的。

### 建议解决方案
跨项目移动/复制接口，暂时没有很好的方案。建议导出Mock数据之后，再把MOCK数据导入到对应项目的位置中。跨项目移动接口的需求还不多...

**Comment by Chener** [comment]
@Bosn 谢谢~
