### ISSUE TITLE
在Rap中mock出来的数据和通过url请求返回的数据完全不相同

### ISSUE THREAD

**Issue by magele758** [thx/RAP#151]
例如

    flowSource|2

我期望的返回是和mock返回的结果都是一致的：

    {
        "content":
        {
            "code":0,"data":
            {
                "flowSource":[
                {
                    "name":"直通车","orderRate":0.1906,"uv":890
                }
                ,
                {
                    "name":"淘内付费","orderRate":0.1606,"uv":878
                }
                ]
            }
        }
        ,"hasError":false
    }

但是在服务端返回的居然是：

    {"content":{"data":{"flowSource|2":[{"orderRate":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(0.1906,0.1606)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '16818';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"uv":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(890,878)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '16819';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"name":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\"\u76f4\u901a\u8f66\",\"\u6dd8\u5185\u4ed8\u8d39\")";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '16820';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}]},"code":0},"hasError":false}

**Comment by Bosn** [comment]
@magele758 RAP Mock服务产出的是Mock.js规则JSON，这样做的好处是当你指定10000条数据时，不需要真的网络传输10000条，只要传输规则即可。

RAP插件会负责Mock.js规则 => 实际数据的处理，并且也可以在控制台(console)中查看到数据结果。



如果你想要RAP直接返回data而不是mock rule，那么可以把路径中的/mockjs/改为/mockjsdata/即可。

默认返回的是规则。

**Comment by magele758** [comment]
@Bosn ，多谢，你的回复完美解决了我的问题，看来还要多看看文档。多谢！

**Comment by Bosn** [comment]
@magele758 不客气：）感谢亲的使用。

**Comment by vistamin** [comment]
返回服务器的真实数据，需要服务器对JSONP的支持吗？

**Comment by Bosn** [comment]
@vistamin 感觉亲有点混淆了，返回服务器的真实数据，你自己开发的前端代码，从真实服务器返回。该怎么返回就怎么返回，和RAP无关。

对于/mockjs/模拟数据接口，路径中的/mockjs/替换为/mockjsdata/的作用，就是由Java端去处理Mock.js规则 => 最终模拟数据的过程。和在前端引入Mock.js后调用Mock.mock({"rules":"规则数据"});是等价的。

**Comment by vistamin** [comment]
@Bosn 恩，看来我理解的有问题。RAP可以集成类似http://www.atool.org/httptest.php上面的功能吗？这样我可以直接利用在RAP上测试真实的接口，并且判断返回的值是否符合接口的规范。

**Comment by mqliutie** [comment]
mockjs 和 mockjsdata 的区别 ~~~ 马一下

**Comment by bad-mask** [comment]
Thanks
