### ISSUE TITLE
希望RAP可以提供OpenAPI接口，实现对Mock规则的API访问与管理

### ISSUE THREAD

**Issue by xunuo** [thx/RAP#153]
希望rap提供可以修改某个接口key-value的API，谢谢 :)

**Comment by Bosn** [comment]
已经实现的功能，但是因为QA提完了没用。。。就扔在那里了。
改动较大，所以我需要再改改才能放粗来。

具体见MockMgrImpl.java中的modify方法：
https://github.com/thx/RAP/blob/master/src/com/taobao/rigel/rap/mock/service/impl/MockMgrImpl.java

相关进度关注本帖更新...

谢谢，不用谢。

**Comment by Bosn** [comment]
# 技术设计

该接口提供了自动化测试工具通过RAP Open API修改、重置RAP MOCK规则的能力。

### 接口设计

为实现该需求，提供以下接口：

* modify接口，用于修改该项目的接口规则
    * 输入：规则JSON、接口ID
    * 输出：是否成功、错误信息
* reset接口，用于重置该项目所有的接口规则
    * 输入：接口ID
    * 输出：是否成功、错误信息

### 规则语法设计

采用JSON格式。

```json
{
    "requestParameterList" : [{
    	identifier: "customerName", // 不带mock规则的变量名，用于要修改的字段
    	identifierChange: "customerName|1-2", // 修改后
    	remarkChange: "@mock=123" // 修改后的规则参数
       parameterList: [{    // 子参数
           identifier: "id",
           ... 
           ... // 对象或装有对象的数组，可能无限嵌套下去，通过parameterList连接   
       }]  
    }]
```


### 由该API设置的规则如何使用
出于以下原因，通过该Open API设置的MOCK规则与常规的规则区分开：

1. 自动化测试会经常modify, reset，不应该影响到版本。
2. 自动化测试不应该干扰开发者自己设置的Mock规则。

因此，用户一般的Mock服务路径为：

```
http://{domainName}/mockjs/{projectId}/{relativePath}
```

而由该API设置的规则，生效后访问的Mock服务路径为：

```
http://{domainName}/mockjsauto/{projectId}/{relativePath}
```

### 自动化测试接口(/mockjsauto/)加载规则

1. 访问/mockjsauto/服务
2. 匹配到接口后与/mockjs/一样加载接口模型
3. 加载本API设置的规则数据，覆盖原模型
4. 继续走后续的mock数据生成逻辑

### 数据库设计

```sql
(
	action_id int(10) NOT NULL
		PRIMARY KEY,  
	rules text NOT NULL, -- JSON规则
	update_time datetime NOT NULL
		DEFAULT NOW(),    -- 最近更新时间

	FOREIGN KEY(action_id) REFERENCES tb_action(id)

	  DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by Bosn** [comment]
亲，开发结束了，为了确保符合你的需求，建议你用我机器临时IP试试。时间OK的时候旺旺找我要IP。

测试账号：test275  密码：123456，你也可以自己注册新的。域账号不能用。


测试modify：http://localhost:8001/api/modifyMockRules.do?actionId=624&rules={%22responseParameterList%22:[{%22identifier%22:%22act_price%22,%22remarkChange%22:%22@mock=189%22}]}

Mock数据接口效果：http://localhost:8001/mockjsauto/43/x?

最终数据：
```
{"price":71441,"desc":"\u6d4b\u8bd5\u5185\u5bb9u250","act_price":189,"countdown_sec":54565,"shop_title":"\u6d4b\u8bd5\u5185\u5bb938qw","outer_id":"\u6d4b\u8bd5\u5185\u5bb9ln6c","promotions":[],"coupons":[],"detail_url":"\u6d4b\u8bd5\u5185\u5bb94w8u","title":"\u6d4b\u8bd5\u5185\u5bb9cevd","num":61425,"pic_url":"\u6d4b\u8bd5\u5185\u5bb9gu94","wap_detail_url":"\u6d4b\u8bd5\u5185\u5bb98f25","num_iid":"\u6d4b\u8bd5\u5185\u5bb9s38q","nick":"\u6d4b\u8bd5\u5185\u5bb9yknj","earnest":84155}
```

可以看到189设置成功。

@xunuo

**Comment by xunuo** [comment]
赞！ 我试试看！

**Comment by Bosn** [comment]
感谢亲的五星好评... :3

如旺旺沟通，有一个Mock缓存导致的BUG，修复后计划本周末发布哦，下周使用有问题再找我咯，HOHOHO

**Comment by Bosn** [comment]
BUGs也修复完了哦，下一个部署版本即将生效，敬请期待：）
