### ISSUE TITLE
关于密码问题，确定就是这么玩的吗？

### ISSUE THREAD

**Issue by x03570227** [thx/RAP#154]
环境：

os: ubuntu-server

version:0.11.2

用RAP有段时间了，从比较老的版本开始，最近在自己服务器部了个，因为要给合作的人使用，然后原来不是问题的问题也来了，首先就是密码，找遍整个系统，没找着改密码的功能，系统是不是就是这么玩的？

现在的办法是，用 StringUtils. getDoubleMD5("密码")，然后到数据库，把对应用户的密码更新掉以解决密码重置问题

在找这个问题的解决方法的同时，又发现，不管什么账号，密码只要输入：""，都可以登录，要纠正这个问题就得自己个性代码，重新编译WAR包，这算BUG吗？还是就这么玩的？

以上两个问题，实在有些不解，请在后面版本解决下

**Comment by Bosn** [comment]
你确定你不输入密码可以正常提交登陆表单？

### 对于RAP的权限、安全性
因为RAP此前都是内部使用，外部无法访问，权限控制上做的比较弱，这也是v0.12规划中需要加强的部分。**所以RAP暂时不适合对外部署**。

### 关于RAP万用密码
为了方便调试问题，RAP是有管理员万用密码的，在PRIVATE_CONFIG.java中的adminPassword中设置。这里我没有判空，这个问题我会修复下。你可以通过把这里设置成复杂的串来禁止万用密码生效。

### 加密方式
目前RAP的加密采用的是简单的双重MD5加密，在后续会考虑运用映射加强加密。因为RAP都是自己公司、自己团队自己部署，开放到外网去的需求并不大.... 这块儿如果有特殊需求也可以自己开发。比如我们阿里巴巴内部使用都是通过域账号ACL接入，并不会使用RAP本身的账号系统。

**Comment by Bosn** [comment]
fixed in https://github.com/thx/RAP/commit/34b337e945089e72a2fd8515674585787e1fb472

**Comment by Bosn** [comment]
下一个release会解决该问题。着急的话，可以根据提交的源码自行修改。
