### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by explorerit** [thx/RAP#156]
好像缺少com.alibaba.*包，导致编译不通过。
有的地方确实导入了，但确实没有这些包，如何解决

**Comment by Bosn** [comment]
仔细部署手册，或者直接用war包

要用release分支

**Comment by explorerit** [comment]
如果部署的项目不是根目录，带有项目名称，如何改url规则，我改了.vm里的路径，但不能全部改变，还是有很多链接走的是根目录路径

**Comment by Bosn** [comment]
目前版本暂时不支持不在根目录的情况...
后续版本会考虑支持自定义二级目录。

**Comment by explorerit** [comment]
哦，好吧，thx
