### ISSUE TITLE
请关闭RAP插件劫持AJAX时的console调试信息，建议使用URL get 参数控制

### ISSUE THREAD

**Issue by openwings** [thx/RAP#157]
请关闭RAP插件劫持AJAX时的console调试信息，建议使用URL get 参数控制。

如果页面有10+AJAX请求，console控制台就被霸占了

默认开启，如果传递rapdebug=0（如果直接使用debug关键字可能会引起开发冲突）时关闭console信息。

**Comment by Bosn** [comment]
### 使用方法

在加载脚本的script中，增加参数disableLog=true，例子：

```html
<script src="http://{domainName}/rap.plugin.js?projectId=43&disableLog=true"></script>
```

**Comment by Bosn** [comment]
因为mock.plugin.js回滚，该问题reopen

**Comment by Bosn** [comment]
Fixed in commit 836b0fbfeba65ad8d18a63aa500266be00b0bb2d
