### ISSUE TITLE
希望能增加一个自动运行脚本用的接口数据校验逻辑服务

### ISSUE THREAD

**Issue by ucliweiguang** [thx/RAP#163]
主要需求如下：
我们会执行开发自动运行脚本，然后调用RAP提供的接口去校验我们自有服务器（生产或测试服务器）上的接口（这些接口在RAP里面已有定义和字段校验规则）。
我们提供：部署在自有服务器上接口的地址、输入参数、对应RAP上的接口信息（如接口id）
返回：我们测试的接口的结果。我们的接口数据是否在RAP上定义的校验规则。
如果全部符合，可简单的返回全部成功的标识；
如果有不符合，返回哪些字段是什么原因不符合即可。
谢谢啦。

**Comment by Bosn** [comment]
### 技术设计
在Open API模块增加新接口

```
http://{domaiName}/validate/{relativePath}
```

其中，{relativePath}为相对路径，与mock服务类似。例如：真实后端接口为http://xxx/getJson.php，则这验证接口为：http://{domainName}/validate/**getJson.php**.

#### 入参

* isRequest boolean true表示校验请求参数，默认为false
* paramList {array<Object>} 需要校验的参数列表，JSON格式。最外层必须为数组。

#### 出参

待定，与mockjs插件返回的validate数据一致

**Comment by Bosn** [comment]
亲，开发结束了，为了确保符合你的需求，建议你用我机器临时IP试试。时间OK的时候旺旺找我要IP。

测试账号：test275  密码：123456，你也可以自己注册新的。域账号不能用。

### 校验API测试
```
http://localhost:8001/validate/43/x?json={%22coupxxons%22:[],%22acxxt_price%22:189,%22price%22:40873,%22shop_title%22:%22\u6d4b\u8bd5\u5185\u5bb95y9z%22,%22num%22:32644,%22title%22:%22\u6d4b\u8bd5\u5185\u5bb9bpux%22,%22promotions%22:[],%22num_iid%22:%22\u6d4b\u8bd5\u5185\u5bb92k3r%22,%22pic_url%22:%22\u6d4b\u8bd5\u5185\u5bb95iq5%22,%22desc%22:%22\u6d4b\u8bd5\u5185\u5bb9hbq5%22,%22countdown_sec%22:21553,%22nick%22:%22\u6d4b\u8bd5\u5185\u5bb98519%22,%22wap_detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb90197%22,%22outer_id%22:%22\u6d4b\u8bd5\u5185\u5bb92u8n%22,%22detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb9463m%22,%22earnest%22:85535}
```

```json
{"left":[{"type":"LOST","property":"coupxxons","namespace":"obj"},{"type":"LOST","property":"acxxt_price","namespace":"obj"}],"right":[{"type":"LOST","property":"coupons","namespace":"obj"},{"type":"LOST","property":"act_price","namespace":"obj"}]}
```

这里返回了左边右边对比时，有差异的字段。具体TYPE=LOST和其它类型的含义，见稍后梳理出的文档。谢谢！
