### ISSUE TITLE
请问能否增加批量导入功能

### ISSUE THREAD

**Issue by youhua** [thx/RAP#164]
我们在搭建RAP之前已经有了很多接口，期望能够有简单方便的方式批量将之前的接口导入到RAP中

**Comment by Bosn** [comment]
目前导入接口的方式，就是JSON导入。批量的话，也要有统一的格式才能实现你所说的批量导入，而这样的话和JSON导入比起来更麻烦。


RAP路由器是提供白名单模式的，老接口走老的，RAP文档中写的新接口MOCK数据才会走新的。
并不会影响新老接口共存。

如果希望把老的放进来，建议使用JSON导入功能。
