### ISSUE TITLE
import com.alibaba.buc.sso.client.util.SimpleUserUtil; 这个包找不到，怎么破

### ISSUE THREAD

**Issue by zhangzhao8668** [thx/RAP#166]
import com.alibaba.buc.sso.client.util.SimpleUserUtil; 这个包找不到，报错，怎么破

**Comment by zhangzhao8668** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by Bosn** [comment]
问过无数遍的问题啊
部署手册里写的很清楚，要用Release分支。
Master很多东西不对外公开的....
