### ISSUE TITLE
希望开放项目配置信息的json接口

### ISSUE THREAD

**Issue by lichenhao** [thx/RAP#167]
RT，
为了方便在node端进行接口拦截，mock，validate 功能。希望增加一个json接口，方便扩展node中间件。

**Comment by Bosn** [comment]
能再具体一些么？要配置啥
请具体描述下接口，我可以开发。

**Comment by lichenhao** [comment]
开放当前项目的相关配置信息的json接口。接口中主要包含：1. 接口列表（用以匹配做路由拦截适配）2. mock映射（用以在拦截后做接口mock）3.校验是否接口是否正常（据说在和iftest合作，这个功能是否有考虑内置或者转发到iftest平台，做为一个完整的平台来服务）

**Comment by Bosn** [comment]
1. 已经有了，见Wiki里，RAP用户手册，开放API部分的API3
1. mock映射是啥东西？
1. 这个也有了，最近刚开发完，详见 #163

**Comment by lichenhao** [comment]
Nice~ 看了一下wiki。基本想要的都在了。
