### ISSUE TITLE
需求：提供控制最外层数据结构的功能

### ISSUE THREAD

**Issue by xunuo** [thx/RAP#168]
目前的响应结果只支持一种情况，希望能够提供一个用于标记分组的约定，如@、__root__，让用户可以选择或随机的输出指定组的响应值 :)

**Comment by Bosn** [comment]
技术设计

虚拟根

在RAP中，当节点名称为__root__时，Mock数据会将__root__的值作为返回，返回结果不会包括__root__，从而达到控制最外层结构的目的。

实现方案

MockMgrImpl中对特殊根节点__root__做处理

对于/mockjsdata/，仅将__root__属性的值输出即可。
对于/mockjs/，在RAP插件中对__root__进行特殊处理。
若既未使用后端Mock数据生成（/mockjsdata/)也没有使用插件，需要自行处理__root__特殊属性。

**Comment by treblam** [comment]
还是不太明白。如果一个接口根据不同的情况返回不同的结果，在规则定义的时候如何通过_root_来描述这两种不同的结果呢？能否详细描述一下？
