### ISSUE TITLE
不知道这个算不算Bug，自动化测试没通过

### ISSUE THREAD

**Issue by lc60005457** [thx/RAP#171]
get-mockjs-rule: jQuery - getMockjsRule - /mockjs/projectId/action (2, 0, 2)Rerun94 ms

    mockjs rule: a|1-10 is in data
    Source: 	

    .success@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev line 3 > eval:12:10
    x.Callbacks/c@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:3:26031
    x.Callbacks/p.fireWith@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:3:26840
    k@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:5:14256
    .send/r@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:5:18646

    and dataType is number
    Source: 	

    .success@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev line 3 > eval:13:10
    x.Callbacks/c@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:3:26031
    x.Callbacks/p.fireWith@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:3:26840
    k@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:5:14256
    .send/r@http://120.26.78.245:8888/stat/js/base.js?_r=20140923.v0.11.dev:5:18646

**Comment by Bosn** [comment]
十分抱歉，这个测试是我自己机器上使用的，因为亲的数据里里没有用例数据所以不通过。

release里稍后我会去掉测试按钮。

**Comment by Bosn** [comment]
亲的版本可能较旧，目前最新Release代码已经注释了“测试”按钮。https://github.com/thx/RAP/blob/release/WebContent/tcom/template.rap.vm

后续发布新的Release会更新，谢谢。
