### ISSUE TITLE
请问admin的初始密码是多少呢？

### ISSUE THREAD

**Issue by dreamrepo** [thx/RAP#172]
RESERVED是不对的，试了SHA1和MD5也不行，至少要在文档上写清楚吧，不然只能看代码了

**Comment by Bosn** [comment]
因为数据库做了两次MD5加密，亲可以注册个小号再设置其为管理员（方法见部署手册）

如果一定要给预设的admin设置密码，可以同样注册个小号，密码设置好后将加密后的密码在数据库中复制过去。
