### ISSUE TITLE
校验API测试接口时，发现数组类型字段校验问题

### ISSUE THREAD

**Issue by ucliweiguang** [thx/RAP#175]
我的接口定义中，其中有一些字段是数组类型，但可以无数据，如其中一个字段“error”是数组类型，在RAP的IDE上选择“array”，在真实API返回的数据中字段“error”是error: [ ],。但RAP 校验API接口仍然提示“ 数据类型与接口文档中的定义不符”。
我的测试项目在10.62.2.212:8001中登记，projectid是666，接口请求Url:  page/index

RAP校验API返回数据如下：
```json
{
    "result": {
        "left": [],
        "right": [{
            "type": "TYPE_NOT_EQUAL",
            "property": "error",
            "namespace": "obj"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "tabs",
            "namespace": "obj.data.subject[0]"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "sub_title",
            "namespace": "obj.data.subject[0].video_list[0]"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "create_time",
            "namespace": "obj.data.subject[0].video_list[0]"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "slider",
            "namespace": "obj.data"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "live",
            "namespace": "obj.data"
        },
        {
            "type": "TYPE_NOT_EQUAL",
            "property": "hotword",
            "namespace": "obj.data"
        }]
    },
    "resultStr": "参数 obj.error 数据类型与接口文档中的定义不符\n参数 obj.data.subject[0].tabs 数据类型与接口文档中的定义不符\n参数 obj.data.subject[0].video_list[0].sub_title 数据类型与接口文档中的定义不符\n参数 obj.data.subject[0].video_list[0].create_time 数据类型与接口文档中的定义不符\n参数 obj.data.slider 数据类型与接口文档中的定义不符\n参数 obj.data.live 数据类型与接口文档中的定义不符\n参数 obj.data.hotword 数据类型与接口文档中的定义不符"
}
```

**Comment by Bosn** [comment]
@ucliweiguang 已修复，是对array类型默认mock数据为数字的BUG导致的校验错误。
请试试还有没有其它问题。

另外亲再有需求 #153 的相关问题，直接在该issue里回复即可，不用新开issue了哟

**Comment by ucliweiguang** [comment]
我的测试请求数据是：
{"success":true,"apiVersion":"1.1.1","error":[],"data":{"subject_total":15,"subject":[{"id":"2217","title":"\/\/Just In","icon":"","link":"","is_more":"0","tabs":[],"video_list":[{"subject_rank":1,"id":"6234533","src_id":"28","src_name":"youtube-cooperate","channel":"\u77ed\u89c6\u9891","genres":"People","type":"short","title":"Hero | Official Trailer introducing Sooraj Pancholi & Athiya Shetty | Salman Khan","sub_title":null,"summary":"Sooraj Pancholi and Athiya Shetty redefine the meaning of Love, Rebel and Freedom! \n\nWatch the most awaited trailer of HERO featuring Sooraj Pancholi & Athiya Shetty for the very first time.\n\nThe film","duration":175,"play_url":"http:\/\/www.youtube.com\/embed\/6k3wapAOu-M","platform":"1","img_url":"http:\/\/img.ucweb.com\/s\/mediana\/g\/uc_video_gj\/1zhx1Fcei-6T5386aL","is_banner":"1","corner":"","update_time":"2015-07-15 21:27:11","create_time":null,"down_id":"911028836","download_url":"http:\/\/ienjoy-782380406.ap-southeast-1.elb.amazonaws.com\/download?url=https%3A%2F%2Fwww.youtube.com%2Fembed%2F6k3wapAOu-M%3Fenablejsapi%3D1"},{"subject_rank":2,"id":"6254961","src_id":"28","src_name":"youtube-cooperate","channel":"\u77ed\u89c6\u9891","genres":"Hollywood","type":"short","title":"The Revenant - Trailer","sub_title":null,"summary":"The Revenant Trailer 1 German Deutsch US | Full Movie (Ganze Filme) bei Amazon Prime Instant: http:\/\/amzn.to\/1spiW9p | Schauspieler: Tom Hardy, Leonardo Di Caprio... | Kinostart: 14.Januar 2016 | OT:","duration":180,"play_url":"http:\/\/www.youtube.com\/embed\/ZZGJNhi1R94","platform":"1","img_url":"http:\/\/img.ucweb.com\/s\/mediana\/g\/uc_video_gj\/1zhOczHwH-6T3386aL","is_banner":"0","corner":"new","update_time":"2015-07-20 11:34:06","create_time":null,"down_id":"911028836","download_url":"http:\/\/ienjoy-782380406.ap-southeast-1.elb.amazonaws.com\/download?url=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZZGJNhi1R94%3Fenablejsapi%3D1"},{"subject_rank":3,"id":"6258941","src_id":"16","src_name":"mrpopat-cooperate","channel":"\u77ed\u89c6\u9891","genres":"People","type":"short","title":"Champayi Rang Yaar Aa Jaye - Janisaar","sub_title":null,"summary":"Presenting Champayi Rang Yaar Aa Jaye from Janisaar.
\r\n
\r\nTitle - Champayi Rang Yaar Aa Jaye
\r\nMusic - Muzaffar Ali & Ustad Shafqat Ali Khan
\r\nLyrics - Nawab Wajid Ali Khan
\r\n","duration":185,"play_url":"http:\/\/mrpopat.in\/embed.php?id=228949","platform":"1","img_url":"http:\/\/img.ucweb.com\/s\/mediana\/g\/uc_video_gj\/1zhO6VwMU-38F346aL","is_banner":"0","corner":"new","update_time":"2015-07-22 02:12:33","create_time":null,"down_id":"911028836","download_url":"http:\/\/dl.mrpopat.in\/VideoDownload\/CDN\/2015072114374826281235839231.mp4"}]}],"slider":[],"live":[],"hotword":[]}}
