### ISSUE TITLE
可以增加request的mock功能么

### ISSUE THREAD

**Issue by izig** [thx/RAP#176]
现在有接口response的mock功能。希望可以增加对request的mock功能，生成request的json模版，省去了手动编辑请求报文的麻烦，提高开发人员对服务端接口进行调试的效率。

**Comment by Bosn** [comment]
request的JSON....

request只能是key/value对儿啊，只能某个参数是JSON。亲想得场景有些抽象。
假设我是一个后端，亲想要的功能实现好了，是如何使用request mock的呢？

response只要数据结构对，在前端展现大都不会有问题。反过来却不是的，如果请求参数是无效的，后端通常会报错。

亲的需求可以再细化下...... 另外不知道亲RAP使用了多久，用在多少接口上了？
