### ISSUE TITLE
导入json数据 mock查看的时候报错

### ISSUE THREAD

**Issue by JihanChen** [thx/RAP#177]
我在接口返回数据导入json数据格式是
{
    "res": "0",
    "description": "ok",
    "result": [
        {
            "id": 1,
            "originalUnit": "kg",
            "targetUnit": "g",
            "targetUnitMultiplier": "1000"
        },
        {
            "id": 2,
            "originalUnit": "kg",
            "targetUnit": "斤",
            "targetUnitMultiplier": "2"
        }
    ]
}

可是当我点开 pageTester 页面  request starting, url: http://localhost:8080/mockjs/1/test/getjson?
点开之后就报错了 要是没有数组样式数据是没问题的，这是怎么回事？

**Comment by Bosn** [comment]
报什么错... 现象是什么，请描述清楚。

**Comment by JihanChen** [comment]
Error: Parse error on line 1:
...t|3":[{"targetUnit":function() {   var w
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['    
点开 request starting 链接主要是这个错误信息   
现象：我先在页面新建一个模块，模块下面新建一个接口，然后在 【响应参数列表】添加上面格式的json
数据 显示ok 的，我点击模块的跳转符号到pageTester页面，然后点击【mockjs数据】这个按钮出现了之前添加的json 数据，在左下角地方有个浮动 【 request starting, url: http://localhost:8080/mockjs/1/test/getjson?】 我点击之后跳转一个新页面 出现了上面的Error 我在js 通过引入插件 访问该接口地址 好像也没数据返回 只是提示说 
Current RAP work mode: 3 (0-disabled, 1-intercept all requests, 2-black list, 3-white list)
没有数据可获取

**Comment by Bosn** [comment]
你自己打开新页面，你自己的浏览器插件当做是JSON解析这个页面，但实际不是JSON，因为有函数对象做value，自然会报错。

但那是你自己浏览器插件的问题，不影响使用。

插件使用后如何返回数据，你使用插件的代码都不贴，鬼能知道啊

**Comment by JihanChen** [comment]
<html>
<head>
<script src="jquery-1.8.3.min.js"></script>
	<script src="http://localhost:8080/rap.plugin.js?projectId=1"></script>
</head>
<body>
<h2>简单测试获取mock数据</h2>

<script type="text/javascript">
    $(function($) {
    	$.ajax({
    		  url: "/test/getjson",
    		  success: function(data){
    		   console.log(data);
    		  }
    		});
	
	});

</script>
</body>
</html>

这个是我简单的使用插件的代码 ，我在rap里新建一个其他的接口 返回数据导入
{
"res": "0",
"description": "ok"
}
这样就可以正常获取的  所以对于嵌套数组没法获取还是搞不懂

**Comment by Bosn** [comment]
我排查下，有可能是本周Release合入了大量新功能还未稳定，

建议如果着急使用，可以先用Issues中正式发布版本的war包。

**Comment by Bosn** [comment]
查到原因了，是RAP插件之前用ajaxPrefilter做拦截，但是没能将JSON转成JSONP导致。

找到了一些解决方案，具体实现还需要再研究下。

http://jsfiddle.net/FdGzS/
http://bugs.jquery.com/ticket/10975

**Comment by Bosn** [comment]
已通过回滚mock.plugin.js临时解决

具体ajaxPrefilter实现的可行性需要进一步测试和调研。

**Comment by JihanChen** [comment]
好的 时刻关注

**Comment by JihanChen** [comment]
问下我把 mock.plugin.js 也回滚  但是貌似还是不行  其他地方还有影响到吗？

**Comment by Bosn** [comment]
@JihanChen 你自己回滚。。。。你知道回滚到哪个版本么？

别着急啊，我刚刚才merge到release分支，你现在pull下应该可以了。。。。

**Comment by Bosn** [comment]
就是现在

**Comment by JihanChen** [comment]
- - 我是看你改了 mock.plugin.js 还以为好了 我再试试  @Bosn
