### ISSUE TITLE
页面显示部分乱码

### ISSUE THREAD

**Issue by JihanChen** [thx/RAP#178]
经过部署多次调试发现 log.js 中写死的title 和name 中文字渲染到 log.vm中时候出现乱码 其他还有一些地方也出现乱码

**Comment by Bosn** [comment]
这应该是你自己文件编码问题了，编码应该是UTF8，你的IDE估计设了什么GBK或者其它鬼编码，把文件编码搞乱了....

怎么设置文件编码，自己google下，根据你的IDE(MyEclipse/Eclipse/IDEA/WebStorm...) 去搜索

**Comment by JihanChen** [comment]
不是ide 问题 我编码全程utf8 现在找到问题了  web.xml需要配置编码格式 问题已解决

**Comment by Bosn** [comment]
@JihanChen 肿莫解决的具体说一下吧，给以后的同学留个方案...

不过之前配置的同学还木有出现过你说的问题，有可能与特定环境有关。

**Comment by JihanChen** [comment]
在web.xml 下面添加下面代码

	<filter>
		<filter-name>encodingFilter</filter-name>
		<filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
		<init-param>
			<param-name>forceEncoding</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>

**Comment by JihanChen** [comment]
是跟某些环境有关系的 具体我还不知道什么环境出现乱码 我本地怎么也出现不了乱码问题 ，不过加上上面编码配置是解决了问题的

**Comment by Bosn** [comment]
好的，我会在web.xml加上这个代码。

**Comment by edagarli** [comment]
tomcat部署正常。可是jetty上就不行了。乱码

**Comment by edagarli** [comment]
<img width="314" alt="2016-11-14 23 33 32" src="https://cloud.githubusercontent.com/assets/5710228/20270629/c8f5c9fe-aac2-11e6-849e-203faa85d959.png">

**Comment by edagarli** [comment]
<locale-encoding-mapping-list>
        <locale-encoding-mapping>
            <locale>zh</locale>
            <encoding>UTF-8</encoding>
        </locale-encoding-mapping>
</locale-encoding-mapping-list> 
加了

**Comment by alswl** [comment]
@edagarli 我也发现 Jetty 部署了乱码，你有解决么？

**Comment by totoice** [comment]
加上下面的就好了
<filter-mapping>
        <filter-name>encodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
