### ISSUE TITLE
整理部署手册/录制部署视频/重录使用教程

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#179]
很多关注RAP的朋友表示Java不太会的亲玩起RAP来很吃力啊有木有

需要好好整理下部署手册啊有木有

最好有一连串教大家如何从0用war包部署，如何用IDE部署的或视频呀有木有！！！

好吧，一切都会有的。有什么想法、建议、意见请跟帖。

**Comment by carlos121493** [comment]
对，极力支持，现在有视频了么？

**Comment by nunnly** [comment]
hehe

**Comment by wsszh** [comment]
表示下载了war包后，就不知道咋办了。。求指教

**Comment by Bosn** [comment]
最近封闭开发。。。等被放出小黑屋的就开始录。
另外争取搞个环境校验工具哎

**Comment by Firxiao** [comment]
已在wiki中添加centos 及ubuntu下的部署文档

**Comment by Bosn** [comment]
@Firxiao 收到，非常感谢！

**Comment by carlos121493** [comment]
弄好了，配置的服务器是mysql，貌似是socket的链接方式？所以，和数据库的交互都不成功直接白屏

**Comment by Bosn** [comment]
部署手册已更新...  

感觉已经比较清楚了，觉得有问题再反馈。
