### ISSUE TITLE
建议：请求参数中增加“是否必需”的定义

### ISSUE THREAD

**Issue by e2ghost** [thx/RAP#181]
搜了一下issue好像没有提到过，不过感觉有这种应用场景。

比如透过不同的样式来区别或者加星号，这样在API沟通的时候能够一眼看出必需的参数。

**Comment by Bosn** [comment]
备注里标注下就可以了，一般情况默认都是必选，哪些是可选的在备注里写上optional或可选就可以。

**Comment by e2ghost** [comment]
可能我的例子相对个别一点吧，虽然可以在备注里添加，不过像这种情况看起来还是会不太整齐。。。
![xxg](https://cloud.githubusercontent.com/assets/349966/8950139/dac87440-35ef-11e5-8421-06d31f170600.jpg)

**Comment by Bosn** [comment]
亲，如果大都是optional。。。。标注下required就可以了啊  😂
