### ISSUE TITLE
自测功能自动化

### ISSUE THREAD

**Issue by JihanChen** [thx/RAP#182]
是否可以在接口旁边出现一个按钮，点击按钮跳转到一个页面，里面可以填写requestParam,还有一个具体的域名地址（真实数据执行的域名或ip）然后下面有个按钮，比如就叫自测，当填写好所有的请求参数和域名点击自测然后后台进行处理请求真实数据接口地址，然后获取的数据和rap里的mock返回数据进行validate 之后就像 API4：校验真实数据的正确性 这样进行显示比较数据格式结果

**Comment by Bosn** [comment]
后续会有这方面的规划。。。。

当然，目前还木有实现。

以为有跨域的问题，所以请求需要在后端去发这个请求，相关的用例功能也需要做保存和设计...
