### ISSUE TITLE
同一个接口返回不同的数据接口要怎么写呢？

### ISSUE THREAD

**Issue by think2011** [thx/RAP#183]
例如有一个接口`/getUser`

成功时返回 
```json
{
"success": true,
"id": 100
}
```

失败时返回
```json
{
"success": false,
"error": "出错了这样"
}
```

请问这种情况的接口要怎么定义呢？

**Comment by Bosn** [comment]
目前一个接口对应的是一个“接口的格式”

亲说的情况，在现有RAP的设计上会被理解为2个接口。

类似问题也有同学提过，会在近期做完善。

感兴趣可以参考issue #168

**Comment by think2011** [comment]
@Bosn  又见酱油大神\(^o^)/~

**Comment by Bosn** [comment]
@think2011 嘘，低调低调。

**Comment by think2011** [comment]
🙊 感谢回答
