### ISSUE TITLE
pageTester 页面点击mockjs 数据会去请求两次

### ISSUE THREAD

**Issue by JihanChen** [thx/RAP#184]
在pageTester 页面点击mockjs 数据或者mockjs模板 会发出两次请求 有什么原因吗？

**Comment by Bosn** [comment]
第二次是为了校验格式是否正确，当你把根路径写成服务器真实后端接口时（需支持JSONP)就会对其进行校验。

所以，第一次是取右上角填写的根路径拼装出来的请求返回的数据。
第二次是固定从RAP返回mock数据用于校验第一步。

正常两个都是一个请求，所以校验一定不会出错。

**Comment by JihanChen** [comment]
你说的是
 Y.jsonp(url, {
                    on : {
                        success : function() {
                            var realData = testResHandler.apply(this, arguments);
                            if (RAP_ROOT != baseUrlOrigin) {
                                Y.jsonp(rapUrl, {
                                    on : {
                                        success : function(response) {
里面的 url 和 rapUrl 吗？
我是说点击annual时候触发事件 调用  form.one('.btn-run').on('click', function(e) {} ，你这个重复执行了两次请求！ 还有像你说的第二次是为了校验格式是否正确，我把路径写真是后端接口地址时候是报错的，应该是js 没有处理好.错误：Uncaught SyntaxError: Unexpected token :

**Comment by Bosn** [comment]
自己百度一下JSONP，并且再仔细看下第一个回帖。
