### ISSUE TITLE
关于将war部署tomcat上后，数据库该怎么配置？、

### ISSUE THREAD

**Issue by wsszh** [thx/RAP#186]
注册和登录都是404，是因为没有配置数据库的问题吗？不知道怎么配置。。

**Comment by wsszh** [comment]
好吧，原来是要改数据库配置，还要用提供的SQL脚本先建数据库。。我还以为能自动建的。。坑了我一天！！！还有SQL脚本有一处错误，tb_rule表中的update_time本来是datetime类型的，却给了他一个"now()"默认值，应该把datetime改成timestamp。

**Comment by Bosn** [comment]
部署手册写了很清楚要如何初始化数据库

也写了很清楚，对MySQL版本的要求，不然在datetime/timestamp类型上，老MySQL会报错。

部署看部署手册
使用看用户手册
开发看开发手册

所有文档整理的都很详细，不看文档自己瞎搞坑几个月也不冤枉。

**Comment by wsszh** [comment]
我也是呵呵了，你自己看看怎么写的，写着用war包不用往下看了，你跟我说写的很详细，哦对，下面是很详细，但我就是要用war包部署，手册还写着推荐，你反过来怪我？还说我瞎搞，你怎么不说你瞎写？坑几个月？谁会被坑几个月？你也太抬举你们的东西了。

**Comment by Bosn** [comment]
亲（*＾3＾）跳过是说不用装IDE和导入工程了。这对war包部署是常识，MYSQL该装还得装。亲如果真的不往下看了，你可以不装MySQL和tomcat的，当然你的问题就不会是MySQL版本不对，而是压根儿没安装了。


该工具就是我个人业余时间维护的开源小工具。欢迎别人随便拿去用，也尽力支持。但是偶不欠谁的。

这位爷慢走，不送😏 您既然这么看不起别人的开源工具何必在这儿浪费彼此时间。

'll
最后，文档已更新： 使用war包部署（推荐）部署方法见issues中的Release帖，较适合只想用RAP不想自己开发定制功能的。（构建项目和导入IDE部分请忽略...IDE也不用装了）
'll

**Comment by wsszh** [comment]
我并不是看不起，我很支持这样的开源项目！但是你回复我的态度确实不怎么样，我是第一次接触war包，完全新手，还要部署在ubuntu服务器上，看到手册就被误导了。。。。另外我mysql和tomcat当然是已经装好了，我就差导入脚本这一步。。。这还是在尝试中解决的。。另外：现在手册更新后的说法就很合理！最后，支持开源，感谢你的分享！

**Comment by Bosn** [comment]
谢谢亲，有问题欢迎随时开issues讨论。
