### ISSUE TITLE
我没有页面，想直接在RAP里测试真实接口的调用，这个能实现吗？

### ISSUE THREAD

**Issue by max0510** [thx/RAP#187]
想测试我自己的真实接口，返回值，格式等是不是正确，直接在RAP里能实现吗？我没有自己的页面或其他的前端手段来测试。

**Comment by Bosn** [comment]
测试真实接口正确性，主要有三个办法：

1. 使用RAP插件，联调时可以在浏览器控制台中输出真实接口的格式错误（如果有），这个在视频教程Mock工具部分里有详细介绍，[视频教程地址](http://thx.github.io/RAP/study.html)
1. 使用Open API，见[Wiki-用户手册](https://github.com/thx/RAP/wiki/user_manual_cn)的API4
1. 通过页面控制台，修改右上角的根路径（默认是RAP MOCK服务），点击"MockJS数据“就会返回真实数据。但是因为受限于跨域策略，需要后端支持JSONP才可以。后续有计划改为后端服务器去代理请求的方式解决该问题。

**Comment by max0510** [comment]
好的，我试试。太感谢了，这东西太好用了！
