### ISSUE TITLE
注册两个相同的用户信息时跳转到的一个页面有些不正常，不知道是不是bug

### ISSUE THREAD

**Issue by max0510** [thx/RAP#188]
页面文字信息大致如下：
用户名:
密码:
确认密码:
Email:
名字:

用户名已存在，或其它错误。（这段描述字体为白色，在白色背景下没有显示出来，我复制的时候才看到的）
我用的是最新版的release。2015-08-13

**Comment by Bosn** [comment]
啊，谢谢亲的反馈。

确实因为整体样式做了重构，部分异常情况可能没有考虑好，先记着BUG，下一个版本中修复。
