### ISSUE TITLE
API4：校验真实数据的正确性 在检查数组数据时检查不完整 

### ISSUE THREAD

**Issue by ucliweiguang** [thx/RAP#189]
我定义的一个接口返回数据定义如下：
Name	   Identifier	Type	             Remark
结果信息	   msg	        string	              required
项目列表	   data              array<object>	
---项目名称	name	string	              required
---项目id	        project_id	number	              required
---项目状态	status|0-1	number	              1
结果状态码	result	number	               required

在测试的时候，如果我的数据如下：
{
    "data":[
    {
        "name":"testname1
    },
    {
        "name":"testname2","project_id":1002,"status":0
    }
    ],"msg":"success","result":1200
}
可返回正确的判断：
参数 obj.data[0].name 缺失
参数 obj.data[0].project_id 缺失

但是，如果我的数据变成如下：
{
    "data":[
    {
        "name":"testname1","project_id":1001,"status":1
    },
    {
        "name":"testname2"
    }
    ],"msg":"success","result":1200
}
则返回：接口结构校验完毕，未发现问题。

我们期待返回的应该是：
参数 obj.data[1].name 缺失
参数 obj.data[1].project_id 缺失

所以，我们判断目前rap接口只判断了数组数据的第一组，而对数据的其他数据没有判断。

请帮忙修复下这个问题。比较紧急，谢谢了。

**Comment by Bosn** [comment]
提交在这里commit 9dcb10f3b97ead5539a11921169a50cb174eb6f6

因为mock数据与真实数据的组数可能不匹配，所以在校验时，若一方为undefined，就改用第一组数据代替。
