### ISSUE TITLE
RAP国际化

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#19]
导入API Blueprint工具到RAP，全面支持Blueprint API规范。所有文档手册、应用提供英语支持。

### 进度
  - [x] 可导入的Blueprint API工具调研
  - [x] RAP数据 => Blueprint API转换器
  - [x] 导入第一个Blueprint API工具 (Aglio)
  - [x] 提供英文RAP (release_en分支)
  - [ ] Blueprint API => RAP数据转换器
  - [ ] 最后将RAP推送到Blueprint API官网实现互通
  - [ ] dredd - 后端自动化测试工具导入
  - [ ] 进一步提升转换器支持程度

**Comment by Bosn** [comment]
规划到2015年度RAP v0.12的版本里

**Comment by wangcash** [comment]
RAP数据 => Blueprint API转换器 实现了吗？

**Comment by Bosn** [comment]
@wangcash HOLD了，亲有这方面的需要？
之前我在[这里](https://github.com/thx/RAP.node/blob/master/lib/blueprintAdapter.js)
做了简单的转换，因为RAP到参数层级，Blueprint API在MOCK这一层主要还是在响应文本上。
并不是很好merge。
