### ISSUE TITLE
如何在做APP开发也能用上这套工具？

### ISSUE THREAD

**Issue by jerry0721** [thx/RAP#192]
如题。好像只看到了web前端的插件方式

**Comment by Bosn** [comment]
亲，app可以直接通过路径访问模拟数据。插件只是为了方便使用控制黑白名单的mock策略，但最终都是从mock接口获取数据的。亲用app的话直接访问mock接口就好，建议仔细看下视频教程mock工具部分就懂啦

**Comment by jerry0721** [comment]
看了，看到有个根路径，是自动设置模拟数据接口返回的，还是手动设置的实际的部署路径？不是很清楚如何做？

**Comment by Bosn** [comment]
视频教程里写了如何使用Mock数据，Wiki里也有详细的用户手册。

根路径那个是从前端获取数据，受跨域限制需要后端支持JSONP才行，使用场景受限制。
