### ISSUE TITLE
请问一下RAP怎么备份？？

### ISSUE THREAD

**Issue by wsszh** [thx/RAP#195]
RT，我想备份一下现在的RAP数据。。

**Comment by Bosn** [comment]
就是数据库备份啊

具体如何备份数据库，需要google下....  如果用mysql，用sqldump之类的

**Comment by wsszh** [comment]
好的，主要是不清楚RAP会不会生成新的文件之类的东西，所以来问问。。

**Comment by Bosn** [comment]
木有啥新文件哈，存储的数据都存在数据库。所以备份也只需要备份数据库就好了。
