### ISSUE TITLE
关于RAP编辑后保存的问题

### ISSUE THREAD

**Issue by wsszh** [thx/RAP#204]
之前编辑后点秒存，能很快的保存，但今天点秒存后还是处于编辑状态，然后再点秒存，就显示“您的请求正在处理，请勿重复点击”，求解答

**Comment by Bosn** [comment]
说明报错了。。。我怀疑还是tb_module.name太小，导致长一点的tab保存失败

**Comment by Bosn** [comment]
你关注下#200
