### ISSUE TITLE
启动没问题，登录就有问题

### ISSUE THREAD

**Issue by bbearb** [thx/RAP#205]
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Cannot open connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Cannot open connection at org.springframework.orm.hibernate3.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:550) at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377) at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:263) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:101) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at $Proxy6.validate(Unknown Source) at 

目测是报的是连接数据库的问题，检查过数据库没问题，初始化数据也导入了，登录就报这个错，最新版的release

**Comment by Bosn** [comment]
看样子还是数据库的问题哦，请检查下数据库配置文件中的用户名和密码是否正确（mysql.local.properties）

部署上，建议使用[war包部署](https://github.com/thx/RAP/issues/180)，更可靠一些。release分支因为我也会定期更新，可以确保是最新的，但也可能疏于严格的测试存在问题。

另外也可以试用线上DEMO版本：[http://cn.rapapi.net](http://cn.rapapi.net)

**Comment by bbearb** [comment]
@Bosn 嗯嗯 貌似是这个问题 这个应该启动就报错的说，现在这个启动的时候不会检查datasource配置，登录的时候才会。

**Comment by Bosn** [comment]
嗯，是这样的，登陆的时候要查询数据库的。
