### ISSUE TITLE
cn.rapapi.net打不开

### ISSUE THREAD

**Issue by wakaryry** [thx/RAP#208]
前天后台整理了API，然后全在rapapi里面，

但是今天上不去。

不会是关闭了吧。

**Comment by Bosn** [comment]
@wakaryry 十分抱歉，刚才在做服务器运维。升级版本。现在已经OK啦。

因为刚刚上线，目前服务器类型比较小... 这两天在购买大一些的服务器，就不会出现服务中断的问题啦。

出现提请及时反馈在issues，紧急问题（如打不开）建议加阿里旺旺群：582755829 ，支持更迅速哦

**Comment by wakaryry** [comment]
@Bosn 谢谢。已经好了。
