### ISSUE TITLE
请问是否有计划支持在请求里加自定义header?

### ISSUE THREAD

**Issue by xujinzheng** [thx/RAP#209]

**Comment by Bosn** [comment]
自定义header类似的信息写在接口备注里就可以了

**Comment by xujinzheng** [comment]
请求的时候会把这些Header的内容发过去吗，比如不同的API是通过自定义Header作为标识的
X-API: xx.user.get

服务器端根据这个Header来获取用户请求什么API，那么mock的时候能从备注里识别？

**Comment by Bosn** [comment]
该需求有些小众，暂时不考虑支持。rap是来源的，亲可以尝试自行实现。

**Comment by xujinzheng** [comment]
嗯，不过这个需求并不小众，很多APP设计是有需要Header的支持的，比如session ticket (JWT), 以及其他的API设计方案 https://devcenter.heroku.com/articles/platform-api-reference

**Comment by Bosn** [comment]
感谢亲的反馈、建议和意见。
因近期需求较多，该需求会在未来的版本中去考虑实现。

亲也可以通过RAP Open API提供得接口，或修改RAP的源代码自行实现。
