### ISSUE TITLE
从后台服务器接口获取真实数据

### ISSUE THREAD

**Issue by vistamin** [thx/RAP#217]
能否增加这样的功能：
1. 直接在RAP上提交http请求到真实的接口获取数据，并且判断返回的数据格式是否符合接口文档所定义的格式？类似于这样的站点： http://www.atool.org/httptest.php
2. 这个http请求的发送，能否自动化。这样可以马上发现后台服务器接口和接口文档定义不一致的问题。

**Comment by Bosn** [comment]
该需求已经在后续版本的规划当中。

目前有个麻烦问题，发出来也请给些参考：

1. 从RAP直接提交数据，针对大都实际场景，会存在跨域问题。
2. 登陆/session/cookie的问题

**Comment by vistamin** [comment]
@Bosn 跨域的问题，可以考虑使用nginx代理来解决，这个RAP目前已经在使用nginx了。

**Comment by Bosn** [comment]
@vistamin 好的，我研究一下。谢谢亲的反馈。

**Comment by Bosn** [comment]
查了下，v0.12版本规划里已经有这个需求了，见自动测试升级  部分https://github.com/thx/RAP/issues/105
