### ISSUE TITLE
http://domain.com/1111/xxx  URL二级纯数字时，mock接口找不到。

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#219]
http://domain.com/1111/xxx  URL二级纯数字时，mock接口找不到。

**Comment by vistamin** [comment]
RAP接口文档中，当请求地址是http://domain.com/xxx/yyy/zzz/mmm时，xxx, yyy, zzz或者mmm换成是数字开头，都会提示找不到接口。当以字母，下划线或者$开头时，都正常。

**Comment by Bosn** [comment]
搞定了，是遍历action list时，未对http://这种开头做处理，匹配时触发了RESTFul对于/:id/这类URL的模糊匹配算法，导致错误。

已修复。

**Comment by vistamin** [comment]
@Bosn  好的，多谢。

**Comment by Bosn** [comment]
@vistamin 还没发布正式release啊，我觉得下周差不多了。
最近两周老出差，项目比较多，有点耽搁了。

具体release发布请关注issues，也可以把邮箱发送给我bosn@outlook.com 有新release，我会在邮件组里通知大家哟。
