### ISSUE TITLE
根据条件切换数据接口,在rap上怎么写

### ISSUE THREAD

**Issue by SAWSAWSAW** [thx/RAP#225]
大家在使用rap的时候有没有遇到过这种场景，比如有个列表，列表中的其中一部分数据的接口不是固定的那些，而是根据某个条件指定特定的数据接口的，这种在rap上怎么写？？ 如下图

![mme9c0lnjwpxl kxyni 37](https://cloud.githubusercontent.com/assets/5058953/10935335/7f936fa2-8320-11e5-8c37-36c203580f7e.jpg)

**Comment by Bosn** [comment]
这种情况在rap里就是多个接口，有几种情况拆分成几个接口。rap中一个接口代表着一种接口的结构。


mock的时候可以根据参数确定返回哪个接口的mock数据，具体看下用户手册，关键字：根据参数返回

**Comment by SAWSAWSAW** [comment]
因为有一种情况就是比如我们有一个列表来存页面相关的数据，前端根据数据来套逻辑模板。
这个列表里面可能会有头部，会有尾部，会有页面内容。这些模块所需要的数据结构明显是不一致的…  所以会出现我上面的那个需求。

**Comment by Bosn** [comment]
我已经回答了。。。还有疑问欢迎继续回复。
