### ISSUE TITLE
不能登陆

### ISSUE THREAD

**Issue by Kahn42** [thx/RAP#228]
Chrome控制台提示找不到这个http://localhost:8080/stat/js/core/jquery-2.1.0.min.js?_r=20150917.v0.11.3.dev

**Comment by Bosn** [comment]
轻轻缓存？ 其它静态资源都能拿到么

**Comment by Kahn42** [comment]
原来是我输错密码了。。。。但是好像没有提示，只是会跳转到这个页面http://cn.rapapi.net/account/doLogin.do，并且这个页面确实Failed to load resource: the server responded with a status of 404 (Not Found) http://cn.rapapi.net/stat/js/core/jquery-2.1.0.min.js?_r=20150917.v0.11.3.dev

**Comment by Bosn** [comment]
好的我检查下啊

**Comment by Bosn** [comment]
已确认，确实加载了不存在的JS，但是不影响任何功能。

**Comment by Bosn** [comment]
另外错误没有给出提示，该问题在下个补丁中修复，谢谢。

**Comment by Bosn** [comment]
已修复，更新在release分支。使用war包部署的，下一版本会生效。
