### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by zhaoqin102** [thx/RAP#229]
签出分支后找不到下面两个类
import com.alibaba.buc.sso.client.util.SimpleUserUtil;
import com.alibaba.platform.buc.sso.common.dto.SimpleSSOUser;

**Comment by Bosn** [comment]
看部署手册，不要自己瞎弄啊。release分支

**Comment by zhaoqin102** [comment]
是release分支，只有那个找不到


通过 Android 版 Outlook 发送





On Sun, Nov 8, 2015 at 1:07 AM -0800, "Bosn" <notifications@github.com> wrote:
看部署手册，不要自己瞎弄啊。release分支

---

**Comment by Bosn** [comment]
release分支没这两个东西，
