### ISSUE TITLE
release问题/.gitignore优化

### ISSUE THREAD

**Issue by ywooer** [thx/RAP#231]
大神可不可以重构一下项目，项目太大了，clone不方便。最好是改成maven项目，然后把master下面的release包删除掉。呃，还有能否把IDE生成的文件加到gitignore？
万分感谢啊！

**Comment by Bosn** [comment]
v0.11.6会引入maven，release war的问题我会想想怎么搞。可以考虑放rapapi.net站点里。

**Comment by Bosn** [comment]
引入Maven对底层变化较大，放在v0.13.0

下一个版本v0.12.0将会完善release问题及gitignore问题。Issue拆分。

**Comment by Bosn** [comment]
已完成

**Comment by ywooer** [comment]
感谢作者的无私奉献！赞一个！
