### ISSUE TITLE
是否可以引入评论系统

### ISSUE THREAD

**Issue by jokefaker** [thx/RAP#232]

**Comment by Bosn** [comment]
聊天灌水两不误么。。。。是个不错的需求，增加活跃度。
下个版本我会考虑下在接口下面增加可隐藏的评论区。

**Comment by jokefaker** [comment]
哈哈，这样就可以在白天讨论下晚上谁捡肥皂了=。=

其实主要考虑接口文档有些时候需要前后端一起沟通的.

**Comment by Bosn** [comment]
前后端沟通接口用评论区？

别逗了。。。。

还是当面聊，或者电话，或者IM吧......


RAP就是专注用来写接口的。。。。

**Comment by jokefaker** [comment]
好像也是，很多时候当面都说不清楚....别说评论区了....

**Comment by Bosn** [comment]
嗯，对对对，关闭。拜拜。有想法再提。
