### ISSUE TITLE
接口请求参数列表中，名称为"seed"的变量名，在请求时如果输入参数过长会报错

### ISSUE THREAD

**Issue by Peter-WF** [thx/RAP#233]
### 测试用例 
* 接口请求参数列表
![image](https://cloud.githubusercontent.com/assets/13869200/11207587/030996b0-8d51-11e5-922c-49ea2ca58b02.png)

* data： {seed:"5636cb273c713"}
![image](https://cloud.githubusercontent.com/assets/13869200/11207451/385b2dd4-8d50-11e5-87ef-634faac87be2.png)
![image](https://cloud.githubusercontent.com/assets/13869200/11207477/62c89bf6-8d50-11e5-9db1-6112707ce70f.png)

**Comment by Bosn** [comment]
已修复...  ActionBase.java中存在无效setSeed()方法导致。
下个版本生效。
