### ISSUE TITLE
保存时会提交整个工程的数据

### ISSUE THREAD

**Issue by skyuning** [thx/RAP#235]
保存时，不是对当前创建或修改的接口进行保存，而是将整个工程的数据都提交保存一遍是吗
如果项目大了接口多了每次保存都会提交大量数据，这块儿以后会优化吗

**Comment by Bosn** [comment]
会优化，但是成本大，必要性小，优先级不高。

不建议一个RAP项目放太多的接口，大型项目适当做拆分，通过项目路由功能在项目之间可以共享数据。
