### ISSUE TITLE
js在ubuntu环境下乱码。

### ISSUE THREAD

**Issue by mfkwfc** [thx/RAP#236]
版本：RAP v0.11.5
环境： ubuntu 12 , jdk1.8  jetty
发现
org/home/index.js
org/productline/index.js
等有汉字的JS文件乱码。
 建议在过滤器强制设置一下编码

response.setCharacterEncoding("UTF-8");

**Comment by mfkwfc** [comment]
我是导入eclipse下产生的。你们打好的WAR包不存在此问题。

**Comment by Bosn** [comment]
eclipse要设置下文件编码为UTF8，这个要看你IDE自己的默认设置了。

**Comment by abincai** [comment]
centos 也出现乱码 war解压出来的文件
