### ISSUE TITLE
后端接口检验的需求

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#239]
还需求提出的同学较多，需解决跨域问题从Java端进行请求并对比数据，检验正确性。后续考虑引入CASE管理实现自动化测试，本期0.12可先实现简单的系列CASE测试。

**Comment by charmingzuo** [comment]
期待

**Comment by Bosn** [comment]
已解决，下个release中，pageTester将会从RAP Server端请求，解决跨域要求JSONP的问题。
另外增加了权限验证，必须有page权限的用户才可进入页面的控制台。
