### ISSUE TITLE
编辑文档的互斥锁 & 性能优化

### ISSUE THREAD

**Issue by xddhaibo** [thx/RAP#240]
互斥锁能改成以模块为单位么。

**Comment by Bosn** [comment]
改动很大，倒是有方面计划。
项目接口太多建议拆分项目，通过项目路由共享数据。一个业务项目可以拆成多个rap项目。

**Comment by Bosn** [comment]
该需求会考虑在0.13版本实现，因为改动比较大，所以开发时间会长。但是考虑到性能问题和快速的数据增长，又必须得做。

所以该项目作为一个现版本的下一个版本并行计划&开发着。
