### ISSUE TITLE
增加页面级别的排序功能

### ISSUE THREAD

**Issue by yinyu00** [thx/RAP#241]
有些页面需要调整优先级， 但是现在的规则是按照添加的顺序排序的， 能否做成可以手动调整页面顺序， 或者通过命名规则来排序页面。 

例如有如下页面
page1
page2
pagexx
默认按照名称排序， 如果我想让pagexx拍到最前面的话， 我可以在pagexx前面加0_pagexx, 其它页面修改为 1_page1, 1_page2

**Comment by HelloYu** [comment]
这是view层的事，估计没有那个精力去做他们，有源代码，自己动手吧。

**Comment by Bosn** [comment]
没问题的，下个版本加哈。感兴趣的同学可以自己尝试下，需要修改rap.js哦

**Comment by Bosn** [comment]
Tab、页面、接口都按照name排序了，下个release生效。
