### ISSUE TITLE
rap_cn_v0.11.5.sp1.war  OnlineDocs 发生错误

### ISSUE THREAD

**Issue by fengyunhe** [thx/RAP#242]
但是在编辑页面是可以编辑并且保存的，说明数据库连接是没有问题的。

页面返回500错误：
----

HTTP Status 500 - Connection refused: connect

type Exception report

message Connection refused: connect

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.net.ConnectException: Connection refused: connect
	java.net.DualStackPlainSocketImpl.connect0(Native Method)
	java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	java.net.Socket.connect(Socket.java:589)
	java.net.Socket.connect(Socket.java:538)
	java.net.Socket.<init>(Socket.java:434)
	java.net.Socket.<init>(Socket.java:286)
	org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	org.tuckey.web.filters.urlrewrite.RequestProxy.execute(RequestProxy.java:135)
	org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:277)
	org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
	org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	com.taobao.rigel.rap.common.AuthCheckFilter.doFilter(AuthCheckFilter.java:74)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:236)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.23 logs.

**Comment by Bosn** [comment]
这个功能没做完，需要起node服务的。注释了才对。。。用导出就好了，在线看其实文档编辑的地方就很适合在线看，还提供全级别搜索。

**Comment by fengyunhe** [comment]
袄~ 还有一个问题，就是字段类型，number 没有区分是 integer 还是long、float、double

**Comment by Bosn** [comment]
目前RAP支持的接口以http JSON形式的接口为主，JSON没有short的区分。

你如果是java 和java 的接口直接注释就好了没必要用rap
