### ISSUE TITLE
 希望RAP提供数据导入导出功能

### ISSUE THREAD

**Issue by ccidcce32167** [thx/RAP#243]
想请问下rapapi.net是否对外开放的？里面的数据会被清档吗？

**Comment by Bosn** [comment]
对外开放，不会清而且定期备份的亲。

**Comment by ccidcce32167** [comment]
Good,还有一个问题，我们之前在自己平台上部署了rap并且已经累积了一定量的接口数据，但是我们的平台十分不稳定，我想把数据迁移到rapapi.net方便团队管理接口，我已经注册了账号了，但不知道如何进行数据的导出和导入？

**Comment by Bosn** [comment]
@ccidcce32167 天啦撸，这个功能我还木有做呢。。。。
以前都是单点部署内网使用，现在确实有这种需求。我考虑在新版本增加下数据导入导出功能吧。

**Comment by ccidcce32167** [comment]
强烈支持～加油～

**Comment by seasun** [comment]
这个需求强烈需要啊，手动TT
