### ISSUE TITLE
创建团队点击［确认创建］无反应

### ISSUE THREAD

**Issue by JihanChen** [thx/RAP#244]
hi：分支release ，主页上方进行创建团队，输好信息之后点击［确认创建］按钮无反应，不能正确创建,
该问题有时候不行，有时候可以（应该是我不选择团队成员就可以成功创建），但是即使创建成功跳转到创建产品线时候输入之后点击［确定］无反应。另外 创建项目 时候无法选择项目归属的团队信息（下拉框无法显示团队, 麻烦大神看下该问题

**Comment by Bosn** [comment]
你新部的还是升级的啊，从老的升级数据库有更新的，看下DATABASE_CHANGE文件。

**Comment by JihanChen** [comment]
我是升级的，中间比对了新的数据库更改，更新了表结构，无反应是不是前端事件就没有触发

**Comment by Bosn** [comment]
https://github.com/thx/RAP/blob/master/DATABASE_CHANGE.md

看看你以前是什么版本，把对应版本的数据库升级脚本执行了才行。

还有问题加下旺旺群吧，群号码在RAP下方就有。

**Comment by JihanChen** [comment]
嗯 有一个sql 没有更新成功 之前没有注意到，很感谢耐心解答，该问题已经解决
