### ISSUE TITLE
关于备注的问题。。

### ISSUE THREAD

**Issue by wsszh** [thx/RAP#252]
写备注的时候不能换行吗？？如果可以该怎样换行？？

**Comment by Bosn** [comment]
下个版本加。

**Comment by Bosn** [comment]
考虑了下，备注不打算支持换行.... 因为回车就表示该字段编辑结束了。增加换行对原有功能修改很大。

**Comment by Bosn** [comment]
另外，RAP的主要目的，是编辑接口。

RAP并不是Wiki文档，想要复杂的文档编辑功能，请使用Wiki.....而RAP中的备注，要尽可能的简单清晰。
