### ISSUE TITLE
新建一个模块并秒存后，会出现两个模块

### ISSUE THREAD

**Issue by interchen** [thx/RAP#257]
新建一个模块并秒存后，会该项目的第一个模块，此时再点击其它模块时，页面上会同时展示两个模块
如下图，出现公共和动态两个模块
一个是第一个模块，一个是当前刚编辑完并秒存的模块

![image](https://cloud.githubusercontent.com/assets/2597576/11685228/78707b54-9eb2-11e5-9894-06f26fcc4bdf.png)

**Comment by Bosn** [comment]
这个我其实也遇到过，几率性复现，这个BUG我会尝试复现并修复下。

**Comment by interchen** [comment]
@Bosn 已经复现，按我描述去操作，100%可以复现

**Comment by Bosn** [comment]
@interchen 好的，非常感谢。该问题计划在最近一个release内修复。

**Comment by interchen** [comment]
昨天在提issue时还不知道复现的规律，写着写着，忽然发现好像是新建了一个模块之后就会出现，尝试了一下，果然。。。。。。

**Comment by Bosn** [comment]
该问题主要由于新创建的module，id是临时的。服务器返回创建后的真实实体ID后，在恢复之前阅读位置时没有正确处理。

修改后，在阅读位置为真实ID时恢复，对新增加tab暂时不做恢复。
