### ISSUE TITLE
编辑参数时，添加和删除按钮位置错位

### ISSUE THREAD

**Issue by afeidonler** [thx/RAP#262]
编辑参数时，添加和删除按钮位置错位，无法点击到

**Comment by Bosn** [comment]
给截图，给例子。

**Comment by Bosn** [comment]
好吧，已经复现了，昨天更新的版本的BUG。该BUG确实很严重，现在已经紧急处理了。
会尽快解决。

```json
{
    "asdfasdf": 1,
    "xxxx": [
        {
            "33": 1,
            "333": 1,
            "xxx": 1,
            "xxxx": 1
        }
    ],
    "test": 80433,
    "asdsxx": 1,
    "asdf": 1
}
```

**Comment by Bosn** [comment]
考虑到该问题较为严重，rapapi.net先回滚到上一个版本。

**Comment by Bosn** [comment]
已经回滚完成了，先用着。
该问题修复后，我再重新上线。

**Comment by afeidonler** [comment]
下午没有注意，发现版本回滚了才想起来看。已发现解决方案：.div-op-container使用绝对定位，但其父级没有定义position,我的方法.td-param op添加position:relative

**Comment by Bosn** [comment]
嗯，因为新的0.12为了解决一些问题去掉了父级的pos，已经通过去掉绝对定位解决。晚上发布新版。
