### ISSUE TITLE
偶发数据获取出错

### ISSUE THREAD

**Issue by zeyongTsai** [thx/RAP#271]
一个页面下，多个接口都是好的，只有某一个接口不行；在RAP里面mock数据没问题，单独打开链接也没问题；放到项目里面ajax就返回“RAP出错啦！当你不幸走入该页面时，说明系统出现了不可处理的错误，...，谢谢哟。 T.T”

版本0.11.4

**Comment by Bosn** [comment]
方便贴一下这个接口的截图么？敏感信息（如备注）可以马赛克，主要要变量名、类型和结构。

**Comment by Bosn** [comment]
如果是rapapi.net上面的，贴一下文档的链接和对应的接口ID即可。

**Comment by zeyongTsai** [comment]
![image](https://cloud.githubusercontent.com/assets/8591261/11776520/b502e916-a282-11e5-9371-8bb522622716.png)
method:POST, action: /userInfo?
额，我今天来试，怎么都无法重现BUG； - -

BUG当天，一开始是这个接口在RAP里面mock的时候，只显示加载中，等很久都没响应；跑到浏览器里面直接返回“RAP出错啦！当你不幸走入该页面时....”；

我怀疑服务器出问题，跑去重启并没用；然后又新建一个接口一个字段一个字段的加，大概加到3-4个就不行了，我怀疑是特定字段名称问题？改了又改没发现规律，期间有时候会提示session异常请联系管理员；

大概过了1个多小时，接口可以用了，rap后台mock有响应，直接新开窗口打开该接口也可以；但就是用在项目里面的ajax没用，依然是上面的那个错误；

最后我就到群里留言了，顺便提个issue，现在没法重现，我就关了吧！D2的时候听听高级用法！:D
