### ISSUE TITLE
谁在使用RAP？快点来补充~~~

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#272]
感谢各位亲们选择和信任RAP，为了让RAP更好的服务大家，也为了RAP更好的宣传。
希望各位部署RAP的同学，将贵公司告知于我。

例子：

公司名称：阿里巴巴
LOGO地址：http://xxxxxxxx

后续我们会加入到RAP主页的“谁在使用RAP”的部分。

**Comment by zsinba** [comment]
公司名称：苏州白鸽云信息技术有限公司
平台地址：http://api.un-bug.com
LOGO地址：http://www.un-bug.com/Images/daaosi/logo.png

**Comment by interchen** [comment]
公司名称：厦门优优汇联信息科技有限公司
LOGO：http://www.uulian.com.cn/images/logo1.png
同时感谢RAP团队提供这么优秀的开源系统，感谢！

**Comment by jokefaker** [comment]
公司名称：杭州匠人网络科技有线公司
LOGO:http://91souban.com/images/logo.jpg
RAP非常不错，希望可以支持改进完善下去！

**Comment by liangjinx** [comment]
深圳润民科技有限公司
logo:www.bajiewg.com
rap我还没有开始使用，不过代码已经看了，功能很好。

**Comment by 327** [comment]
公司名称：南京爱动信息技术有限公司
logo：http://7u2opd.com2.z0.glb.qiniucdn.com/logocangao983249_1445508611697_46.jpg
希望rapapi.net能更加稳定，现在注册报错都比较多

**Comment by Bosn** [comment]
@327 已经更新到阿里云主机了，速度应该会快一个层次。。。稳定性也通过性能优化解决了哦。有问题随时issues提交问题哦亲。

**Comment by xie-zhichao** [comment]
公司名称：智能云科信息科技有限公司
LOGO：https://www.isesol.com/img/sesol_logo.png
我们使用RAP已经半年了，非常合适的Web接口管理工具。

**Comment by ymsheng** [comment]
公司名称：Boss直聘
LOGO：http://img.wdjimg.com/mms/icon/v1/a/63/6a7982125b632afa9914c277107c863a_256_256.png
非常棒的工具，很喜欢

**Comment by Oceanz** [comment]
公司名称：上海锦商网络科技有限公司
平台地址：http://www.baosaas.com
LOGO：http://www.baosaas.com/jsweb/web/jsweb/images/logo_pic.jpg
RAP非常棒，已经用于多个项目，非常感谢阿里妈妈MUX团队，提供了这么优秀的开源系统。

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by ckokdke11111** [comment]
大神可以教教怎么部署RAP项目到MYECLIPSE上吗？

**Comment by Bosn** [comment]
@ckokdke11111 该吃药了你

**Comment by ckokdke11111** [comment]
这是电脑卡了，才不小心按到那么多的

**Comment by ckokdke11111** [comment]
@Bosn可以教教我吗？

**Comment by belerweb** [comment]
公司名称：重庆智数信息科技有限公司
平台地址：https://rap.idataitech.com
LOGO地址：https://sso.idataitech.com/assets/img/login/logo.jpg

**Comment by borisding1994** [comment]
华兴资本逐鹿X

**Comment by Asa-Fany** [comment]
公司名称：北京停简单信息技术有限公司
LOGO地址：http://images.tingjiandan.com/resource/logo/logo-title-03.png
不错的工具，但是在写开放平台文档的时候，不太好用，因为每个接口的公共参数部分需要重复写。希望能对公共参数部分进行拆分。

**Comment by codyyeachann** [comment]
公司名称：阔地教育科技有限公司
LOGO地址：http://www.codyy.com/public/img/common/logo_w.png
初步开始内部推广使用，希望可以增加错误码定义功能。

**Comment by Yuntianhe2016** [comment]
上海高顿教育

**Comment by shengbox** [comment]
公司名称：金柚网
LOGO：http://staticweb.joyowo.com/modules/website/images/index/4.0.0/logo.png
非常好，特别是在创业型的公司即利用保证文档质量又可以节省不少时间。

**Comment by zhengsk** [comment]
公司名称：厦门节点科技集团有限公司
LOGO地址：[http://www.xmnode.com/template/node/img/logo.jpg](http://www.xmnode.com/template/node/img/logo.jpg)
谢谢，很方便。

**Comment by husu** [comment]
公司名称：重庆秒差距科技有限公司
LOGO地址：https://avatars2.githubusercontent.com/u/8263559?v=3&u=62cd4e84917b3e7258846bf7f57dda31330412a9&s=140

**Comment by michealzh** [comment]
公司名称：美丽说(北京)网络科技有限公司
LOGO地址：http://s16.mogucdn.com/new1/v1/bmisc/5db023a8f434d62f2db85bb9fb8c26d0/182326981374.png

**Comment by JiangLongLiu** [comment]
公司名称: 西安诠释软件有限公司
LOGO地址: http://wiseq.cn/images/logo-new.png

**Comment by xiaochunping** [comment]
公司名称: 湖南理才网科技发展有限公司
LOGO地址: http://about.dayhr.com/skins/dayhr/images/logo.png

**Comment by anymijun** [comment]
公司名称：蓝月亮（中国）有限公司
LOGO地址：http://www.bluemoon.com.cn/images/our%20coporation/our-corporation_01_01.jpg
非常好的API管理工具，希望继续完善功能

**Comment by mosaic101** [comment]
公司名称：上海店达信息有限公司
LOGO地址：http://www.dd528.com/mall/images/login/login_03.png
试过其他api管理工具，对比之下还是觉得rap更好用，希望继续完善

**Comment by cuidingfeng** [comment]
公司名称：优信二手车
LOGO地址：http://s.xinstatic.com/www/img/home_logo.png
全站已使用4个月，感谢RAP给我们带来的便捷。

**Comment by MinionsDave** [comment]
公司名称：杭州依萨卡信息科技有限公司
LOGO地址: http://isa.qa/wp-content/uploads/2014/01/logo-site2.png
所有项目组都在使用，感谢RAP给我们带来的便捷。

**Comment by oyy670085244** [comment]
公司名称：深圳嗨购科技有限公司
LOGO地址：http://res.guesslive.com/haigou/logo/haigou_logo.jpg
公司所有接口项目都在使用API管理

**Comment by cielqian** [comment]
公司名称：无锡雅索软件技术服务有限公司
LOGO地址：http://www.useeinfo.com/img/ColorLogo.png

**Comment by AabbyAngel** [comment]
公司名称：恒生电子股份有限公司
LOGO地址：http://www.hundsun.com

**Comment by q474818917** [comment]
公司名称：且康电子商务有限公司
LOGO地址：http://www.360guanai.com

**Comment by BigbigY** [comment]
公司名称：瑞钱宝
LOGO地址：http://www.rqbao.com

**Comment by wenshan** [comment]
公司名称：北京购阿购-开放数据服务平台
平台地址：http://www.gooagoo.com
LOGO地址：http://www.gooagoo.com/img/logo.png

谢谢提供这么好的数据MOCK的系统。

**Comment by jiangqqlmj** [comment]
公司名称：南通嘎嘎软件科技有限公司
LOGO：http://vvzmtstorage.gagakj.com/GAG-02.png
同时感谢RAP团队提供这么优秀的开源系统，感谢！

**Comment by Darcy-Qin** [comment]
公司名称：四川掌麦科技有限公司
LOGO：https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1502361384521&di=fbcd6f61646849327ffd89c0712423ec&imgtype=0&src=http%3A%2F%2Fimg6.58.com%2Fimages%2Fyellow%2F5858126468125343490%2Fbig%2Fn_s12467895000697336065.jpg
好期待RAP1.0版本，现在缺少了数据格式检查，错误的mock数据容易导致服务停止。

**Comment by tenlee2012** [comment]
公司名称：小佩网络科技有限公司
平台地址：http://www.petkit.com
LOGO：http://www.petkit.com/images/cn/logo.png
同时感谢RAP团队提供这么优秀的开源系统，感谢！
希望能够完善消息模块，修改API后，参与项目的人都能收到通知就好了

**Comment by lovewanwan** [comment]
公司名称：硅谷厚朴（北京）金融信息服务有限公司
平台地址：https://www.puhuilicai.com/
同时感谢RAP团队提供这么优秀的开源系统，感谢！
现在缺少了数据格式检查，错误的mock数据容易导致服务停止。

**Comment by haotogo** [comment]
公司名称：杭州恒奕网络有限公司
LOGO地址：http://www.hengynet.com

**Comment by DoFunCloud** [comment]
公司名称：深圳驾控科技有限公司（兜风出行）
LOGO：https://avatars3.githubusercontent.com/u/30190039

同时感谢RAP团队提供这么优秀的开源系统，感谢！

**Comment by tonyfree** [comment]
公司名称： 珠海市旗云科技有限公司
公司地址： https://www.qi-cloud.com/
LOGO： https://www.qi-cloud.com/static/favicon.ico

同时感谢RAP团队提供这么优秀的开源系统，感谢！

**Comment by ChunPIG** [comment]
公司名称：广州大气候农业科技有限公司
平台地址：http://rap.airag.cn
LOGO地址：http://www.airag.cn

**Comment by zerochl** [comment]
公司名称：上海兽耳科技网络有限公司
LOGO地址：https://www.mimikko.cn/favicon.ico
非常感谢RAP团队提供这么优秀的开源系统，感谢！

**Comment by lm3515** [comment]
公司名称：印记（深圳）网络技术有限公司
公司地址： http://www.yinjiyun.cn
LOGO地址：http://www.yinjiyun.cn/img/logo.png

**Comment by bjpo** [comment]
公司名称：黑龙江正世科技有限公司
LOGO地址：http://www.hljzskj.com/images/zsindex_09.jpg
感谢RAP团队提供优秀的开源工具！

**Comment by qgm168** [comment]
公司名称：易智付科技（北京）有限公司
公司地址： http://www.beijing.com.cn
LOGO地址：https://static.5upay.com/repo/www/common/images/big-logo_b527260.png

**Comment by shangyangzi** [comment]
公司名称：广州骏伯网络科技有限公司
公司地址：http://www.gzjunbo.net
LOGO地址：http://www.gzjunbo.net/assets/images/logo.png
