### ISSUE TITLE
/mockjsdata/安全升级

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#275]
因为mockjsdata接口，将在后端运行js，当mock规则中包含自定义函数时，如果用户提交死循环或危险函数会导致服务器遭受危险。

因此需要修改/mockjsdata/，从后端生成mock数据时，过滤自定义函数。
这并不影响大部分使用RAP插件，或调用/mockjs/接口的用户。

**Comment by afeidonler** [comment]
mockjs接口返回的数据仍然有mock的规则，无法直接使用。请问app中如何可以使用生成好的数据

**Comment by Bosn** [comment]
@afeidonler 如果是用RAP插件（目前只支持jQuery/KISSY），插件会处理好这些细节。

如果想直接调用最终结果，/mockjsdata/已经恢复使用了，只是因为安全/性能原因暂时禁止了自定义函数。自定义函数会被过滤为1。

这部分我会调研解决后，再恢复自定义函数。但是除了自定义函数其它mock规则都是支持的。

**Comment by afeidonler** [comment]
@Bosn 多谢

**Comment by Bosn** [comment]
DIRTY着解决了，但是仍然有问题。
需要解决mockjs自定义函数运行超时、死循环等问题。

**Comment by Bosn** [comment]
### 解决方案
1. 引入缓存，/mockjsdata/特别消耗资源，强制缓存。
2. 超时强杀策略，超过2秒跑不出来放弃，保证整体服务器的稳定性。
3. 既能支持function，又要防止越权。这块儿需要调研下看看如何解决。

**Comment by huqingliang** [comment]
提示跨域错误怎么办？
Fetch API cannot load http://rap.alibaba-inc.com/mockjsdata/530/itemformto/listFlowFromTo.json?da…e=recent1&device=1&itemId=522892796310&sycmToken=b32234b2a&_=1453088255272. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://sudo.bda.sycm.taobao.com' is therefore not allowed access.

**Comment by Bosn** [comment]
@huqingliang KISSY/jQuery的话，使用RAP插件，会自动将Ajax请求的类型转换为JSONP。
如果不用插件，自己处理的话需要修改为JSONP的接口请求方式。

**Comment by huqingliang** [comment]
谢谢！改成jsonp好了，一开始用cors方案是不行的
