### ISSUE TITLE
上传的接口没了，莫名变成很多重复的字段

### ISSUE THREAD

**Issue by zsinba** [thx/RAP#279]

**Comment by zsinba** [comment]
![1](https://cloud.githubusercontent.com/assets/890157/11833268/009b4d94-a3fc-11e5-9ccb-8a054557ac99.png)

**Comment by zsinba** [comment]
![1](https://cloud.githubusercontent.com/assets/890157/11833295/2c807790-a3fc-11e5-9f1c-e0cff6a8ac21.jpg)

**Comment by Bosn** [comment]
上传接口是啥？RAP没有上传接口的功能。

你是说导入JSON么？

导入JSON是往里添加新的字段，并不会删除老的。重复导入JSON就会导致图片中的情况。

你是怎么操作的没有说清楚，我也只是猜测。

**Comment by zsinba** [comment]
因为不是我在上传接口，所以具体操作不清楚。
这是表现。我只是平台建起来。现在升级0.12版本试试看

**Comment by Bosn** [comment]
那是谁上传的啊，谁提的问题找谁描述清楚。

RAP没有上传接口的功能.........

**Comment by huanggm** [comment]
我也遇到了同样的问题，很崩溃
