### ISSUE TITLE
多出来的接口，不知道哪来的

### ISSUE THREAD

**Issue by zsinba** [thx/RAP#280]
![image](https://cloud.githubusercontent.com/assets/890157/11833676/1acd0b0e-a400-11e5-9498-58378afc0ffb.png)

**Comment by zsinba** [comment]
![1](https://cloud.githubusercontent.com/assets/890157/11833683/3290a4c6-a400-11e5-8d41-6f6ccad1492a.png)

**Comment by zsinba** [comment]
应该是前台的问题，不是后台存储的问题。
猜测是保存的时候，未做数据过滤，导致相同的数据多次入库，
或者可以添加一个，根据接口URL和接口参数及结果列表HASH一个ID出来，根据ID判断，防止相同数据入库

**Comment by Bosn** [comment]
好奇怪，有稳定复现的办法么？

因为目前我在自测、线上rapapi.net环境里，都没有复现这个问题。（不然早就发现并修复了）

应该是特定环境下的问题。

**Comment by zsinba** [comment]
再出现我让同事告诉我复现办法
