### ISSUE TITLE
权限控制有问题

### ISSUE THREAD

**Issue by chushiyun2015** [thx/RAP#283]
我创建了一个项目 添加了项目成员 权限为“普通权限”，但是 他们登录后却可以修改我的项目信息和 接口信息

**Comment by Bosn** [comment]
只要是项目成员，就有项目的读写能力。

如果只读，不让写，就不要添加为项目成员。
只要让他和你在同一个团队就可以了。即添加为团队成员。

**Comment by chushiyun2015** [comment]
明白了 现在可以了 谢谢。另外一点个人感觉：就是项目成员查看项目的入口有点深，需要通过“团队”一级一级走下去

**Comment by Bosn** [comment]
如果是项目成员或创建者在我的主页里就有啊
