### ISSUE TITLE
多个接口对应同一个模板数据bug

### ISSUE THREAD

**Issue by tracyhyq** [thx/RAP#284]
现在有这样一个场景
我这边有两个接口， /index-type-1和/index-type-2  两个接口，对应的数据结构是不同的，同时指向同一个模板，导致模拟出来的数据始终只有一个接口的

**Comment by Bosn** [comment]
模拟数据是按照路径来匹配的。

你两个接口的请求链接写的是什么？

同时指向同一个模板是什么？RAP里没有模板的处理。

**Comment by Bosn** [comment]
给一些截图，把你的问题描述清楚，这样才能得到有效的解答。

**Comment by tracyhyq** [comment]
![image](https://cloud.githubusercontent.com/assets/2010271/11888547/a39f5890-a579-11e5-99ac-83fb9800041c.png)
![a2c9cd66-418b-46b0-8296-a413a6fbaf08](https://cloud.githubusercontent.com/assets/2010271/11888579/ee267dda-a579-11e5-8759-7ad1abbc91ad.png)
如图所示，两个接口，对应同一个模板文件，这样就会出错，我访问第二个接口是，模拟出来的数据始终是第一个接口的数据

**Comment by Bosn** [comment]
模板文件，是你自己应用内部的逻辑。

RAP需要保证的，是当你请求RAP的请求正确时，返回正确的数据。
你检查下网络面板里面得网络请求情况，是不是你自己应用请求的链接就是有问题得。

http://rapapi.net/tester/pageTester.do?id=1444

我做了你截图的测试CASE，能够正确返回，没有发现问题。

另外，附一下你的RAP的版本，是不是比较老得版本的BUG也说不定。
