### ISSUE TITLE
docker镜像调研 & rapapi.net 迁移到阿里云

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#285]
### 目标
* 制作Docker镜像，部署更方便
* rapapi.net从GoDaddy迁移到阿里云，大幅提升访问速度

**Comment by belber** [comment]
现在页面响应速度的确是慢到无法忍受了。楼主加油！！

**Comment by Bosn** [comment]
@belber I'm so sorry. rapapi.net刚刚开放，在运维上经验确实不足。
我也发现了CPU飙升的问题，短期先通过升级服务器解决，后续我会尽快迁移到阿里云服务器。

**Comment by Bosn** [comment]
### 进度UPDATE

公司已提供了服务器，但是要求必须用docker镜像。
所以我只好再调研docker部署RAP了，科科

近期性能优化 + 接口文档模型的重构工作较多，待解决后立刻高优先级处理该问题。

毕竟rapapi.net 每天都在烧我的个人资金啊 T  .T

**Comment by colincatsu** [comment]
赞啊！~

**Comment by Bosn** [comment]
@colincatsu rapapi.net已经迁移到阿里云了，速度非常快。
docker部署方式从下一个release，也就是v0.14开始，提供docker部署。
目前rapapi.net已经用docker在跑了。

**Comment by colincatsu** [comment]
确实速度提高了不少，感觉是飞快啊

**Comment by yangaiche** [comment]
自己部署的 docker 镜像有没？
