### ISSUE TITLE
页面控制台如何发送Http请求Header

### ISSUE THREAD

**Issue by belber** [thx/RAP#287]
##### 后端测试
用页面控制台进行后端接口测试或校验的时候能够增加Http请求Header、cookies等参数吗？

**Comment by Bosn** [comment]
暂时还没有。后端测试是要跨域的，以跨域为前提在cookie作用域、header上都有一些差异。

**Comment by cyp2018** [comment]
BOSN，现在我通过AJAX调用mock插件的方式测试真实接口返回数据与mock数据的匹配结果，发生了跨域问题，请问您的5分钟视频是怎样做到跨域访问接口的问题啊!   qq 526968364

**Comment by Bosn** [comment]
插件会自动处理成JSONP

**Comment by Bosn** [comment]
我不用QQ，实时支持请使用旺旺群。

**Comment by cyp2018** [comment]
我这边跨域后，就返回不了接口数据了，代码如下：
改成同一个域就OK了
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>RAP Example</title>
<script src="http://code.jquery.com/jquery-1.11.0.js"></script>
<script src="http://raptest/rap.plugin.js?projectId=83"></script>

</head>
<body>
	<div id="container"></div>
	<script>
		$.ajax({
			url : 'http://rap.chinawayltd.com/validate/33/router/rest?sign=479A8970967B74B16321CC9F80A8EDE9&timestamp=2015-12-28+11%3A28%3A24&orgcode=100018&method=huoyunren.test.test&app_key=1089&format=json',
			type : 'get',
			success : function(json) {
				$('#container').html(JSON.stringify(json, null, 4));
				console.log(json);				
			},
			failure : function() {
				alert("failure");
			},
			error : function() {
				alert("error");
			}
		});
	</script>
</body>
</html>

**Comment by cyp2018** [comment]
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>RAP Example</title>
<script src="http://code.jquery.com/jquery-1.11.0.js"></script>
<script src="http://raptest/rap.plugin.js?projectId=83"></script>

</head>
<body>
	<div id="container"></div>
	<script>
		$.ajax({
			url : 'http://rap.chinawayltd.com/validate/33/router/rest?sign=479A8970967B74B16321CC9F80A8EDE9&timestamp=2015-12-28+11%3A28%3A24&orgcode=100018&method=huoyunren.test.test&app_key=1089&format=json',
			type : 'get',
			success : function(json) {
				$('#container').html(JSON.stringify(json, null, 4));
				console.log(json);				
			},
			failure : function() {
				alert("failure");
			},
			error : function() {
				alert("error");
			}
		});
	</script>
</body>
</html>

**Comment by Bosn** [comment]
看下具体错误是什么。
RAP默认仅拦截在接口文档里定义过的接口，如果路径不匹配，就不会拦截。

你需要确认id=83的项目里面，是否有相对路径为/validate/33/router/rest  的接口。

你可以把http://raptest/rap.plugin.js?projectId=83  返回的代码内容也贴出来。

**Comment by cyp2018** [comment]
我们公司用钉钉，您用钉钉吗？
