### ISSUE TITLE
数据重复

### ISSUE THREAD

**Issue by Hihayden** [thx/RAP#288]
我这边网速非常不稳定，在编辑状态点击“秒存”，发现网络无法访问 rapapi，此时无法提交。过了一会网络好了，我在新页面打开rapapi，重新登录，提示我有未保存的数据，是否加载，我选择加载，保存之后出现2条一样的数据。

**Comment by Bosn** [comment]
应该是恢复功能的BUG，我会想办法复现并修复。

**Comment by Bosn** [comment]
无法复现，且rapapi.net已升级到阿里云服务器，速度稳定，不太容易再出现网络问题。

请继续关注，若再次复现reopen 之

**Comment by huzhenchao** [comment]
我把项目部署到本地服务器，有时保存时就出现相同的栏目和接口，有时出现上一个版本保存的栏目，项目多人在同时使用
