### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#289]
目前在用户量较大时发现较高的性能问题，尤其是/mockjsdata/接口，动态执行js时出现较高的性能问题。

已上传线上服务器的半个多小时的JProfiler Session
[Profile文件](https://github.com/Bosn/RAPDeploy/raw/master/rap_JProfile_session_20151222.jps)

希望Java Profile高手一起帮忙查看性能瓶颈，谢谢。

**Comment by Bosn** [comment]
用JProfiler做了性能分析，我一直以为是Java跑JS慢导致的性能损耗。
没想到一个把中文转换为unicode的函数消耗竟然这么大。（如下图）

大家有什么好想法么？当初做中文unicode化的目的是为了解决乱码的问题。

![](http://gtms01.alicdn.com/tps/i1/TB1KB8JLXXXXXbTXpXX54Kl_VXX-800-374.png)

**Comment by Bosn** [comment]
### chineseToUnicodes方法消耗详情
![](http://gtms04.alicdn.com/tps/i4/TB1l7FQLXXXXXcIXXXX5mdUKFXX-680-214.png）
/mockjsdata/ 需要加/mockjs/一样，增加缓存


### getCorpList 和 getCurUserId

这个用缓存解决就可以了
![](http://gtms01.alicdn.com/tps/i1/TB1JDRALXXXXXcDXFXXnw10IVXX-600-132.png)

**Comment by jserme** [comment]
换成这样试一试

```java
  public static String chineseToUnicode(String str) {
    if (str == null) {
      str = "";
    }
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < str.length(); i++) {
      int chr1 = (char) str.charAt(i);
      if (chr1 >= 19968 && chr1 <= 171941) {// 汉字范围 \u4e00-\u9fa5 (中文)
        sb.append("\\u")
        sb.append(Integer.toHexString(chr1));
      } else {
        sb.append(str.charAt(i));
      }
    }

    String result = sb.toString();
    return result;
  }
```

**Comment by jserme** [comment]
换成concat也可以

```java
public class Main
{
    public static void main(String[] args)
    {
        long now = System.currentTimeMillis();
        slow();
        System.out.println("slow elapsed " + (System.currentTimeMillis() - now) + " ms");

        now = System.currentTimeMillis();
        fast();
        System.out.println("fast elapsed " + (System.currentTimeMillis() - now) + " ms");

        now = System.currentTimeMillis();
        concat();
        System.out.println("concat elapsed " + (System.currentTimeMillis() - now) + " ms");
    }

    private static void concat()
    {
        String s = "";
        for(int i=0;i<100000;i++)
            s.concat("*");
    }

    private static void fast()
    {
        StringBuilder s = new StringBuilder();
        for(int i=0;i<100000;i++)
            s.append("*");
    }

    private static void slow()
    {
        String s = "";
        for(int i=0;i<100000;i++)
            s+="*";
    }
}
```

java version "1.6.0_65"

![2015-12-22 2 10 30](https://cloud.githubusercontent.com/assets/451996/11949048/f2c45936-a8b5-11e5-9577-525e7e80ddaf.png)

**Comment by Bosn** [comment]
已上传线上服务器的半个多小时的JProfiler Session
[Profile文件](https://github.com/Bosn/RAPDeploy/raw/master/rap_JProfile_session_20151222.jps)

希望Java Profile高手一起帮忙查看性能瓶颈，谢谢。

**Comment by Bosn** [comment]
* 增加/mockjsdata/接口的超时机制，默认超过1秒强制去掉进程。
* 重构，更新了最新的hibernate/spring框架
* 增加了projectSummary，防止较大的字段projectData重复加载
* 引入Redis，常用服务全部缓存到Redis Server

**Comment by chenyangone** [comment]
chineseTounicode 方法中 字符串的拼接 不要用 +  ，用 append 就可以将时间缩减到1毫秒左右，减少大量String对象的创建
