### ISSUE TITLE
文档页面的框可以适配下宽高吗？

### ISSUE THREAD

**Issue by jokefaker** [thx/RAP#291]
分辨率高的时候，文档页面的灰色框很小，滚上滚下稍微有点麻烦阿=。=
或者可以左边的接口列表和右边的接口详情分开来，都单独支持滚动

**Comment by Bosn** [comment]
支持超大豪宽屏这种需求忙不过来。。。。

可以做，但优先级低。亲感兴趣也可以自己研究研究。谢谢。

**Comment by steventong** [comment]
myWorkspace.css .m的height可否不限定？

**Comment by Bosn** [comment]
fixed by @jokefaker 
thx
