### ISSUE TITLE
编辑锁定状态的bug

### ISSUE THREAD

**Issue by steventong** [thx/RAP#292]
编辑文档之后 直接关闭网页 
后面再次进入该项目 alert提示有未保存的草稿 是否继续编辑 点击取消

这时候并没有将锁定状态取消 其他人无法保存编辑文档 而我也不会再次收到继续编辑的提醒

需要手动点击编辑 然后点击取消 才能取消锁定状态

**Comment by Bosn** [comment]
你有什么好的解决方案么？

异常退出确实不好知道锁定状态，至今丢弃草稿或直接解锁都是不对的。

这是比较边界的问题。我暂时没有想到好的解决方案。
