### ISSUE TITLE
Chrome 46 无法删除接口

### ISSUE THREAD

**Issue by sh00tg0a1** [thx/RAP#298]
版本：v0.12
浏览器：Chrome 46.0.2490.86 
操作：
1. 创建一个接口
2. 点击秒存
3. 点击编辑
4. 点击接口旁边的垃圾桶图表
结果：
浏览器没有任何反应

P.S. Windows Edge 浏览器正常，其他暂时没有测试过。

**Comment by Bosn** [comment]
看下错误控制台，应该是JS报错了，看看具体报了什么错误。
是不是稳定复现。

我一般开发、使用都是Chrome，所以Chrome一般是没有问题的。
