### ISSUE TITLE
创建接口问题

### ISSUE THREAD

**Issue by freexiaoyu** [thx/RAP#302]
我创建项目的时候出现项目归属为什么出现不想干的团队，这些团队不是我的，而且是必填项，我创建自己的项目点击完成后出现3个同样的项目名称，在就是创建项目为什么是公开的，我想删除其它项目没找到这个功能在哪。

**Comment by Bosn** [comment]
1. 公开项目默认显示，过滤功能下个版本会加，只显示已经加入的私有团队。目前做法也是为了兼容老版本，因为老版本是全公开的。

2. 私有团队必须是团队成员才能创建。删除按钮在项目的悬停按钮里，前提是你有权限。关于权限，查一下用户手册。
