### ISSUE TITLE
API4：校验真实数据的正确性，RESTFUL API 验证接口URL该如何配置，谢谢！

### ISSUE THREAD

**Issue by cyp2018** [thx/RAP#305]
API4：校验真实数据的正确性

URL

http://{domaiName}/validate/{projectId}/{relativePath}?json={jsonToCompare}
输入参数

{relativePath}为相对路径，与mock服务类似。例如：
真实后端接口为：http://xxx/getJson.php，项目ID为334，则
API验证接口为：http://{domainName}/validate/334/getJson.php.
{jsonToCompare}为想要必要的JSON数据，一般为真实数据
{projectId}为项目ID
输出

输出为一个JSON，最外层是对象，包含两个字段：

result 表示校验结果
result.left 表示左边（RAP文档）所产生的Mock数据和右边比较的差异
result.right 表示右边（入参JSON字符串）和左边RAP文档比较的差异
这里之所以区分左边右边，是因为在比较时可能真实数据（右边）少了字段，也可能多了字段，所以需要两边数据相互比较一次，并分别记录在left/right字段下。
resultStr 表示校验结果的中文提示字符串

您好！ 我们公司在RAP基础上开发开放平台，现在有需求需要验证真实接口返回的数据，请问，基于RAP已有的上述功能，我该如何配置URL？

**Comment by Bosn** [comment]
亲上面贴的，就是配置方法呀，另外还有例子可以参考：
http://localhost:8001/validate/43/x?json={%22coupxxons%22:[],%22acxxt_price%22:189,%22price%22:40873,%22shop_title%22:%22\u6d4b\u8bd5\u5185\u5bb95y9z%22,%22num%22:32644,%22title%22:%22\u6d4b\u8bd5\u5185\u5bb9bpux%22,%22promotions%22:[],%22num_iid%22:%22\u6d4b\u8bd5\u5185\u5bb92k3r%22,%22pic_url%22:%22\u6d4b\u8bd5\u5185\u5bb95iq5%22,%22desc%22:%22\u6d4b\u8bd5\u5185\u5bb9hbq5%22,%22countdown_sec%22:21553,%22nick%22:%22\u6d4b\u8bd5\u5185\u5bb98519%22,%22wap_detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb90197%22,%22outer_id%22:%22\u6d4b\u8bd5\u5185\u5bb92u8n%22,%22detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb9463m%22,%22earnest%22:85535}


请查看用户手册，API4部分后面的EXAMPLE就是例子。

**Comment by cyp2018** [comment]
json={%22coupxxons%22:[],%22acxxt_price%22:189,%22price%22:40873,%22shop_title%22:%22\u6d4b\u8bd5\u5185\u5bb95y9z%22,%22num%22:32644,%22title%22:%22\u6d4b\u8bd5\u5185\u5bb9bpux%22,%22promotions%22:[],%22num_iid%22:%22\u6d4b\u8bd5\u5185\u5bb92k3r%22,%22pic_url%22:%22\u6d4b\u8bd5\u5185\u5bb95iq5%22,%22desc%22:%22\u6d4b\u8bd5\u5185\u5bb9hbq5%22,%22countdown_sec%22:21553,%22nick%22:%22\u6d4b\u8bd5\u5185\u5bb98519%22,%22wap_detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb90197%22,%22outer_id%22:%22\u6d4b\u8bd5\u5185\u5bb92u8n%22,%22detail_url%22:%22\u6d4b\u8bd5\u5185\u5bb9463m%22,%22earnest%22:85535}  不会需要将JSON数据直接放到URL上面吧？

**Comment by cyp2018** [comment]
您有QQ吗，我加您QQ聊，谢谢！

**Comment by Bosn** [comment]
使用GET或POST传递参数均可。注意要做下uri encode.
RAP交流群是阿里旺旺群：582755829

**Comment by zhoulujun** [comment]
这个问题让我也很纠结？
验证的是请求数据，还是返回数据？
比如：{keygen: "aa", pwd: "aaa", user: "aaa"}
……http://rap.taobao.org/validate/5114/get?json={keygen:%20%22aa%22,%20pwd:%20%22aaa%22,%20user:%20%22aaa%22}
 
返回的全部是（请求与返回数据都试了，post，get都试了……：
@cyp2018  解决了吗？？
qq：529892056
{
result: {
left: [
{
type: "LOST",
property: "isOk",
namespace: "obj"
},
{
type: "LOST",
property: "errMsg",
namespace: "obj"
}
],
right: [
{
type: "LOST",
property: "keygen",
namespace: "obj"
},
{
type: "LOST",
property: "pwd",
namespace: "obj"
},
{
type: "LOST",
property: "user",
namespace: "obj"
}
]
},
resultStr: "参数 obj.isOk 缺失 参数 obj.errMsg 缺失 参数 obj.keygen 未在接口文档中未定义。 参数 obj.pwd 未在接口文档中未定义。 参数 obj.user 未在接口文档中未定义。"
}
