### ISSUE TITLE
rapapi.net服务器迁移进展UPDATE

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#306]
为解决外网访问慢的问题，RAP服务器近期将向国内迁移。
新域名：rap.taobao.org 即将启用

新的部署方式依赖于docker，目前还在调研中，预计春节前完成迁移。
届时大家就可以用上飞一般的RAP啦

相关进度该帖更新，待迁移时需要服务器断网1小时，完成数据库的配置与老域名的重定向。

**Comment by cyp2018** [comment]
docker是个好东西
