### ISSUE TITLE
RAP in Docker在进行，部署RAP服务器只需一条命令

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#308]
应我司要求... 部署开源工具RAP需要用docker 镜像的形式。
我查了下，如果做好docker镜像，以后大家在部署RAP的时候也极为方便了。
我会把RAP的服务器搭建（数据库/JDK等环境安装）、配置（初始化SQL、密码设置等等）都打包到docker镜像中。

这样，理想情况下只需要一条命令就可以在docker中实现RAP服务器的部署。

v0.13版本新引入node server / redis server，配置更加复杂。所以docker的引入，是一个极好的消息。

相关进展在该帖同步，感兴趣的同学可以了解下docker

https://www.docker.com/
![](https://www.docker.com/sites/all/themes/docker/assets/images/logo.png)

**Comment by Bosn** [comment]
#285

**Comment by 327** [comment]
hi，这个计划进展到什么步骤了？

**Comment by Bosn** [comment]
rap.taobao.org就是用docker部署的，导出镜像从下个版本v0.14开始支持。

**Comment by denonzhu** [comment]
可以关注我写的自动化脚本,拆分mysql redis rap,支持手动配置,  git@github.com:denonzhu/RAP.git

**Comment by Xixi20160512** [comment]
到底是有docker部署还是没有嘛 很困惑

**Comment by ryotlee** [comment]
目前docker部署rap和rap2都失败，rap2动不动就undefined
