### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by dianniu** [thx/RAP#311]
希望能实现：

1. 管理api接口，模拟数据
2. 管理数据字典，方便查询数据库
3. 软件说明文档（支持mackrdown格式）
4. 允许部署到自己的平台上（最好是node，java，php版本都有）
6. 支持多人协作，有版本控制类似git
5. 支持数据123需求中的数据导入导出（重要！！！）

相信会有更多人fork这个项目

**Comment by Bosn** [comment]
145本来就有，6在下个版本中会出。
23不适合放在RAP中实现，wiki擅长的事情rap没必要重新实现一遍。

**Comment by dianniu** [comment]
很奇怪为神马rap官网特别特别特别特别卡顿，加载超级慢，期待优化

**Comment by Bosn** [comment]
服务器国外的，最近几天在做迁移了
