### ISSUE TITLE
我是一个团队的管理员，我怎么添加一个成员到团队呢

### ISSUE THREAD

**Issue by Tomatoo** [thx/RAP#312]
我发现，新建项目的时候添加成员是没问题的，但是项目的中途添加成员的时候提示找不到成员。查阅了wiki，说需要联系团队的管理员添加成员到团队，我在团队的页面并没有找到添加成员到团队的入口。

请问怎么添加成员到团队呢？

**Comment by Bosn** [comment]
主菜单，团队，全部团队，这里找到自己的团队右边有管理按钮。这块儿还在优化，后续会有搜索和过滤。
