### ISSUE TITLE
在线版创建非公开项目后，编辑时加不了人啊。。。

### ISSUE THREAD

**Issue by seasun** [thx/RAP#314]
在线版创建非公开项目后，编辑时加不了人；
在线版创建非公开项目后，编辑时加不了人；
在线版创建非公开项目后，编辑时加不了人；

**Comment by Bosn** [comment]
你是复读机么？

添加不了，是因为被添加人和你不在同一个团队。
先在团队管理里面把这个用户添加为团队成员。
下个版本会增加提示。

**Comment by seasun** [comment]
他限制我的字数，就V了几下。thank you very much.
