### ISSUE TITLE
是否考虑和Swagger集成

### ISSUE THREAD

**Issue by birdwyatt** [thx/RAP#320]
是否考虑和Swagger集成，项目中可以的导入Swagger生成的API的文档以及描述文件，这样减少了编写API的成本。

**Comment by Bosn** [comment]
RAP导入导出功能是计划中的功能。因为目前在重构（v0.13分支）
可能该功能还需等一等。

做好了RAP导入导出后，各位想从哪里导，按照格式做下生成器就好了。而且这些生成器可以相互贡献出来。

**Comment by jacktan1991** [comment]
同求！！

**Comment by IceWee** [comment]
我本来打算写一个的，然后调研发现RAP不能测试真实接口就放弃了。。。
