### ISSUE TITLE
请问只有admin的角色才能够编辑吗？

### ISSUE THREAD

**Issue by shiwencong** [thx/RAP#322]
我们有2个团队，各自有人负责接口设计，可是不希望2个团队的人能够互相访问各自团队的项目。
可是试了PM也没有编辑的权限。设为admin又能看到别的团队的东西。能怎么解决？

**Comment by Bosn** [comment]
可以创建两个不同的私有团队，在全部团队=>团队管理里面，可以设置团队内的权限。
