### ISSUE TITLE
queryRAPModel每次返回的数据不相同，参数顺序会有出入能解决下吗？

### ISSUE THREAD

**Issue by askday** [thx/RAP#323]
最近解析rapmodel返回的数据发现每次参数的位置都不相同很是，想了解下原因

**Comment by Bosn** [comment]
你要顺序相同可以自己排序，因为是set，序列化的时候顺序随机。

**Comment by askday** [comment]
奇怪的是 为什么页面上显示的数据从来没有乱序呢
我看你们的代码使用了gson，是这个解析json导致的
我们自己是可以处理排序，不过从用户使用角度来说还是希望拿到的数据每次是一样的
这样解析起来，进行字段比对的时候比较方便
