### ISSUE TITLE
RESTful 请求变量匹配冲突

### ISSUE THREAD

**Issue by think2011** [thx/RAP#327]
有2个接口。

1.  /api/adlet-templates/:templateId
2.  /api/adlet-templates/:templateId/serial

但是模拟数据，始终返回的是前者的那个API接口，如果我把 2 改成 `/api/adlet-templates/101/serial` 就能正确返回应该的数据。

v0.11.3 版本

**Comment by Bosn** [comment]
和 #300 是一个问题，已经修复。

**Comment by think2011** [comment]
ok!
