### ISSUE TITLE
有时候无法保存接口文档

### ISSUE THREAD

**Issue by 1018053166** [thx/RAP#329]
您的请求正在处理，请勿重复点击。

**Comment by Bosn** [comment]
因为服务器在国外网络不稳定，不过今天已经在做阿里云迁移了，大概明天就可以完成所有迁移工作，不会再有性能和间歇性被墙(科科)的问题了哦

**Comment by alading2015** [comment]
本地搭建的RAP，经常遇到您的请求正在处理，请勿重复点击的情况，是不是因为开了一天没关闭的情况呢，要怎么解决呢，经常第二天又好了

**Comment by BoydYang** [comment]
我也遇到了，不知道什么时候好; 重启tomcat, 还好提示有草稿可以恢复，不错！
