### ISSUE TITLE
重要：对外RAP站点已迁移到阿里云，速度飞起来！

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#330]
因国外服务器网络不稳定，迁移至阿里云的计划已经接近尾声。
今天将完成最后的数据迁移和域名解析工作。

迁移完成后，域名变更为rap.taobao.org

原域名rapapi.net将做跳转。

具体进度请订阅本贴，阿里云服务器迁移完毕后会大幅度提升国内访问速度，机器配置也由单核1G内存升级到4核4G，不会再出现服务器内存爆满的问题。

特别感谢阿里云提供服务器资源，支持开源项目。谢谢！
http://www.aliyun.com

Bosn

**Comment by Bosn** [comment]
服务器已搭建完毕：http://139.129.8.215/org/index.do

数据迁移中，rapapi.net服务可能期间暂停一会儿。

**Comment by Bosn** [comment]
rapapi.net服务已暂停
rap.taobao.org已启用

数据还在迁移中，预计几分钟内完成。

**Comment by Bosn** [comment]
迁移完成，现在大家可以通过：
http://rap.taobao.org 访问RAP服务啦

旧的rapapi.net解析需要些时间，请大家用rap.taobao.org访问，后续rapapi.net域名将被禁用。

**Comment by bibodeng** [comment]
rap.taobao.org又无法访问了

**Comment by dolphinZhou** [comment]
rap.taobao.org又无法访问了
