### ISSUE TITLE
如果不用jquery或kissy，RAP是不是就没啥用？

### ISSUE THREAD

**Issue by codering** [thx/RAP#342]
一直很疑惑，不知道大家是怎么使用rap的
1、现在一些mvvm框架自己实现一套ajax API , 或者干脆直接使用fetch, 因此 jquery完全可以不使用。
2、RAP  现在还不支持 promise ?
3、公司规模不大，真的需要集中维护这份规则吗？

考虑以上3种场景，RAP是不是就没啥用 ？ 直接用mockjs就可以了？

**Comment by Bosn** [comment]
建议仔细了解下RAP在评论...

插件确实支持的还不够好，目前只支持jQuery/KISSY，但是Mock数据是通过/mockjs/和/mockjsdata/ API直接开放出去的，直接去调用API也可以拿到数据。

RAP的优势，强依赖、GUI工具、结构结构的有效性、校验格式、自动MOCK数据等等。

更多功能文档、视频介绍都有。RAP乃至任何工具都有适合、不适合的场景。
如果亲觉得不适合，那就选择更适合的方式。
