### ISSUE TITLE
无法移到和复制接口，如下图

### ISSUE THREAD

**Issue by motian** [thx/RAP#343]
![image](https://cloud.githubusercontent.com/assets/2382215/12605221/e6928372-c4fd-11e5-9ebe-7c4af9b319f4.png)

**Comment by Bosn** [comment]
天啊，确实有问题。
现在RAP功能越来越多了，但是所有RAP的工作都是我一个人维护。
每次发新版本的时候，很难测全所有CASE。

修复中....进展见该issue更新

**Comment by Bosn** [comment]
已修复，下一个release或rap.taobao.org下一次更新时就会修复。


### 原因

旧的临时数据对象，我用大数 ( id > 99999999)来表示，这样在数据量越来越大时，可能会有问题。
所以修改为从-1开始递减。

而老的逻辑采用 > 0 判断，所以被误认为没有选中任何tab，导致报错。
