### ISSUE TITLE
测试的时候直接访问后端服务接口，是否可行？

### ISSUE THREAD

**Issue by xie-zhichao** [thx/RAP#348]
测试的时候直接访问后端服务接口，是否可行？

**Comment by Bosn** [comment]
可以啊，右上角输入后端接口的路径即可。
不过要允许跨域访问，这样RAP Server才能访问成功。

**Comment by xie-zhichao** [comment]
我试过，返回信心是一个：301 Moved Permanently 页面

**Comment by Bosn** [comment]
那要问你自己咯。。。。访问真实服务器返回301。。。你真实服务器里面怎么写的
