### ISSUE TITLE
模拟分页时，数组长度怎么和请求参数联动

### ISSUE THREAD

**Issue by jerry-i** [thx/RAP#360]

**Comment by Bosn** [comment]
@mock=$page.     page是参数名。这些文档里有写

**Comment by jerry-i** [comment]
这样不能
![image](https://cloud.githubusercontent.com/assets/11937539/13076525/bab54e56-d4ed-11e5-8138-b2a6b8e2ee75.png)
是数组长度控制，我在mockjs.com中也没找到

**Comment by jerry-i** [comment]
![image](https://cloud.githubusercontent.com/assets/11937539/13076558/fe276ec6-d4ed-11e5-9b50-62f8009d53c6.png)

**Comment by Bosn** [comment]
@mock只能写在备注里。

变量名目前还不支持$page这种写法，这个需求可能在后续版本实现。
暂时需要写死`roles|3-9`

如果你非常想返回按照请求参数page返回固定长度，你可以用@mock=function，并在function里面判断$page的值。

**Comment by Bosn** [comment]
等会儿，这个问题以前确实有，但是已经修复了。

参数名现在是支持${page}写法的。
之所以你写的不行，是因为你少了{}

`$page => ${page} `   就可以了

**Comment by Bosn** [comment]
### 用例

![](https://img.alicdn.com/tps/TB1HVG4LFXXXXc8XFXXXXXXXXXX-1236-248.png)

![](https://img.alicdn.com/tps/TB126yKLFXXXXbCaXXXXXXXXXXX-866-166.png)

链接：[http://rap.taobao.org/mockjs/145/test?page=123](http://rap.taobao.org/mockjs/145/test?page=123)
