### ISSUE TITLE
线上的RAP 为什么不是用最新的mockjs? 

### ISSUE THREAD

**Issue by teng14** [thx/RAP#362]
http://rap.taobao.org/org/index.do

老版的中文模拟数据类型太少。新版增加了挺多的模拟数据类型

**Comment by Bosn** [comment]
想用最新的需要自己在前面先引入最新的mock.js

线上版本更新和mock.js的更新本身就不同步，且目前最新的mock.js部分RAP用户反馈报错。
因此RAP中的mock.js会倾向稳定版本。

使用最新mock.js特性需要手动引入最新mock.js，自己部署的RAP可以通过替换mock-min.js文件来更新。

**Comment by teng14** [comment]
OK,如果最新的MOCKJS 测试稳定之后望换最新的 谢谢！东西做得很棒。到时自己也会部署到本地。

**Comment by Bosn** [comment]
这个，请Mock..js作者 @nuysoft  看看，Mock.js新版的很多特性都很不错，但是CMD模块加载的那个问题，希望能有解决方案，不然我这边已更新，整个AFP项目都挂了。

**Comment by nuysoft** [comment]
曲线支持 CMD 规范 <https://github.com/nuysoft/Mock/wiki/Getting-Started#seajs-cmd>
