### ISSUE TITLE
阿里妈妈急招前端啦！

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#363]
有意向的小伙伴们，请发简历至bosn@outlook.com 哦

地点：杭州、北京

我们team美女如云，技术氛围非常好。阿里无论福利待遇还是发展空间都是棒棒哒！
我们的技术创新： [http://thx.github.io/](http://thx.github.io/)
我们的开源贡献：[http://github.com/thx/](http://github.com/thx/)
阿里妈妈官网：[http://www.alimama.com/](http://www.alimama.com/)

### 岗位描述

阿里妈妈是阿里巴巴集团旗下面向全网客户的开放式网络营销平台，阿里妈妈用户体验部负责集团PC端和无线端广告平台的体验设计和前端研发工作。高级前端工程师的职责包括： 
1、广告投放系统、管理系统、创意制作工具和营销导购产品的前端和基于 Node 的 Server 端功能设计、开发和实现；
2、广告 PC 端和无线端各产品线易用性改进和技术优化； 
3、研究和探索创新的开发思路和前端技术，为生产实践带来帮助；

### 岗位要求
1、熟练运用 JavaScript / HTML / CSS,能够在脱离各前端类库后进行跨浏览器开发； 
2、具备丰富的 PC 端或无线端富应用开发经验，并有商业实战案例； 
3、有基于 Node 的 Sever 端研发经验，或至少熟悉一门非Web前端脚本的语言（如: Java / PHP / C++）； 
4、对前端技术有持续的热情,个性乐观开朗,逻辑性强,善于和各种背景的人合作； 
5、有 HTML5 或无线端 Hybrid 相关开发经验者优先； 
6、计算机、数学、自动化等相关专业本科以上学历优先；

**Comment by colincatsu** [comment]
可惜不是前端。

**Comment by Bosn** [comment]
《可惜不是你》  --- 梁静茹

**Comment by think2011** [comment]
+1

**Comment by ccidcce32167** [comment]
工作地点在哪里？

**Comment by khlipeng** [comment]
可惜不是前端。

**Comment by zhongning7924** [comment]
可惜没面上

**Comment by yatessss** [comment]
bosn。。。。刚看完慕课网的js视频。。。 就看到了。。。。

**Comment by Windancer** [comment]
~

**Comment by openwings** [comment]
**Let me in!**

**Comment by leochan2017** [comment]
希望深圳有职位哈哈

**Comment by wangcansun** [comment]
我还很菜啊。。。。

**Comment by foxundermoon** [comment]
薪资怎么样？

**Comment by aqnaruto** [comment]
招后端吗

**Comment by ivanberry** [comment]
我要去～可惜我还太嫩～

**Comment by sxyseo** [comment]
继续努力中。

**Comment by aoheng** [comment]
# 

>

**Comment by tankaiqian** [comment]
可惜不是广州

**Comment by wcj343169893** [comment]
可惜不在重庆或者深圳

**Comment by 0531Coder** [comment]
可惜我是阿里爸爸

**Comment by tic8** [comment]
可惜不是前端

**Comment by ghostpanda** [comment]
😆 可惜不是南京

**Comment by TechQuery** [comment]
@Bosn 

[Debug]  “岗位要求”第3条 —— “Sever”……

**Comment by liuyang-it** [comment]
Java 后端 可以不是我

**Comment by liuyang-it** [comment]
Java 后端 可惜不是我~求收留

**Comment by Osub** [comment]
```php
北京 php 
```

**Comment by linapex** [comment]
专业Java后端，哈哈~

**Comment by Pengch3581** [comment]
可惜不是前端

**Comment by fzninja** [comment]
huangyaoxin.com
整套博客系统使用nodejs写的,数据库和前后端都是自己写的,写过混合应用，ios商店师道,
可惜我是专科生,估计没戏

**Comment by main1015** [comment]
可惜不是前端

**Comment by fzninja** [comment]
是前端呀


发自我的 iPhone

**Comment by hlpszy** [comment]
美女如云...你们信吗？





反正我是不信...

**Comment by chow-xiang** [comment]
美女如云，大概就是“有个女的叫如云”，是这个梗吧

**Comment by profoundsoul** [comment]
可惜是杭州和北京，不然真想去试试

**Comment by J-J-J** [comment]
可惜杭州

**Comment by yujingweivip** [comment]
可惜不是上海，可惜不是前端!

**Comment by Jackson-Jack** [comment]
我们公司有个女的叫如花。

**Comment by oychao** [comment]
可惜我还没达到要求~

**Comment by SchuckBeta** [comment]
可惜....可惜我来晚了

**Comment by wangyangexpo** [comment]
可惜没有上海

**Comment by terryme007** [comment]
可惜我刚看到

**Comment by zhengyongbo** [comment]
可惜结婚了

**Comment by ghostpanda** [comment]
@zhengyongbo - -。

**Comment by txy920** [comment]
能在家办公么？

**Comment by Pines-Cheng** [comment]
可惜不是深圳。

**Comment by IDBAI** [comment]
可惜不是你

**Comment by lestchun** [comment]
可惜不是深圳

**Comment by renjiale1214** [comment]
可惜不是深圳，可惜不是移动端前端

**Comment by jilyblue** [comment]
可惜不在大杭州啊

**Comment by OneNewLife** [comment]
可惜不是爸爸hhh

**Comment by ZhangQingya** [comment]
美女如云,万里无云

**Comment by QiZZ121** [comment]
唉 技术不到家 没法去啊

**Comment by yuzexia** [comment]
技术不到家，我就是来看看的。

**Comment by 2505183916** [comment]
可惜我不是前端

**Comment by lesonky** [comment]
可惜不在杭州也不在北京

**Comment by linuxgg** [comment]
可惜超龄了。

**Comment by denonzhu** [comment]
可惜不在合肥

**Comment by XuChuangfeng** [comment]
阿里妈妈。。。那爸爸呢

**Comment by liangzai92** [comment]
真牛逼，广告都发到京东来了

**Comment by gaoKuoZqq** [comment]
可惜不在铁岭

**Comment by zhangzhongchen** [comment]
``

**Comment by Pmmmmmmmmmm** [comment]
可惜过了5年了

**Comment by 2505183916** [comment]
那就让他过去吧&nbsp;
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 下午4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thx/RAP] 阿里妈妈急招前端啦！ (#363)





 
可惜过了5年了

**Comment by jacky-wang-design** [comment]
可惜现在已经是2230年了

**Comment by aoheng** [comment]
你好！你的邮件我已收到，谢谢你的邮件。笑一个
