### ISSUE TITLE
白名单匹配逻辑不准确,可能出现错误的匹配

### ISSUE THREAD

**Issue by angular-moon** [thx/RAP#365]
url.indexOf(o) >= 0 || o.indexOf(url) >= 0
例如有一个url为 v1/hello
 v1/helloo 也可以匹配成功

**Comment by Bosn** [comment]
是的，为了让匹配尽可能的工作，默认会采取模糊匹配的方法。这个不是BUG，而是已知问题。

例如匹配某URL可能有  actionName.do  或者actionName.action那么只要写actionName均可匹配。

但v1/hello和v1/helloo  如果有这两个接口，会精确匹配到每一个。这里有特殊的计算。

如果你不喜欢这样的方式，可以通过RAP.getWhiteList来得到并修改白名单。
