### ISSUE TITLE
如何处理多种格式的返回请求？

### ISSUE THREAD

**Issue by zg2013** [thx/RAP#367]
您好，如何处理如下场景
场景1：变参数。
   登录请求，后端返回
  {
           "status":"01/02",//01 表示成功 02表示失败。
           "userInfo":{    //当且仅当status为 01时才存在此返回对象数据。
            省略无数参数。
           }
  }
场景2：多格式参数。
  获取数据请求，后端可能返回：
  {
    "A"："1",
    "B": "B"
  }
 也可能返回
 {
   "status":"error"  请求异常
 }

请问RAP如何解决。谢谢

**Comment by Bosn** [comment]
RAP中一个接口，就表示一种结构。

不同结构可以写在不同接口里去，如

XXX接口-正常
XXX接口-异常
XXX接口-正常2
