### ISSUE TITLE
可能是代码的bug

### ISSUE THREAD

**Issue by believe1499** [thx/RAP#370]
URLUtils.java中第83行和第85行的位置是不是需要调换一下？
`public static String getRelativeUrl(String url) {
        if (url == null || url.isEmpty()) {
            return "";
        }
        if (url.contains("https://")) {
            url = url.substring(url.indexOf("/", 7));--------------------------------83
        } else if (url.contains("http://")) {
            url = url.substring(url.indexOf("/", 8));--------------------------------85
        }
        if (url.contains("?")) {
            url = url.substring(0, url.indexOf("?"));
        }
        if (url.charAt(0) != '/' && !url.startsWith("reg:")) {
            url = '/' + url;

        }
        return url;
    }`

**Comment by Bosn** [comment]
已修复
