### ISSUE TITLE
急急急 --- 导入的json数据，请求时报错

### ISSUE THREAD

**Issue by zhangtao020** [thx/RAP#371]
导入的json数据，里面有个数组，数组里面有多条数据，请求时报错，提示
![image](https://cloud.githubusercontent.com/assets/3678796/13283726/75a76b6c-db2a-11e5-8131-3664dbd7eea7.png)

导入的json数据：
{
    
    "code": 0,
    "desc": "启动成功",
    "content":[
        {
            "desc":"9.2折起",
            "spec_id":"123",
            "spec_name":"本田"
        },{
            "desc": "9折起",
            "spec_id": "1233",
            "spec_name":"本田"
        },
        {
            "desc": "9.5折起",
            "spec_id": "1223",
            "spec_name": "现代"
        },
        {
            "desc": "",
            "spec_id": "1234",
            "spec_name": "丰田"
        }]
}

**Comment by Bosn** [comment]
你运行下就正常了啊

JSON不支持function的，这是Mock.js的规则对象，不是JSON。

你可以把路径中的/mockjs/改成/mockjsdata/来直接看结果。

之所以出现图中的错误，是因为你的插件把它当JSON来理解，可它不是JSON。自然报错。
