### ISSUE TITLE
在jquery使用when执行ajax请求的问题

### ISSUE THREAD

**Issue by 95kg** [thx/RAP#372]
在jquery使用when执行ajax请求，返回的不是模拟数据，而是mock规则，这个咋破哦？好像是RAP不支持promise模式的请求

**Comment by Bosn** [comment]
直接请求/mockjsdata/的接口，或者自己做下IO拦截或适配。

**Comment by xingmolu** [comment]
直接`setPrefix('/mockjsdata/')`是可以实现的，但是比较慢，我自己搭建的服务，基本上都在300-440ms才会返回。
拦截的话可以通过dataFilter来做，但是dataFilter在请求type为jsonp的时候返回的是undefined，请教还有什么方法来做到拦截呢？
@Bosn 谢谢
