### ISSUE TITLE
RAP0.14.1redis访问不支持密码访问

### ISSUE THREAD

**Issue by fenghong007** [thx/RAP#373]
因为不想新开一个redis服务，想使用开发服务器上已经在用的redis，发现目前的RAP中访问redis不支持密码访问。

目前我自己对JedisFactory类修改了下，支持密码访问和数据库指定，RAP中是否已经可以在其他地方指定来支持？。

`
package com.taobao.rigel.rap.common.utils;

import com.taobao.rigel.rap.common.config.SystemConstant;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.Protocol;

import java.io.IOException;

class JedisFactory {
    private static JedisPool jedisPool;
    private static JedisFactory instance = null;

    public JedisFactory() {
        JedisPoolConfig poolConfig = new JedisPoolConfig();
        String host = SystemConstant.getConfig("redis.host");
        int port = Integer.parseInt(SystemConstant.getConfig("redis.port"));
        String password = this.getConfigString("redis.password");
        String db = this.getConfigString("redis.database");
        int database = db ==null ? 0: Integer.valueOf(db);
        jedisPool = new JedisPool(poolConfig, host, port, Protocol.DEFAULT_TIMEOUT,password,database);

    }

    private String getConfigString(String key){
        try {
            String v = SystemConstant.getConfig(key);
            if(v==null||v.isEmpty()){
                return null;
            }else{
                return v;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public JedisPool getJedisPool() {
        return jedisPool;
    }

    public static JedisFactory getInstance() throws IOException {

        if (instance == null) {
            instance = new JedisFactory();
        }
        return instance;
    }
}`

**Comment by Bosn** [comment]
个性化配置自己改下源代码吧。

默认配置暂不支持。
