### ISSUE TITLE
无法正常启动tomcat的

### ISSUE THREAD

**Issue by githublaohu** [thx/RAP#378]
tomcat异常是

06-Mar-2016 13:57:39.759 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Log4j2-Log4j2Scheduled-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
06-Mar-2016 13:57:39.760 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [MySQL Statement Cancellation Timer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 java.util.TimerThread.mainLoop(Timer.java:526)
 java.util.TimerThread.run(Timer.java:505)
06-Mar-2016 13:57:39.760 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)

**Comment by Bosn** [comment]
这是全部的异常么？我看到最上部只有WARNING，没有ERROR。
你需要找到ERROR的部分，看看tomcat文件夹下，搜一下rap-error.log
看看有没有什么错误日志。

**Comment by githublaohu** [comment]
rap-error.log没有内容。
rap是不是一定要 redis啊

**Comment by Bosn** [comment]
是的一定要。

**Comment by byphper** [comment]
遇到同样的tomcat warning    访问始终是404

**Comment by shen0834** [comment]
Log4j2-Log4j2Scheduled-1 的jar放在tomcat的lib包下面，这样tomcat的类加载器才能终止，和线程池，jdbc无法关闭一个原理，可以试试

**Comment by summer9989** [comment]
我遇到一样的 不过发现是redis的连接问题  因为Rap默认连接的redis 不能有密码  我去掉连接密码后 启动tomcat正常  看了源码 顺带@Bosn 其实redis建议密码也加到配置文件里
