### ISSUE TITLE
对于mock数据，APP开发人员直接通过url访问效果不理想，望改进。

### ISSUE THREAD

**Issue by itwenwu** [thx/RAP#380]
通过页面控制台请求所生成的url直接访问mock数据，返回结果mock表达式没有正确解析而直接输出。这是APP开发常见的场景，希望能支持。下面贴下过程，具体如下：

1、请求url：
http://192.168.1.100/mockjs/1/user/dept/list.json?pageSize=10&pageNo=1&startTime=123
2、响应结果：
{"rspCode":200,"totalResults":10*5,"entities|10":[{"organization":{"name":"\u7ec4\u7ec7\u540d\u79f0@WORD","parentId|+1":1,"ucode":"@WORD","parentUcode":"@WORD","id|+1":1}}],"pageSize":10,"totalPage":5,"msg":"ok","previous":false,"next":true,"pageNo":1}

**Comment by Bosn** [comment]
看用户手册，搜mockjsdata

大部分问题，用户手册常见问题和其它部分都有介绍。

**Comment by longzhiyou** [comment]
这个我使用mockjsdata 不正确，返回来的是 `{"errMsg":"\"Mock\" is not defined.","isOk":false}`
