### ISSUE TITLE
tomcat启动正常打开localhost:8080空白

### ISSUE THREAD

**Issue by zhzhh7378** [thx/RAP#383]
数据库也导入正常jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc\:mysql\://localhost\:3306/rap_db?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull&noAccessToProcedureBodies\=true
jdbc.username=root
jdbc.password=root.host=localhost
redis.port=6379
最后这个redis.port=6379什么意思

**Comment by Bosn** [comment]
看下错误日志看起来你根本没配置redis server

redis.port是redis的端口，默认不需要改。照着部署手册做就好了

**Comment by zhzhh7378** [comment]
哦谢谢回答！我刚认真的看了一下。需要安装redis服务器。我用的是window系统，是不是rap只能运行到Linux系统上啊。

**Comment by Bosn** [comment]
只要能装jdk, mysql, redis的系统就可以。
