### ISSUE TITLE
http://thx.github.io/RAP/study.html挂了

### ISSUE THREAD

**Issue by 95kg** [thx/RAP#385]
http://thx.github.io/RAP/study.html 这个页面访问不了

**Comment by Bosn** [comment]
我这里访问无问题哦。。。。
请检查网络配置，有可能是GitHub被墙....

**Comment by 95kg** [comment]
我就在github上发问题的……裂

**Comment by Bosn** [comment]
哈哈，翻墙试试

这个网站用的GitHub Pages，某些网络GitHub Pages因为***原因，间歇性被墙。

我测试过了，可以访问。翻墙吧。
