### ISSUE TITLE
RESTful格式的请求存在bug

### ISSUE THREAD

**Issue by xjchenhao** [thx/RAP#386]
规则是` /auth/users/:pageNum/:pageSize`

请求 http://rap.taobao.org/mockjsdata/1812/auth/users/1/1 失败,
请求 http://rap.taobao.org/mockjsdata/1812/auth/users/100/100 成功.

**Comment by Bosn** [comment]
和#300 是一个问题，刚刚修复。

**Comment by xjchenhao** [comment]
@Bosn push了吗, 我刚中午拉下来的代码.

**Comment by Bosn** [comment]
@xjchenhao 看commits

**Comment by xjchenhao** [comment]
@Bosn 我看到是上午的提交记录, 但我是中午饭后拉下来的啊.. 好奇怪...

**Comment by Bosn** [comment]
@xjchenhao 发布前会先修改master分支。如果着急，可以看下master的commits，是最新的代码。

合入release的都是经过测试的版本，但也会延后一些。

**Comment by xjchenhao** [comment]
OK 看到了 谢谢啊~~

**Comment by xjchenhao** [comment]
@Bosn 额, 你好, 好像这个问题还没修复诶. 我又试了一下, 不管是拉下来本地运行. 还是[在线rap](http://rap.taobao.org/)都有问题哦.

请求 http://rap.taobao.org/mockjsdata/1812/auth/users/1/1 失败,
请求 http://rap.taobao.org/mockjsdata/1812/auth/users/100/100 成功.

**Comment by Bosn** [comment]
修复了但是没上线呢。我不可能修一个bug上线一次。你如果着急看上面commit自己按照我改的改自己的

**Comment by xjchenhao** [comment]
@Bosn 作者你好，这个问题过了那么久，还是没有修复啊。
现在`http://rap.taobao.org/mockjsdata/1812/auth/users/1/1`和`http://rap.taobao.org/mockjsdata/1812/auth/users/100/100`都无法返回正确的值了。跟我的设置没关系吧。
![image](https://user-images.githubusercontent.com/5373111/28253525-67cb600a-6ad7-11e7-9bd9-179e3788f01c.png)

**Comment by mijingling** [comment]
@Bosn @xjchenhao 这个bug在#300中未完全修复，[#300](https://github.com/thx/RAP/commit/424d7a3345f9a282c63224c1b41eac562d76546b)
根本原因是正则中$1所取值开头的/没有取到导致的，建议修复方案(\\/|$)改为(|$)即可
即com.taobao.rigel.rap.common.utils.URLUtils.java中line106行修改为
url = url.replaceAll("/\\d+(|$)", "/:number$1");
