### ISSUE TITLE
作者维护的RAP系统中创建团队后，在创建项目时无法找到。

### ISSUE THREAD

**Issue by lidianhao123** [thx/RAP#387]
本人特别欣赏作者的产品，特意试用刚产品，但是在开始使用就遇到问题。
我注册账号（账号名：lidain）-》创建团队（团队名：小小组）；而后想创建项目，在项目归属中无法找到自己创建的团队，顾提问希望帮助解答

**Comment by Bosn** [comment]
http://rap.taobao.org/org/group.action?plid=1292

在这里创建，另外看到你已经创建项目了呀

**Comment by lidianhao123** [comment]
@Bosn 您好，我刚创建完团队后一段时间内在创建项目归属时无法找到我创建的团队名称的。我再次创建了一个团队进行测试还是存在这个问题。目前我确实能够正常使用，只是希望向您反馈这个bug。
![0b9d l k5cbros 1ijyp](https://cloud.githubusercontent.com/assets/7970645/13735382/b84054f8-e9e3-11e5-8886-8eea226d2143.png)

我比较怀疑创建项目时，项目归属数据在后端缓存了。

**Comment by Bosn** [comment]
@lidianhao123 嗯，应该是缓存的问题，感谢亲的反馈。

**Comment by Bosn** [comment]
已在commit 74e963eb61ee2c7b18fd32fd51ae3db6d6df6d2a 中修复
