### ISSUE TITLE
报文字段不能按导入的顺序排列

### ISSUE THREAD

**Issue by martinzhang** [thx/RAP#388]
不能对报文字段排序。

**Comment by Bosn** [comment]
是的呢，不能对字段排序。默认按照字段字母顺序排列。暂不提供自定义排序功能。

**Comment by youngwind** [comment]
今天我也发现这个问题，感觉不太方便呢，请问打算增加这个功能吗？ @Bosn

**Comment by Bosn** [comment]
@youngwind 不能，现默认按照字段变量名字母排序，喜欢别的排序方式需要在rap.js代码中自行开发。

**Comment by youngwind** [comment]
好的 @Bosn

**Comment by edwardaa** [comment]
能否不排序？
