### ISSUE TITLE
部署好注册时一直报： 账户必须由数字/字母/下划线组成,长度6-32.

### ISSUE THREAD

**Issue by dennislan** [thx/RAP#389]
部署好注册时一直报： 账户必须由数字/字母/下划线组成,长度6-32. 请问是哪里配置错了？ 谢谢！

**Comment by Bosn** [comment]
错误原因：账户必须由数字/字母/下划线组成,长度6-32 .....

你应该把你的账户贴出来

**Comment by dennislan** [comment]
感谢您神速的回复！  我是本地部署的。在注册时如下图：
![screen shot 2016-03-14 at 10 19 14](https://cloud.githubusercontent.com/assets/1840697/13733486/65070814-e9ce-11e5-89dd-ac305835341d.png)

**Comment by Bosn** [comment]
错误提示里写的是：账户。。。长度。。。必须是6~32

亲的账户是test，一共有t...e....s...t...四个字母。所以长度是4.

根据4 < 6这样一个神奇的不等式，亲长度为4的账户并不满足大于等于4，小于等于32的账户要求。

**Comment by dennislan** [comment]
抱歉! 红字在确认密码下面，下意识认为是密码的问题！给您添麻烦了

**Comment by Bosn** [comment]
不客气哈，欢迎有问题再提issue。
