### ISSUE TITLE
callback name冲突

### ISSUE THREAD

**Issue by answer-huang** [thx/RAP#391]
自己请求里面就带有 _c 参数，跟callback name冲突了，可以关闭这个 callback name的响应么。

**Comment by Bosn** [comment]
```
_c=abc&callback=def
```

_c和callback都有时，callback优先级更高。所以你改为callback就可以了。
如果callback冲突，那就只能修改源代码了。_c和callback是非常常见的JSONP字段，自己的程序逻辑尽量不要用它做普通参数传输。
