### ISSUE TITLE
请问我下载的war包中为什么没有classes目录

### ISSUE THREAD

**Issue by wangyunli** [thx/RAP#394]
在Release页面中下载war包（建议用最新）， 将war包修改为ROOT.war后放入tomcat webapps文件夹中。 startup.sh(.bat)启动tomcat，该war包自动部署到文件夹ROOT 停掉服务器，打开ROOT中得WEB-INF/classes/config.properties 来修改数据库配置 启动tomcat，完成部署。

请问我下载的war包中为什么没有classes目录，这么不靠谱啊，还什么抱的阿里的大腿，我嘞个去，浪费我的感情啊

**Comment by Bosn** [comment]
就是，别浪费感情了。没能力又没耐心是我们永远无法解决的问题。

**Comment by sloth2012** [comment]
这个你把tomcat停掉就行了
