### ISSUE TITLE
发生严重错误，请联系维护人员并保留现场。

### ISSUE THREAD

**Issue by OneNewLife** [thx/RAP#395]
加载我的mock数据的时候发生严重错误了

http://rap.taobao.org/workspace/myWorkspace.do?projectId=1457#10791
![qq 20160322083701](https://cloud.githubusercontent.com/assets/10388933/13938748/6dbbef2e-f009-11e5-9897-9f394f0abc00.png)

**Comment by Bosn** [comment]
链接贴出来，不用担心，没权限的人打不开。

**Comment by OneNewLife** [comment]
已贴，谢谢

**Comment by Bosn** [comment]
G:\tomcat\apache-tomcat-7.0.52\webapps\sewage\uplode/

**Comment by Bosn** [comment]
你把G:\tomcat\apache-tomcat-7.0.52\webapps\sewage\uplode/  

最后的/去掉，或者改成\就好了
/会被转义成\/，在Mock.mock处理的时候变成不合法的字符串了。

**Comment by edagarli** [comment]
不是很理解你说的，我内网搭建了一个玩玩，结果也出现上面的问题。我的tomcat下面没有你的那个目录。
