### ISSUE TITLE
MOCK请求地址得到JSON是不正确，感觉是不是JS解析的问题？

### ISSUE THREAD

**Issue by dengjie200** [thx/RAP#396]
我用这个json做测试。如下：
{"code":"J000000","description":"成功","resultMap":{"iTotalDisplayRecords":2,"rows":[{"codeType":"11","codeTypeName":"111","codeValue":"11","codeValueName":"的说法发","id":1,"isDefault":false,"orderNo":1,"remark":"啊手动阀撒"},{"codeType":"22","codeTypeName":"222","codeValue":"22","codeValueName":"的发顺丰","id":2,"isDefault":false,"orderNo":2,"remark":"打发士大夫"}]},"success":true}

然后mock访问mock地址是后出来的是：
{"resultMap":{"iTotalDisplayRecords":2,"rows|2":[{"codeTypeName":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'11\u58eb\u5927\u592b1\',\'\u58eb\u5927\u592b222\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10120';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"codeType":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'11\u58eb\u5927\u592b\',\'22\u963f\u4e09\u5730\u65b9\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10121';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"codeValueName":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'\u7684\u8bf4\u6cd5\u53d1\',\'\u7684\u53d1\u987a\u4e30\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10122';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"id":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1,2)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10123';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"isDefault":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(false,false)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '  类似如此的。这个米有办法使用。求助一下。

**Comment by dengjie200** [comment]
浏览器用safari和chrome都测试过一样的情况。我这边暂时是war包部署在windows机器上的。

**Comment by Bosn** [comment]
使用JSON导入，导入的数据，为了默认mock显示的最终数据和导入一致，使用Mock.js自定义函数特性，编译成复杂的规则。

最终生成的Mock数据会和导入数据一致。

默认MOCK API返回的是Mock.js规则，而不是最终数据。这里在用户手册中，搜索mockjsdata有详细的解释。包括如何返回Mock数据而不是规则，以及为什么要这样做。

**Comment by youngwind** [comment]
@dengjie200 请问你找到解决方案了吗？我貌似也碰到了同样的问题。

@Bosn 还是没能理解rap与mock的关系，你说的mock是这个吗？ https://github.com/nuysoft/Mock/wiki/Syntax-Specification
我知道如何用mock生成假数据，但是不能理解rap里面的@mock=$order(...)这些语法与mock之间的关系。
