### ISSUE TITLE
导入json报错

### ISSUE THREAD

**Issue by huixisheng** [thx/RAP#398]
![image](https://cloud.githubusercontent.com/assets/1518967/14010293/e378a056-f1ce-11e5-9be2-a045d07aff22.png)

ajax `http://rap.taobao.org/workspace/checkIn.do` 接口返回

> 当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
Unknown Exception
java.lang.NullPointerException
...

**Comment by Bosn** [comment]
百分百必现么？控制台输入以下代码：
```js
document.body.innerHTML = ws._getData()
```
然后把数据内容发送到我的邮箱bosn@outlook.com  
另外错误也要贴全，别用省略号。

**Comment by huixisheng** [comment]
目前已经正常
