### ISSUE TITLE
数据库报错

### ISSUE THREAD

**Issue by firewood1122** [thx/RAP#402]
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at 

运行一段时间后，数据库占用cpu 100%，然后进入页面报错

**Comment by Bosn** [comment]
无法创建数据库连接，请检查数据库配置文件和数据库服务器状态。
