### ISSUE TITLE
接口能否增加长度与是否必填

### ISSUE THREAD

**Issue by zxhdaniel** [thx/RAP#406]
目前接口只有：变量名、含义、类型、备注
能否增加“最大长度“、”是否必填“这2个空，接口的使用方，也相当关注这2个空呢~

**Comment by Bosn** [comment]
备注想填啥就填啥，附加信息写在备注里。

**Comment by zxhdaniel** [comment]
但是这2个也是很通用的，估计不给个空出来的话，要处女座的，才能在备注里面把这2个信息都写清楚...

**Comment by Bosn** [comment]
在备注里写不清楚的话，不是星座问题，是智商问题。

备注就是为了防灵活多变信息的，不是所有字段都有长度，另外如果大多为必选，备注可选的。反之备注必选的就可以，更方便一些。

**Comment by zxhdaniel** [comment]
谢谢

**Comment by One2r** [comment]
支持添加“是否必填”项！

**Comment by liurx** [comment]
是否必填这一项真的很需要
