### ISSUE TITLE
$.ajax(...).done(...) is undefined

### ISSUE THREAD

**Issue by ql2005** [thx/RAP#407]
尝试了rap.taobao.org之后感觉rap很好用,于是让运维的同事下了release的版本自己部署了一个
但是发现用
```
$.ajax({
    url: '/path/to/file',
})
.done(function() {
    console.log("success");
});
```
这种办法ajax请求报错, 老的写法没问题
```
$.ajax({
    url: '/path/to/file',
    success:function (res) {
    }
});
```

之前用rap.taobao.org都不会的....求解

**Comment by Bosn** [comment]
ERROR CODE:500，服务器无法响应。
错误信息：从楼主提供的信息中，无法计算出错误原因。非常抱歉。
ERROR MESSAGE: Sorry, from the messages provided by the author, we don't know the reason causing this problem.

**Comment by ql2005** [comment]
=,=|||

github的回复500了?

**Comment by ql2005** [comment]
怎么关闭了....

找到原因了~
这里也怪我代码没贴全...提示 done is undefined
其实undefined的根本不是done....

```
$.ajax({
    url: '/path/to/file',
})
.done(function() {
    console.log("success");
})
.fail(function() {
    console.log("error");
})
.always(function() {
    console.log("complete");
});
```

这样链式调用, $.ajax 返回的是deferred对象, mock.plugin.js 里done没有返回deferred对象,导致后面链式的 file,always方法undefined

mock.plugin.js 里
```
oldDone.apply(this, args);
return rv;
```
解决该问题~

很奇怪....只有我出现这个问题么?....

**Comment by Bosn** [comment]
Nice，有效回帖。Reopened。

该BUG修复中...
