### ISSUE TITLE
POST请求连接真实服务器报错

### ISSUE THREAD

**Issue by TomJony** [thx/RAP#409]
你好， Bosn
后台服务定义为Post请求，我在TestPage页面连接真实后台的时候报错，错误信息如下：
9  error occurred!, detail:Unexpected identifier
通过fiddler发现错误信息如下：
<Error>
<Message>
The requested resource does not support http method 'GET'.
</Message>
</Error>

通过看浏览器信息报错：
pageTester.js:206 Uncaught TypeError: Cannot read property 'formatJS' of undefinedtestResHandler @ pageTester.js:206Y.io.on.success @ pageTester.js:79b.Subscriber._notify @ combo:45b.Subscriber.notify @ combo:46b.CustomEvent._notify @ combo:45b.CustomEvent._procSubs @ combo:45b.CustomEvent.fireSimple @ combo:45b.CustomEvent.fire @ combo:45d.fire @ combo:46c._evt @ combo:37c.success @ combo:37c._result @ combo:37(anonymous function) @ combo:37

请问，RAP对于post请求，需要连接后台，我需要怎么做？

**Comment by Bosn** [comment]
hi，Tom Jony 目前pageTester中，真实接口校验，暂时只支持GET的方式。并且是通过RAP Server直接请求到真实服务器的。

因为跨域策略的限制，能够支持的请求手段比较有限。亲有什么好的意见和建议，也可以给出，我们会尽力完善。

谢谢

**Comment by TomJony** [comment]
Hi， Bosn，谢谢解答。
我接触RAP几天，可能了解有限，下面是我想达到的效果：
1. 定义并管理项目的接口 --  已支持
2. 开发初期给前端模拟 -- 已支持
3. 接口自动化测试 ： 这块我想是在已定义的接口中，能够调用真实的环境，对输入、输出参数进行校验，并输出报告。
对于第三点，没有看到相关文档如何做到？

**Comment by Bosn** [comment]
自动化测试有考虑做过，但是因为RAP一直个人较小人力在做，为确保核心功能的稳定发展，没有做自动化测试功能。

但是RAP开放了Open API，将mock数据、文档数据、校验接口暴露出去。感兴趣可以自己开发想要的功能。

**Comment by hugcoday** [comment]
页面测试数据，就是用rap server 也是get方式，是不是不支持页面post模式

**Comment by nuysoft** [comment]
不支持 post 方式。
