### ISSUE TITLE
请求mock数据时，入参和出参可以使用base64编码吗？

### ISSUE THREAD

**Issue by wangcansun** [thx/RAP#410]
公司部分项目迁移到rap使用时，很多接口使用base64编码，rap可以提供这样的功能吗？

**Comment by Bosn** [comment]
我不太明白您想表达的意思，建议附上详细示例，或者换位思考的角度去表述您的问题。

**Comment by wangcansun** [comment]
我们一般的请求是传递一个json字符串过去，但是公司的一些项目是先将json字符串通过base64编码加密一遍，然后返回base64编码加密过的数据，在浏览器再将返回的数据解码成json字符串。

**Comment by Bosn** [comment]
参数如何处理，是你程序里面要做的事。对于接口的管理工具，不需要了解如何处理参数的业务逻辑。你可以在字段中备注，与大家达成一致即可。

对于mock结果，可以固定几个加密后的结果返回即可

**Comment by wangcansun** [comment]
我想一想，理清头绪。。。。

**Comment by andyfeng101** [comment]
对于入参来说，base64编码不编码都没关系，看起来入参是没有做校验的，对于返回值，可以进行二次开发，在返回的时候进行base64

**Comment by wangcansun** [comment]
@andyfeng101 我在前端进行请求和返回都可以使用base64进行解析和加密，但是当切到生产环境时就需要改代码，这样的多余的动作是我所不希望的

**Comment by zhoulujun** [comment]
我们的数据做了md5 或者其他方式加密 ……和楼上同样的情况！
