### ISSUE TITLE
关于使用mockjsdata 返回来的是 {"errMsg":"\"Mock\" is not defined.","isOk":false} 的问题

### ISSUE THREAD

**Issue by longzhiyou** [thx/RAP#412]
#### 关联问题是: #380 ，我的环境是Windows上面，经过源码查看是root根目录的问题,没有对应的路径斜杠，导致在拼接js模块目录时root与js目录直接拼接在一起。最后增加了'\\'，问题就解决了。
> 非常感谢作者提供这么好的工具，我正在琢磨怎样和swagger进行结合。

**Comment by purewater2011** [comment]
我使用的是linux环境，也出现同样的问题。

**Comment by purewater2011** [comment]
现有的rap发布的0.14.1版本修复了这个问题了吗？

**Comment by stcer** [comment]
我使用的是 0.14.1, linux环境, 出现同样的问题

**Comment by longzhiyou** [comment]
由于昨天有网友联系我，关于这个问题的解决方法，大家怎么不继续跟踪查找呢？
我就直接告诉具体的修改方式吧。
### 位置是AuthCheckFilter.java 中获取上下文路径那里
> 原来是 SystemConstant.ROOT = session.getServletContext().getRealPath(File.separator);
更改下面的方式。

``` java
SystemConstant.ROOT = session.getServletContext().getRealPath(File.separator)+"//";
```

**Comment by ivanberry** [comment]
请问，如何替换为新版本的mock. js？谢谢

**Comment by noseew** [comment]
我的Windows也有这个问题，修改后确实管用，谢谢。

**Comment by suinia** [comment]
所以这个问题至今还没解决？？？

**Comment by nuysoft** [comment]
解决方案参考关联的 issues。

**Comment by clarkhan** [comment]
@nunnly close 是在某个版本中已解决？还是不解决？

**Comment by suinia** [comment]
@clarkhan 我下载最新版war包还是有问题。估计要改代码编译war包？

**Comment by mkc-leslie** [comment]
遇到相同的问题，但我用的是war包，从release下载源码，用eclipse导入时，提示没有project文件，能把你们的源码或编译好的文件给我copy下吗？

**Comment by OSIMLY** [comment]
Tomcat版本切换到7即可，win7下测试有效，版本7和8对getRealPath(File.separator)的处理结果不同，导致8下缺少一个路径分隔符，就像上面那位仁兄说的一样。
