### ISSUE TITLE
当mock的json数据 里面有array<object>	类型时候 返回的mock数据里面有好多js！！！

### ISSUE THREAD

**Issue by pzk417** [thx/RAP#413]
mock的返回数据有：
[{"guid":function() {   var window = function(){return this;}();	.
.....
.....
等很多js

**Comment by Bosn** [comment]
关键字：自定义函数， /mockjsdata/ 
用户手册、issues里搜一搜

**Comment by Bosn** [comment]
关键字：自定义函数， /mockjsdata/ 
用户手册、issues里搜一搜

**Comment by Bosn** [comment]
关键字：自定义函数， /mockjsdata/ 
用户手册、issues里搜一搜
