### ISSUE TITLE
访问项目报错502

### ISSUE THREAD

**Issue by leeduo** [thx/RAP#417]
The proxy server received an invalid response from an upstream server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL:	http://ryze-rap.aliapp.com/workspace/myWorkspace.action?projectId=32
Server:	acenginx08.dg.aliyun.com
Date:	2016/04/06 09:09:58
Powered by Tengine

**Comment by Bosn** [comment]
详细错误信息呢？版本呢？操作系统呢？

这个错误是Tengine报的。只告诉我：“哇，出错了”，鬼知道是什么错

**Comment by Bosn** [comment]
详细错误信息呢？版本呢？操作系统呢？

这个错误是Tengine报的。只告诉我：“哇，出错了”，鬼知道是什么错

**Comment by Bosn** [comment]
详细错误信息呢？版本呢？操作系统呢？

这个错误是Tengine报的。只告诉我：“哇，出错了”，鬼知道是什么错

**Comment by leeduo** [comment]
谢谢解答!
RAP版本v.0.11.3 ,操作系统win7 64位,详细信息不知道从哪里可以看到,我的操作就是点击访问项目,就出现这个页面.在出现这个问题之前编辑过项目,但是秒存的时候卡住不动,重复几次依然卡住,然后访问就报错了.
