### ISSUE TITLE
导入json数据，生成的假数据不符合要求

### ISSUE THREAD

**Issue by youngwind** [thx/RAP#418]
# 第一个问题
我想生成下面的假数据
// 请注意choice字段，它是一个数组
```
{
  "code": 0,
  "data": {
    "questions": [
      {
        "choice": [
          '选项A',
          '选项B',
          '选项C',
          '选项D'
        ],
        "answer": 1,
        "dimension": 1,
        "id": 1,
        "question": "apple",
        "type": 1
      },
      {
        "choice": [
          'pl',
          'ap',
          'e'
        ],
        "answer": "apple",
        "dimension": 2,
        "id": 2,
        "question": "题目",
        "type": 8
      }
    ],
    "testId": 1
  }
}
```
我通过导入json功能，得到结果截图
![2016-04-07 11 10 13](https://cloud.githubusercontent.com/assets/8401872/14339465/5ac7f7b4-fcb1-11e5-98c3-628b7275552a.png)

当我保存并且请求这个接口的时候，提示
![2016-04-07 11 15 02](https://cloud.githubusercontent.com/assets/8401872/14339545/01647b10-fcb2-11e5-9d4c-489cdd24918e.png)
其他接口是能返回数据的。

# 第二个问题
接口请求成功，并且显示返回数据，但是直接点击url却显示失败，方法是get方法
![2016-04-07 11 11 47](https://cloud.githubusercontent.com/assets/8401872/14339572/28acbe80-fcb2-11e5-9e85-5e7f2e35b698.png)

直接点击url请求会报错
![2016-04-07 11 11 59](https://cloud.githubusercontent.com/assets/8401872/14339586/506fb968-fcb2-11e5-913a-97d6a12d8d44.png)

**Comment by Bosn** [comment]
问题1，点右下角链接进去，然后看看返回了什么信息，贴出来。

问题2，现在都喜欢装个JSON校验的插件，或自带JSON校验功能。遗憾的是，/mockjs/返回的本来就不是JSON，因为值有自定义函数function(){....}，所以当做JSON来校验时自然报错，但并没有错误。因为人家不是JSON啊！

**Comment by youngwind** [comment]
嗯，后来我翻了一下相关的issue，找到原因了，确实如你所言，那本就不是一个json。
其实我已经先翻看issue，而不是直接提问。
谢谢了。 @Bosn

**Comment by youngwind** [comment]
主要是我并没有使用rap生成的那个js文件来解析这个返回数据。我估计有一部分人在使用的时候也没有调用那个js文件，而是直接访问数据了。

**Comment by Bosn** [comment]
哈哈，搞清楚了就好。欢迎再次交流其它问题哦：）
