### ISSUE TITLE
我下载了源码，把发邮件的功能简单实现了下，应用到了项目组，暂时满足了需求。还是盼望Bosn实现完整功能哈。

### ISSUE THREAD

**Issue by Gradven** [thx/RAP#426]
修改功能描述：
1、可以配置发送人，暂时不支持SSL发送；
2、接收人也是配置的，当用户修改时，自动发邮件并抄送给自己。

改了几个java类，
config.properties增加了相关的配置项：
mail.host=smtp.126.com   （服务器）
mail.port=25
mail.sslPort=465 （暂不支持）
mail.from=rap_xxxxx@126.com   （发送人）
mail.username=rap_xxxxx@126.com   （发送人邮件）
mail.password=xxxxxx         （登陆密码）
mail.bccAddresses=name@xxx.com,name1@xxx.com   （收件人，逗号分隔）
mail.ccAddresses=name2@xxx.com,name3@xxx.com   （抄送人，逗号分隔）

**Comment by Bosn** [comment]
求Merge Request....

**Comment by Gradven** [comment]
好像没有权限提交吧
