### ISSUE TITLE
木有LDAP接口

### ISSUE THREAD

**Issue by lunatic20** [thx/RAP#429]
希望RAP团队可以添加LDAP接口

**Comment by Bosn** [comment]
暂时没有这方面考虑。目前接口中的数据类型是抽象的类型，用作Java, JSON, Velocity都可以。
如果类型不够可以自己再改名字或添加。

**Comment by lunatic20** [comment]
hi Bosn，是不是说要我们自己开发接口对接目前的json格式的接口？

**Comment by Bosn** [comment]
目前已有功能参见视频教程和文档，没有且在计划中的功能参见issues列表，其它的需求请考虑自己开发。

**Comment by lunatic20** [comment]
多谢

**Comment by daidou0554** [comment]
难道阿里巴巴自己用的时候也是要挨个用户的注册么？难受不

**Comment by xiaoxing598** [comment]
@daidou0554      你觉得是所有学生记校长的名字容易些，还是校长记所有学生的名字容易些。

**Comment by LinuxSuRen** [comment]
貌似只是支持HTTP这种类型的接口
