### ISSUE TITLE
插件升级，支持更多类库及方法

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#433]
支持AngularJS/React等类库

对jQuery.Promise等一些方法提供支持，重点提升jQuery各种不同使用方法的兼容性。

**Comment by slertness** [comment]
让后端定义了一堆接口 才发现不支持react

**Comment by Bosn** [comment]
可以直接访问mockjsdata api

**Comment by slertness** [comment]
怎么做 不太明白

**Comment by nuysoft** [comment]
`RAP.setPrefix('/mockjsdata/')`

**Comment by huanggm** [comment]
@nuysoft   你好，每次刷新页面都要重新在浏览器端执行 RAP.setPrefix('/mockjsdata/')。

挺麻烦的，能不能在插件的URL上加上prefix=mockjsdata来达到同样的效果呢？

现在是不行的。
