### ISSUE TITLE
有支持 fetch的插件吗

### ISSUE THREAD

**Issue by foxundermoon** [thx/RAP#436]
如题！
react + webpack + webpackDevServer 请求数据用的是 fetch。
现在有没有支持的插件 、或者以后会不会支持

**Comment by Bosn** [comment]
插件本质就是拦截IO，把自己去访问/mockjs/的API，改成自动匹配的。
自己也可以做哟~~~~

支持范围暂时只支持jQuery + KISSY

**Comment by foxundermoon** [comment]
@Bosn   那我还是用个代理服务器吧，你们的插件有开源吗？参考一下你们的接口校验功能

**Comment by Bosn** [comment]
整个RAP都是开源的。
