### ISSUE TITLE
rap支持上传下载文件的接口吗

### ISSUE THREAD

**Issue by xxiyatu** [thx/RAP#437]
有些接口是上传下载文件的，rap支持上传下载吗。还是有另外的方法支持？

**Comment by foxundermoon** [comment]
帮你测试了一下 
结果是**不可以**
结果也是很喜人的，贴出来看看
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <title>我勒个去！出错了 T.T </title> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="shortcut icon" href="/stat/img/favicon.ico"> <link rel="stylesheet" href="/stat/bootstrap/css/bootstrap.min.css?_r=20151111.v0.14.0"> <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --> <!-- WARNING: Respond.js doesn't work if you view the page via file:// --> <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]--> <link rel="stylesheet" href="/stat/css/rap.template.css?_r=20151111.v0.14.0" type="text/css" media="screen"> <link rel="stylesheet" href="/stat/js/ui/floater/css/floater.css?_r=20151111.v0.14.0" type="text/css"> <script type="text/javascript" src="/stat/js/core/jquery-2.1.4.min.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/core/tangram-1.2.1.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/core/tangram-fix.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/base.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/routes.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/bootstrap/js/bootstrap.min.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/core/ecui-1.1.0-br.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/ui/floater/js/floater.js?_r=20151111.v0.14.0"></script> <script type="text/javascript" src="/stat/js/core/rap.js?_r=20151111.v0.14.0"></script> </head> <body> <script> function getUsers(callback, teamId) { if ($.local('users')) { callback($.local('users')); return; } var params = {}; if (teamId) { params.id = teamId; } $.get($.route('org.account.all'), params, function (data) { users = data.users; $.local('users', users); callback(users); }, "JSON"); } </script> <div class="navbar navbar-fixed-top navbar-inverse" role="navigation"> <div class="container"> <div class="navbar-header"> <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#global-navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a class="navbar-brand" href="/"><i class="iconlogo mi-rap"></i> <span class="logo-text"><span id="rap-logo-text">RAP</span> v0.<span style="">14.<span style="color:#999;">1</span></span><span style="color:#cc0000;font-size:10px;">&nbsp;&nbsp;beta</span></span></a> </div> <div class="collapse navbar-collapse" id="global-navbar"> <ul class="nav navbar-nav"> <li><a href="/platform/home.do">主页</a></li> <li><a href="https://github.com/thx/RAP/wiki/home_cn" target="_blank">文档</a></li> <li style="display:none;"><a href="/platform/test.do">测试</a></li> <li><a href="/platform/log.do">数据</a></li> <li><a href="http://thx.github.io/RAP/study.html" target="_blank">教程 <!-- <span style="color:yellow;"> (new)</span> --> </a></li> <li><a id="jobHref" href="https://github.com/thx/RAP/issues/363" target="_blank" style="color:yellow;">招聘 </a></li> </ul> <div class="pull-right"> <ul class="nav navbar-nav"> <li> <a href="javascript:void(0);" class="dropdown-toggle" id="login-trigger">登录</a> <ul class="dropdown-menu dropdown-menu-right"> <li> <form name="formMain" class="navbar-form login-form" action="/account/doLogin.do" method="post"> <input class="span2 form-control" style="width:200px" type="text" placeholder="用户名" required name="account"> <input class="span2 form-control" style="width:200px;margin-top:10px;" type="password" required placeholder="密码" name="password"> <!-- <div style="margin-top: 10px; display: none;"> <div class="checkbox remember-me"> <label> <input type="checkbox" name="remember"> 下次自动登录 </label> </div>http://rap.xintuzaojiu.com/org/index.do </div> --> <div style="margin-top: 10px;"> <button type="submit" class="btn btn-primary" id="login-btn">登陆</button> <button type="button" class="btn btn-default" id="cancel-login-btn" style="margin-left: 10px;">取消 </button> </div> </form> </li> <li style="display:none;" class="divider"></li> <li style="display:none;"> <div class="navbar-form"> <a href="https://login.alibaba-inc.com/ssoLogin.htm?APP_NAME=rapauto&BACK_URL=http%3A%2F%2Frap.taobao.org&CANCEL_CERT=true&CLIENT_VERSION=0.3.9&CONTEXT_PATH=%2F"> <span class="btn btn-warning other-login-btn sso-login">用阿里域账号登录</span> </a> </div> </li> </ul> </li> <li> <a href="javascript:void(0);" class="dropdown-toggle" id="register-trigger">注册</a> <ul class="dropdown-menu dropdown-menu-right"> <li> <form name="formMain" class="navbar-form register-form" action="/account/doRegister.do" method="post"> <input class="span2 form-control" style="width:200px" type="text" placeholder="中文名" required name="name"> <input class="span2 form-control" style="width:200px;margin-top:10px;" type="email" placeholder="邮箱" required name="email"> <input class="span2 form-control" style="width:200px;margin-top:10px;"`

**Comment by Bosn** [comment]
上传和下载文件。。。你想要啥mock数据。。。。  告诉你成功？失败？
下载文件说到底就是一个链接，有啥模拟的意义么？

**Comment by foxundermoon** [comment]
@Bosn    他要的应该就是返回成功或者失败，这样可以在写客户端的时候用纯js来上传的时候确保上传功能正常。 @xxiyatu  我们是写个 express来测试前端,你也可以参考一下。

**Comment by cloudLiu** [comment]
表单提交，带文件的类型的，我看选择参数类型的时候没有file。其实也没关系就是加下标注下可以让其他人看清楚，如果是base64就是string的。
