### ISSUE TITLE
mock里如何获取到请求path 里面的 参数 以及正则匹配到的结果

### ISSUE THREAD

**Issue by foxundermoon** [thx/RAP#439]
比如  `/get/issue/:id`
我尝试用获取query的方式  `@mock=${id}` 但是发现并没有预期效果

比如   `reg:/get/issue/(.*[^/])/second/([a-z]{16})`
mock需要根据获取到匹配的内容返回不同结果、如何在mock里面获取到正则匹配的结果？

**Comment by Bosn** [comment]
暂时不支持参数化路径，mock数据别太纠结逻辑。使用自定义函数可以实现所有的逻辑，但你为了Mock数据搞的比实际开发都复杂，何必呢。

**Comment by foxundermoon** [comment]
@Bosn  自定义函数的时候要根据路径里的参数返回不同的结果。不过改为query参数也可以满足要求
