### ISSUE TITLE
ajax拦截失败？

### ISSUE THREAD

**Issue by ivanberry** [thx/RAP#440]
基本按照视频教程学习的，但是本地browser-sync测试，不能得到结果，猜测为ajax拦截失败，更改模式为`mode=1`也不行，同样的代码在codepen却能实现，代码如下：

```html
<head>
	<meta charset="UTF-8">
	<title>Rap mock server</title>
	<script src="//cdn.bootcss.com/jquery/1.12.0/jquery.js"></script>
	<script src="//rap.taobao.org/rap.plugin.js?projectId=2772&mode=1"></script>

</head>
<body>
<pre></pre>
<img src="" alt="商品地址" id="img">

<script>
//get the image element
	var el = document.getElementById('#img');

	// make a ajax request

	$.ajax({
		url: 'getUserData',
		type: 'json',
		data: {
			id: 123
		},
		sucess: function(data) {
			console.log(data);
			data.JSONstringify(data, null ,4).appendTo('body');
		},
		error: function() {
			console.log("error happends here");
		}
	});
</script>
```

控制台报错如下：

1. mode=1时，未报错，对应数据未加载
2. mode=3（默认），报错

![1](https://cloud.githubusercontent.com/assets/13112910/14582249/576ffebc-0432-11e6-8db9-033b12b21b83.PNG)

![2](https://cloud.githubusercontent.com/assets/13112910/14582250/59f94094-0432-11e6-9b59-bb7e126453c1.PNG)

是我有什么基本的地方没有掌握吗？

**Comment by Bosn** [comment]
我查了您的接口文档，写的是getUserDat**e**

但是您访问的接口却是getUserDat**a**

注意最后一个字母，不一样，导致RAP认为该接口并未定义，所以放行。
默认的模式中，RAP仅拦截已在接口文档定义过的接口（通过路径）

所以，改吧... 类似问题，仔细检查。

**Comment by ivanberry** [comment]
thx THX
