### ISSUE TITLE
使用rapapi.net的版本，并不能创建团队啊？

### ISSUE THREAD

**Issue by njleonzhang** [thx/RAP#444]
并没有找到创建团队的入口啊。而且我能看到别人创建团队的接口描述。这样不是很危险么？所以RAP并不想做成saas？如果想用还是应该自己搭服务器？

**Comment by Bosn** [comment]
1. 主菜单 => 团队 => 左下角创建团队按钮。看不到窗口放下拉一拉。在浮层最下面。
2. 公开团队全员可见，默认选项是私有团队，仅团队内可见。

仔细看下文档，自己操作下试试。

**Comment by njleonzhang** [comment]
@Bosn, macbook pro上看不到团队下拉列表的最下面，我拉到大屏幕上才看得到。建议改进
