### ISSUE TITLE
rap 能够支持 Json 格式的请求参数吗？

### ISSUE THREAD

**Issue by clarkhan** [thx/RAP#446]
如 `JSON.stringify(data)` 作为 request body，有办法解析吗？

我试了下，`Content-Type` 为 `application/json;` ，post request body 为 json 格式，无法在 response 中通过 `${xxx}` 取到值。

**Comment by clarkhan** [comment]
#374 里面好像提到了，mock 只支持 GET。
希望能支持其他请求方式的 mock 数据。

**Comment by Bosn** [comment]
MOCK插件为解决跨域问题底层都改成JSONP。
HTTP METHOD仅对真实环境有意义，不用太纠结MOCK API用什么METHOD访问。

**Comment by yaojingguo** [comment]
@Bosn 我所在项目很多REST AP的`Content-Type`是`application/json`, 数据是通过request body发送的JSON。如果RAP不能支持这种REST API的话，有没有什么work around呢？
