### ISSUE TITLE
作为管理员权限的用户创建的项目为什么在产品线线首页看不到？

### ISSUE THREAD

**Issue by xiaowing** [thx/RAP#449]
各位

最近刚开始在试用RAP  v0.14.1(部署在一台Ubuntu Server 14.04上)，很棒的一个产品。
不过，今天发现了一个问题，我们怀疑是个BUG，因此分享一下。

- Reproduce方法：

1. 由超级管理员A 权限创建一个团队，并将用户B加入该团队并将B的权限设置为管理员权限
2. 超级管理员A为该团队创建一个产品线
3. 管理员B在产品线中创建一个项目，创建成功
4. 创建成功后管理员B可以立刻在产品线首页看见创建的项目
5. 管理员B跳出产品线首页，之后再回到该产品线首页后就无法看见刚才的项目

补充：
但是，如果用户B在自己的个人首页上仍然可以看见自己创建的项目，
且， 超级管理员A在该产品线首页上可以看见B创建的项目。
(今天Github有点抽风，上传截图有点问题，所以先共享文字描述)

之所以认为这个现象可能是BUG的原因是：
1. 用户自己在产品线中创建的项目，第一次可见后，之后再回产品线首页却反而看不见了，这个不符合常理。
2. 从效果来看，表现出来的似乎成了 在这个产品线 上用户B有**写权限**，却没有**读权限**，这更加违背常识。

想听一下大家的意见~

**Comment by xiongchen2012** [comment]
一定是你打开的姿势不对~

**Comment by xiaowing** [comment]
经过反复尝试发现，该现象只在 微软的Edge浏览器上出现，且再Reproduce步骤的第五步使用F5强制刷新则又能看见新建的项目(Chrome下第五步默认可以看见新建项目)。也许是浏览器的缓存策略导致的误报，不好意思。
