### ISSUE TITLE
消息功能的使用

### ISSUE THREAD

**Issue by lyxc** [thx/RAP#450]
目前团队成员修改了项目后，消息只是提示是修改了哪个项目，并没有标明具体修改的是哪个接口。接口修改之后，团队其他成员若要了解具体修改的哪个接口，只能通过面对面的沟通？还是有其他的方式可以实现？

**Comment by Bosn** [comment]
达成共识，提交的时候写下备注。不要点快存，点一般提交写好备注就知道改了什么了。
