### ISSUE TITLE
接口测试地址不正确

### ISSUE THREAD

**Issue by ccidcce32167** [thx/RAP#452]
当接口地址填写为类似
/index.php?app=activity&mod=AppPortfolioFresh&act=awardStatus
这样时，接口测试页面返回的结果固定是另一个接口的格式，而不是该接口定义时的格式。

**Comment by Bosn** [comment]
检查是否有同名接口，接口MOCK默认仅按照相对路径匹配（忽略参数）

如果需要按照参数值匹配或正则等匹配方式，查用户手册RESTFul关键词搜索下。

**Comment by ccidcce32167** [comment]
确认过并无同名接口
