### ISSUE TITLE
RAP的全称是什么

### ISSUE THREAD

**Issue by duguyin** [thx/RAP#454]
如标题所述，RAP是哪几个单词的缩写？还是它本身就叫RAP，而不是缩写。如果本身叫RAP，请问为什么取这样一个名字。

**Comment by ivanberry** [comment]
这个问题，我来回答一下，它们是缩写，主页上就有描述的。具体我不记得了。

**Comment by duguyin** [comment]
能不能写出来

**Comment by Bosn** [comment]
Rigel Automation Platform
