### ISSUE TITLE
关于接口责任人的问题

### ISSUE THREAD

**Issue by samyau2016** [thx/RAP#455]
我们是自己内部搭建的RAP服务器，在过程中遇到一个困难。
没有编辑权限的人查看接口文档时不能看到版本信息，即不能看到编辑者，这样造成一个困难，假设接口调用者没有分配权限的情况下，发现接口有问题时不能直接找到接口的负责人，除非加入编辑权限或者在说明中注释。
所以希望能加入这个功能，可以让接口调用者在查看接口的时候能看到接口文档的最新编辑者的名字，方便直接沟通。

**Comment by Bosn** [comment]
想要标识接口责任人，或其它任何附加信息，写在接口描述里即可。

接口描述字段，可以用来写自定义信息。

这是文档。。。思维可以灵活些。
