### ISSUE TITLE
对于POST的接口请求处理

### ISSUE THREAD

**Issue by gametheworld** [thx/RAP#457]

**Comment by Bosn** [comment]
文档类型选择POST让人能看懂即可，MOCK服务器受跨域限制全部底层走的JSONP

**Comment by gametheworld** [comment]
属性能不能别按字母排序，因为在写注释的时候很难找，在json字段很多的情况下






在 2016-05-04 14:39:39，"Bosn" <notifications@github.com> 写道：


文档类型选择POST让人能看懂即可，MOCK服务器受跨域限制全部底层走的JSONP
