### ISSUE TITLE
mock.js的版本不支持随机中文的问题

### ISSUE THREAD

**Issue by toniol** [thx/RAP#459]
现在RAP用的mock.js版本是0.1.9的，这个版本不支持 ctitle/csentence/cword/cparagraph。官方的Mock.js从1.0.0版本开始支持了，麻烦能更新下吗，感谢！强迫症啊，假数据一堆英文看着好别扭！

**Comment by Bosn** [comment]
自己引入插件前，引入最新Mock.js即可。
官方不更新Mock.js是因为新版Mock.js对很多旧业务有兼容问题。
