### ISSUE TITLE
浏览器直接请求mock地址返回结果异常

### ISSUE THREAD

**Issue by xuanxiao2013** [thx/RAP#462]
![image](https://cloud.githubusercontent.com/assets/3166025/14912668/577a6cdc-0e30-11e6-9cbf-e0dce0033bbd.png)
这里正确，没有问题，但是下图浏览器直接请求，为什么对不

![image](https://cloud.githubusercontent.com/assets/3166025/14912658/49c6c428-0e30-11e6-80c5-c5168c789391.png)

**Comment by aCoder2013** [comment]
路径中的 mockjs 替换成 mockjsdata

**Comment by xuanxiao2013** [comment]
恩，好了，谢谢

**Comment by Bosn** [comment]
返回的mock规则，不是JSON，因为包含函数对象作为value。浏览器及插件当做JSON去解释自然会报错。

**Comment by hertzi418** [comment]
用http://{domainName}/api/queryModel.do?projectId={projectId} 查出reqUrl地址，然后去请求这个地址为什么会404？

**Comment by hertzi418** [comment]
路径中的 mockjs 替换成 mockjsdata，返回的还是｛resParam:17620｝ 这样的数据
