### ISSUE TITLE
v0.11.0升级到v0.14.1失败

### ISSUE THREAD

**Issue by tj13** [thx/RAP#465]
页面提示这个报错：
RAP出错啦！
当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
technical details
could not extract ResultSet
org.hibernate.exception.SQLGrammarException: could not extract ResultSet at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63) at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109) at org.hibernate.engine.jdbc.spi.SqlEx

tomcat错误日志：

15:39:22.244 [catalina-exec-1] INFO  com.taobao.rigel.rap.common.utils.SystemVisitorLog - New visitor:172.0.0.155
15:41:41.836 [catalina-exec-13] INFO  org.hibernate.hql.internal.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory
15:41:42.053 [catalina-exec-13] INFO  com.taobao.rigel.rap.common.utils.SystemVisitorLog - New logined visitor laiqian(laiqian)
15:41:42.144 [catalina-exec-13] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
15:41:42.144 [catalina-exec-13] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'access_type' in 'where clause'
15:41:42.156 [catalina-exec-13] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
15:41:42.156 [catalina-exec-13] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'access_type' in 'where clause'
15:41:42.430 [catalina-exec-12] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
15:41:42.431 [catalina-exec-12] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'this_.access_type' in 'field list'
15:41:42.444 [catalina-exec-12] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22
15:41:42.445 [catalina-exec-12] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Unknown column 'access_type' in 'where clause'
15:41:45.742 [catalina-exec-15] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1054, SQLState: 42S22

**Comment by Bosn** [comment]
DATABASE_CHANGE.md检查下，版本升级的同时，需要执行SQL脚本增加新版本需要的字段。
