### ISSUE TITLE
RAP升级文档

### ISSUE THREAD

**Issue by tj13** [thx/RAP#466]
去年开始用RAP，现在想升级到新版本。现在问题是老版本上面建了很多项目，这些数据没法通过数据库直接备份／还原过去。新版本有些表结构都不一样。
／／下面这张表新版本才有
CREATE TABLE tb_corporation_and_user
(
  user_id        INT(10) NOT NULL,
  corporation_id INT(10) NOT NULL,
  role_id        INT(10) NOT NULL,

  PRIMARY KEY (user_id, corporation_id),
  FOREIGN KEY (user_id) REFERENCES tb_user (id),
  FOREIGN KEY (corporation_id) REFERENCES tb_corporation (id),
  FOREIGN KEY (role_id) REFERENCES tb_role (id)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

／／下面这张表新版本结构有改动
CREATE TABLE tb_corporation
(
  id          INT(10) AUTO_INCREMENT NOT NULL
    PRIMARY KEY,
  name        VARCHAR(256)           NOT NULL,
  logo_url    VARCHAR(256)           NULL,
  user_id     INT(10)                NULL,
  access_type TINYINT                NOT NULL
  COMMENT '权限控制, 10普通, 20公开'
    DEFAULT 10,
  `desc`      TEXT                   NOT NULL
  COMMENT '备注',

  FOREIGN KEY (user_id) REFERENCES tb_user (id)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

能不够提供一个升级的文档？

**Comment by Bosn** [comment]
看下DATABASE_CHANGE.md，里面标记了版本到版本之间迁移时需要执行的SQL脚本，该脚本不会删除原有数据。

安全起见，操作前要先sqldump备份。
