### ISSUE TITLE
获取多条数据出现问题

### ISSUE THREAD

**Issue by burningice529** [thx/RAP#471]
获取多条数据的时候，在访问api的时候，得到的结果会有`|N`字样，影响数据的调用

## 我需要获取两条数据
![image](https://cloud.githubusercontent.com/assets/7487299/15063027/1c022f16-1379-11e6-8d10-0f77301cf1fb.png)

## 网页访问可以正常获取到2条数据
![image](https://cloud.githubusercontent.com/assets/7487299/15063031/260742a8-1379-11e6-87e8-8eac921f4f67.png)

## 访问API获取
![image](https://cloud.githubusercontent.com/assets/7487299/15063038/368a5962-1379-11e6-93a7-021649a484d3.png)

实际访问API地址得到的数据不是`list` 而是`list|2`

**Comment by Bosn** [comment]
用户手册搜mockjsdata，为什么都不仔细看文档啊，视频教程也有说明。
