### ISSUE TITLE
mojsdata 失效！

### ISSUE THREAD

**Issue by xShanQiu** [thx/RAP#473]
你好,请问下请求路径改成mockjsdata 为什么不返回 正确数据 ? 
 截图：![image](https://cloud.githubusercontent.com/assets/13234228/15103508/a498ae42-15de-11e6-842c-a59d9983950d.png)

![image](https://cloud.githubusercontent.com/assets/13234228/15103539/f281e63c-15de-11e6-9a68-81f09dae6da5.png)

部署版本：v0.14.1

**Comment by Bosn** [comment]
很抱歉，支持的环境有限。。。-  。-

建议用tomcat8

**Comment by xShanQiu** [comment]
你好！
这是我的版本：
mysql 5.7.12
redis  2.6.12
tomcat 8.0.33
jdk 1.8
RAP 部署版本：v0.14.1（尝试过release分支的最新版）
经测试
mockjsdata  还是无法显示正确数据（显示结果与上面一致）

**Comment by xShanQiu** [comment]
你好，我已经找出原因了，关联问题#412！
