### ISSUE TITLE
JSON导入数组时，数据丢失问题。

### ISSUE THREAD

**Issue by wssgzhj** [thx/RAP#474]
RAP中使用JSON导入时，如果是数组，只导入了第一组数据，其它数据丢失。
例如：
[{
    "a" : 1,
    "b" : true
}, {
    "a" : 222,
    "b" : false
}, {
    "a" : 243,
    "b" : true
}]
只返回了：
[{
    "a" : 1,
    "b" : true
}］

**Comment by Bosn** [comment]
导入最外层为数组的数据，最外层用：
{`__root__`:  [要导入的数组]} 包起来
对最外层指定的规则，要用__root__虚拟根节点，用户手册搜root有详细介绍。

**Comment by wssgzhj** [comment]
已通过旺旺群咨询解决，下面贴下解决方法，方便后面有同样疑问的小伙伴。同时，希望 RAP 负责人可以抽空修复下控制台的 bug，辛苦啦。 

直接导入 JSON 数组时，需要按照特定的格式来编辑 JSON 串。例如：
[{
    "a" : 1,
    "b" : true
}, {
    "a" : 222,
    "b" : false
}, {
    "a" : 243,
    "b" : true
}]
需要编辑字符串为：
// __root__是虚拟根节点，|3表示有3组数据，$order() 为指令函数。
{
    "__root__|3" :  [{
        "a" : “$order(1, 222, 243)",
        "b" : “$order(true, false, true)"
    }]
}
然后，RAP 控制台返回的数据会存在显示问题，如下：
{
    "__root__":[
    {
        "a":1,"b":true
    }
    ,
    {
        "a":222,"b":false
    }
    ,
    {
        "a":243,"b":true
    }
    ]
}
请求接口的 url 也存在问题，可以把请求接口的 url 中的 /mockjs/ 修改为 /mockjsdata/，再使用浏览器访问即可看到正确数据。
