### ISSUE TITLE
POST模拟发送JSON数据

### ISSUE THREAD

**Issue by dreamquster** [thx/RAP#477]
支持POST requestUrl
       {
          "user": {
               "name": “小明",
               "age": 19
           },
       }

**Comment by starleesky** [comment]
现在还不支持post模拟吧？

**Comment by miaoyinjun** [comment]
希望会支持

**Comment by Bosn** [comment]
跨域POST没啥意义

**Comment by miaoyinjun** [comment]
正需要能post  json数据呢，希望下面的版本能加上就完美了
