### ISSUE TITLE
模拟数据时遇到问题。

### ISSUE THREAD

**Issue by csyingliu** [thx/RAP#480]
http://rap.taobao.org/mockjs/3540/getLatestNewsOfWZX?#
该模拟数据访问地址，返回了一些乱起八糟的方法名什么的。

**Comment by Bosn** [comment]
这是模板，因为你用数据导入功能导入了，为了记住导入的数据自动编译成函数。用的时候不影响。

**Comment by csyingliu** [comment]
明白了，多谢。
