### ISSUE TITLE
希望能更新：支持匹配GET/POST/PUT/DELETE，支持配置自定义请求根路径

### ISSUE THREAD

**Issue by iyouling** [thx/RAP#483]
希望能更新这两个功能：
1 支持跨域模拟GET/POST/PUT/DELETE，同一个接口地址，不同method，现在都只会变成GET方式。相比之下POSTMAN的模拟请求就很完善
2 可配置自定义请求根路径

先奉上100分！

**Comment by Bosn** [comment]
自定义路径参考正则，用户手册搜reg

跨域模拟GET POST PUT DELETE没啥意义啊，你只是前端拿到数据就可以了
