### ISSUE TITLE
如何使用admin用户？

### ISSUE THREAD

**Issue by dingmingk** [thx/RAP#484]
同事忘记密码不知道如何操作，只能在数据库里删除帐户，再让用户重新注册。

看到有一个admin帐户，不知道默认密码是多少，该如何启用？

**Comment by zhousuhang** [comment]
自己的密码你肯定知道，把自己的密码（数据库中的）填到admin账户上就可以了

**Comment by dingmingk** [comment]
@zhousuhang 刚刚用SQL重置了admin的密码，但发现还是无法登录，有什么办法恢复admin密码吗？

**Comment by Bosn** [comment]
没有默认密码，修改密码很简单，你创建个新账号密码设置为123456，然后把这个新账号的密码更新过去就好了。
