### ISSUE TITLE
导入数据库失败

### ISSUE THREAD

**Issue by luludfd** [thx/RAP#486]
https://github.com/thx/RAP/wiki/deploy_on_ubuntu_cn 这个文档上
导入数据库：
mysql -u rap -p rap_db < ROOT/WEB-INF/classes/database/initialize.sql   #这条命令出错
报错信息为：
ERROR 1067 (42000) at line 521: Invalid default value for 'update_time'
数据库版本：5.5 求助怎么解决呢？

**Comment by luludfd** [comment]
以解决

**Comment by Bosn** [comment]
数据库版本在部署手册上有要求，太低的版本确实会报错哦
