### ISSUE TITLE
Uncaught TypeError: Cannot read property 'formatJS' of undefined

### ISSUE THREAD

**Issue by lifubing** [thx/RAP#488]
1， 服务搭建完成用IP:8080 访问，所有功能均正常
2， 把IP:8080 换成域名访问， server.xml 修改成80端口再访问， 执行接口进行请求拦截，一直显示：加载中，请稍后... (无结果返回，长期等待)
3， 
但控制台显示：Uncaught TypeError: Cannot read property 'formatJS' of undefined

报错：testResHandler	@	pageTester.js:205

Uncaught TypeError: Cannot read property '0' of undefined   @ pageTester.js:141

**Comment by Bosn** [comment]
得看下具体网络请求的返回，去网络面板看一下xhr的请求。

**Comment by Bosn** [comment]
亲看看网络面板的请求返回，再reopen

**Comment by niasand** [comment]
我也出现这个问题
