### ISSUE TITLE
模块不支持二级分级

### ISSUE THREAD

**Issue by jdpxiaoming** [thx/RAP#490]
您好，我想在模块下支持子模块功能 or 建立二级页面 ，因为我们API有很多三级四级功能，
关于排序我有以下问题：
1）手动添加序号1.1.x后  x超过9后如1.1.10会排序在1.1.1之前 
2）手动简历索引在接口名中后导出word还是会自动生成index 如：1.1.0 1.1.1xxx

Thanks for your work！

**Comment by nuysoft** [comment]
二级分级功能优先级很低，资源和时间有限，现在不考虑增加。
关于排序，@Bosn 已经多次回复过 issue 了，不再重复。
