### ISSUE TITLE
怎么在MUI框架当中拦截ajax的请求?

### ISSUE THREAD

**Issue by yileye** [thx/RAP#493]
我们项目中使用了mui框架，怎么用rap来调用mock的数据呢？求教？

**Comment by Bosn** [comment]
看视频教程，使用插件，如果不是jQuery KISSY，可以直接跨域调用mockjsdata接口来获得mock数据。也可以自己总体上做下拦截，并不会很难的哟~~~（就是统一的地方，根路径一改，临时改为JSONP）
