### ISSUE TITLE
支持自定义返回数据的形式吗

### ISSUE THREAD

**Issue by jiangzm** [thx/RAP#499]
不是callback(mock)形式， 而是response={mockdata}

**Comment by Bosn** [comment]
没看懂

**Comment by jiangzm** [comment]
这么暴力，17天前提的问题 2天前看一下就关掉了，都没看懂你关什么呢。

**Comment by Bosn** [comment]
你表达清楚了再reopen，我没有责任义务教您如何表达清楚你的问题。

**Comment by Bosn** [comment]
刚刚有幸领悟阁下的意思，不支持。

目前只支持JSON和JSONP，其它奇葩的类型涉及安全问题，自己部署的RAP通过修改callback变量的处理可以实现。
