### ISSUE TITLE
jQuery.ajax complete函数回调报错

### ISSUE THREAD

**Issue by jiangzm** [thx/RAP#500]
置换complete函数的参数不对，应该为complete(xhr, status)，实际为complete(data)

../mock.plugin.js
```javascript
oldComplete && (oOptions.complete = function (data) {
	if (PREFIX == '/mockjs/') {
		data = Mock.mock(data);
		if (data.__root__) {
			data = data.__root__;
		}
		if (!disableLog) {
			console.log('请求' + url + '返回的Mock数据:');
			console.dir(data);
		}

	}
	oldComplete.apply(this, arguments);
});

```

**Comment by jiangzm** [comment]
再增加一个问题
接口地址为相对地址时， 会影响mockapi的地址，
比如接口地址为“../ajax/getdata”
mockapi地址:"http://localhost:8080/mockjs/1"+“../ajax/getdata”
就会变成 "http://localhost:8080/mockjs/ajax/getdata"

**Comment by jiangzm** [comment]
继续增加一个问题
当使用__root__根节点时，在js判断if(data.__root__) 是有问题的， data.__root__可能为0 false “” null。所以正确的判断是if (data.__root__ != undefined)

**Comment by Bosn** [comment]
插件BUG
