### ISSUE TITLE
怎么链接mysql！

### ISSUE THREAD

**Issue by zs123456789** [thx/RAP#509]
求教！

**Comment by cbfmai** [comment]
在WEB-INF\classes下有个config.properties

修改对应的参数即可

**Comment by irisxu2016** [comment]
为啥启动tomcat的服务后，WEB-INF下面没有classes/onfig.properties 文件呢？

**Comment by zhangshuaizs** [comment]
@cbfmai  谢了。我没配置。这个只有本地才开始弄对吧

**Comment by cbfmai** [comment]
@irisxu2016 在部署文档有写到， 你需要把你的war包修改成ROOT.war, 最好把tomcat本身下ROOT文件夹删掉， 启动tomcat。（不过推荐你打包之前就把onfig.properties修改了）
![image](https://cloud.githubusercontent.com/assets/2399789/15731419/9760c396-28a7-11e6-8806-94d4e1d020fc.png)
![image](https://cloud.githubusercontent.com/assets/2399789/15731451/ca0e5ede-28a7-11e6-968c-ab3df130e1ce.png)

**Comment by cbfmai** [comment]
@zhangshuaizs 嗯 本地使用你需要初始化mysql数据库 源文件里面有提供

**Comment by zhangshuaizs** [comment]
@cbfmai  感谢回答我的问题。thank you！！！

**Comment by zhangshuaizs** [comment]
@cbfmai 感觉好像是java使用的。
