### ISSUE TITLE
定义接收参数id类型为字符串, 请求时id出现非数字字符时返回错误

### ISSUE THREAD

**Issue by qiu-deqing** [thx/RAP#512]
见

http://rap.alibaba-inc.com/workspace/myWorkspace.do?projectId=1103#15629

请求id为abc时返回

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
```

改为纯数字时正常返回

**Comment by Bosn** [comment]
这是内网链接，本宝宝已经离职了，打不开的呢。请再详细描述后reopen.
