### ISSUE TITLE
怎么单独升级mock.js

### ISSUE THREAD

**Issue by freehost** [thx/RAP#513]
mock官方已经升级到1.0.1了，RAP现在用的还是0.1.9，像生成中文字符串等很多功能不支持。如果要手动升级mock.js，该怎么操作？

**Comment by Bosn** [comment]
自己的RAP系统，替换mock-min.js文件。
使用线上官网RAP，在引入RAP插件前引入mock.js最新版本。或者使用Fiddler/Charles把mock-min.js映射下。
