### ISSUE TITLE
你好，我使用rap跟bsgrid一类的表格生成工具出错！

### ISSUE THREAD

**Issue by chinalijinglun** [thx/RAP#514]
是这样的，因为我们要做很多数据的输出，所以用了一个bsgrid的插件，是把返回的数据直接拼到页面的table里面，rap里面的json格式也调整跟bsgrid一样，但是始终出不来，也不报错，想问下有没有朋友遇到同样的问题！

**Comment by Bosn** [comment]
不懂啥是bsgrid
