### ISSUE TITLE
war包部署在tomcat/webapps/ROOT/WEB-INF下面没有classes/config.properties

### ISSUE THREAD

**Issue by irisxu2016** [thx/RAP#516]
root@iZ25jnemvrdZ:/usr/local/tomcat9/webapps/ROOT# ls
asf-logo.png       bg-button.png  bg-nav-item.png  bg-upper.png  favicon.ico  RELEASE-NOTES.txt  tomcat.gif  tomcat-power.gif  WEB-INF
asf-logo-wide.gif  bg-middle.png  bg-nav.png       build.xml     index.jsp    tomcat.css         tomcat.png  tomcat.svg
root@iZ25jnemvrdZ:/usr/local/tomcat9/webapps/ROOT# cd WEB-INF/
root@iZ25jnemvrdZ:/usr/local/tomcat9/webapps/ROOT/WEB-INF# ls
web.xml

将war包修改为ROOT.war后放入tomcat webapps文件夹中。 startup.sh(.bat)启动tomcat，该war包自动部署到文件夹ROOT 停掉服务器，打开ROOT中得WEB-INF/classes/config.properties 来修改数据库配置 启动tomcat，完成部署。

注意，一定要用ROOT部署，历史原因暂时只支持ROOT部署

停掉服务后，tomcat/webapps/ROOT/WEB-INF下面没有classes/config.properties

是我的操作有什么问题吗？

**Comment by Bosn** [comment]
搜索一下，find . -name config*
windows直接右上角搜索。
