### ISSUE TITLE
http://rapapi.net  这个网站怎么建立私人项目啊?

### ISSUE THREAD

**Issue by Lujango** [thx/RAP#518]
http://rapapi.net 网站上的东西都可以看，没有私有项目

**Comment by Huiguang** [comment]
1.菜单中有个"团队"的下拉列表,点击后选择右下角的"创建团队",按流程创建自己的团队并设置是否公开
2.创建项目时即可选择自己创建的团队

**Comment by Lujango** [comment]
@Huiguang @Bosn   mac上 safari浏览器看不见那个创建团队的按钮，被挤下去了。
