### ISSUE TITLE
使用JSON导入时，@mock= 里面生成的是单引号，最后请求接口时返回不正确

### ISSUE THREAD

**Issue by zhanxp** [thx/RAP#520]
使用JSON导入时，@mock= 里面生成的是单引号，如下：
@mock=$order('4526','10002','5201','35422')

最后生成的接口有错误，改成双引号就没有问题
Error: Parse error on line 1:
...erialsTypeQuantity":function() {   var w
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by Bosn** [comment]
生成的不是JSON，你的语法解析器按照JSON去解析才报错。这是提问过非常多次的问题，具体看下视频了解MOCK原理。
