### ISSUE TITLE
在线版RAP会清除数据？

### ISSUE THREAD

**Issue by zzvv** [thx/RAP#524]
RT.

**Comment by Bosn** [comment]
不会

**Comment by zzvv** [comment]
那麻烦问下，为什么之前创建的团队不在了？
并且我当时也邀请了小伙伴加入团队，他们的帐号下均看不到我当时邀请他们进的团队
然后我自己的帐号也不在了不说，创建的团队，项目，接口定义，全部无缘无故消失了
看来是个灵异事件~

**Comment by Bosn** [comment]
如果使用的是线上RAP  rapapi.net
