### ISSUE TITLE
大厂气质？随手秒关issuse？

### ISSUE THREAD

**Issue by zzvv** [thx/RAP#526]
#524 

是觉得问的没营养还是觉得不愿意直视？还是需要我贴图证实下？

**Comment by Bosn** [comment]
别那么玻璃心，首先，这个项目主要是我个人维护的。
我最近在创业，大部分精力暂时抽去做我自己公司的项目了。

你理解，我谢谢您。你不理解，我也没办法。

对于你提的#524 你问是否会清除，我已经回答了，不会。
如果数据丢失，那是数据丢失的问题，你可以再开帖子。


所以你问的问题，我回答完了，我凭什么不能关啊？
玻璃心的问题，我是更没时间和精力去解决。其实我觉得我打这么多字跟你说这个，已经挺浮夸的了。

开源项目，你选择使用，我很荣幸。但不表示我有无偿对你及时到位进行全方位技术支持的义务。

谢谢

**Comment by Bosn** [comment]
哦，对了，close掉的issue如果你觉得没解决，可以随时reopen。如果你以前不知道的话，你现在已经知道了。
