### ISSUE TITLE
这个算不算bug啊，直接发链接打开

### ISSUE THREAD

**Issue by Lujango** [thx/RAP#527]
http://rap.taobao.org/workspace/myWorkspace.do?projectId=xxx
这个是我的私有项目的链接，没有把别人加进来也可以打开
但是上一层目录进不去

**Comment by Bosn** [comment]
单独把数据发给我邮箱，包括项目id和这个人的id，我查一下。

**Comment by Eric0808** [comment]
数据库连接不上；config.properties 已经配置无误 

technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at ....

**Comment by nuysoft** [comment]
@Lujango 后来？如果依然如此再打开。
