### ISSUE TITLE
小广告：我创业咯，在北京三元桥开了家健身工作室

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#529]
微信咨询：bolifestudio

预售期间超低优惠，地点在北京朝阳区时间国际大厦（近三元桥、太阳宫），附近工作、居住的朋友别错过哟~~~嘿嘿

![](http://ww1.sinaimg.cn/large/64394518jw1f4kshnppttj20qo1uoduz.jpg)

**Comment by Lujango** [comment]
不错
