### ISSUE TITLE
requestBody的方式能读到请求参数吗？

### ISSUE THREAD

**Issue by HuangSheng** [thx/RAP#533]
我们的项目api服务器是使用的requestBody的方式传递请求参数，现在测试发现如果响应值里想用请求参数做判断的话必须用url挂参数的方式，有没有方式可以用requestBody来传递参数？

**Comment by Bosn** [comment]
暂时不支持requestBody....  （其实我不太懂啥是requestBody）

JSON API是通用的，完全可以自己做一层适配。
