### ISSUE TITLE
这两天怎么一直登陆报错

### ISSUE THREAD

**Issue by yanhaounique** [thx/RAP#540]
RAP出错啦！
当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) at com.sun.proxy.$Proxy45.validate(Unknown Source) at com.taobao.rigel.rap.account.web.action.AccountAction.doLogin(AccountAction.java:297) at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) at

**Comment by Bosn** [comment]
看起来是数据库连接错误呀，看看是不是内存泄露了，CPU/内存占用是否正常呀~我现在登不进服务器了。

@nuysoft

**Comment by yunchenwen** [comment]
这个应该是数据库连接有问题，你试下：
找到数据库配置文件ROOT/WEB-INF/classes/config.properties
修改这项
jdbc.url=jdbc\:mysql\://localhost\:3306/rap_db?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull&noAccessToProcedureBodies\=true
为
jdbc.url=jdbc\:mysql\://localhost\:3306/rap_db?useUnicode\=true&characterEncoding\=utf8

我的情况是数据的版本问题，不支持后面这些参数，修改了之后就work了，你可以先试下我这个思路。

**Comment by icexun** [comment]
没找到问题，但是重启tomcat后就好了
