### ISSUE TITLE
0.14.1无法创建分组

### ISSUE THREAD

**Issue by guanxueping** [thx/RAP#542]
之前部署0.14.0时无法创建分组（输入正常，点击“确认创建”按钮无响应；团队、产品线都可正常创建），升级至14.1后问题仍然存在。日志中也查询不到创建动作，请问是什么原因？

**Comment by Bosn** [comment]
可能是更新了war包，但是没有执行对应的数据库更新脚本。
因为新增加分组功能后，需要在数据库结构里也添加对应的表，才可以正常运作。

**Comment by guanxueping** [comment]
问题解决了，非常感谢！！
