### ISSUE TITLE
接口验签和返回数据加密

### ISSUE THREAD

**Issue by hloong** [thx/RAP#543]
请问下在这种场景下是不是没办法用：
GET请求

http://www.test.com/api1?参数1&参数2&参数3&sign=*******
其中sign中的参数是根据参数1和参数2以及参数3的数据来生成的一个参数

POST请求
提交参数的加密数据
data=密文 （AES/base64加密）

返回的数据也是一段密文，然后客户端解密后再解析json

**Comment by Bosn** [comment]
MOCK数据不要过分在意逻辑，MOCK的作用就是快速简单的实现一种情景。

当然你的需求是可以实现的，[用户手册](https://github.com/thx/RAP/wiki/user_manual_cn) 搜索${page} 会教你如何联动参数值返回不同结果。

如果你需要做一些简单的计算，也可以使用mock.js的function特性，即@mock=function(){return ${page} + 1; }  来实现你说的需求。
