### ISSUE TITLE
一直卡在登陆这

### ISSUE THREAD

**Issue by lialzmChina** [thx/RAP#544]
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.taobao.rigel.rap.common.listener.SessionListener.sessionDestroyed(SessionListener.java:42)

**Comment by Bosn** [comment]
自己部的么，啥版本啊

**Comment by lialzmChina** [comment]
已解决,是我redis配置有问题,设置的空间不够大,修改了配置就行了

**Comment by lialzmChina** [comment]
用的0.14.1,redis是不是不能使用默认配置?
