### ISSUE TITLE
这个项目根路径 不能设置嘛

### ISSUE THREAD

**Issue by yuzhang430** [thx/RAP#545]
这个项目根路径 不能设置嘛  每个项目应该能设置一个项目根路径

**Comment by Bosn** [comment]
请具体一点，给出例子。

**Comment by shawon1220** [comment]
目录部署确实有点麻烦，比如部署到domain.com/3ms/rap 这样的目录，需要修改几个地方，建议设置一个全局的basePath变量

**Comment by Bosn** [comment]
历史原因，确实这块儿还需要优化，谢谢反馈。
