### ISSUE TITLE
有他人修改了项目修改的内容能否做标记

### ISSUE THREAD

**Issue by pinkdoremi** [thx/RAP#546]
目前只能知道有人修改了项目,但是不知道具体修改了什么.
特别是老接口要做拓展.项目里一堆的接口.
不知道到底哪些接口有修改.

希望能让他人修改过的接口标绿什么的.点开查看(已读)后,标绿消失这样

**Comment by Bosn** [comment]
以前想做来着，后来一直没时间弄。
如果对这个有要求，建议大家协定好，改过什么写在提交的记录备注里就好了。

版本比较开发量比较大，之前在计划安排里，但还没弄。
