### ISSUE TITLE
使用MySql 5.7 会出现的问题

### ISSUE THREAD

**Issue by lordpeas** [thx/RAP#548]
hi ：
       发现由于mysql 5.7默认开启 sql_mode=ONLY_FULL_GROUP_BY ，导致在点击首页--》数据 的时候，会报sql error 大概意思是分组条件的问题:SELECT list is not in GROUP BY clause and contains nonaggregated column 'rap_db.tb_user.create_date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by 我修改了mysql 5.7的sql_mode

**Comment by Bosn** [comment]
部署手册本来就有写对于SQL_MODE的设置。仔细看看。
