### ISSUE TITLE
淘宝线上版本校验真实数据的正确性接口有问题

### ISSUE THREAD

**Issue by txy920** [thx/RAP#555]
1、在页面控制台生成mock数据，转换成字符串，URLEncode
     `mock地址：http://rap.taobao.org/mockjsdata/4858/list.json`
2、调用数据验证接口，地址：
     `http://rap.taobao.org/validate/4858/list.json?json=%7B%22code%22%3A1%2C%22msg%22%3A%2210%22%2C%22result%22%3A%7B%22hasMore%22%3Afalse%2C%22pageData%22%3A%5B%5D%7D%7D`

目测每次Left返回的数据结构都是
`{
    ‘isOk’ : false,
    'errMsg' : ''
}`

**Comment by Bosn** [comment]
检查路径及入参...
