### ISSUE TITLE
对象数组不能模拟多条数据

### ISSUE THREAD

**Issue by cumtping** [thx/RAP#556]
1、比如接口定义里有一个resultData数组对象，想模拟两条数据，于是改为resultData|2。这样在pageTester页面点“请求”按钮是正常的，但是使用链接访问时，resultData|2字段名被原封不动的返回。
2、$order在用链接访问时也有问题。在使用$order的地方会返回一个function代码段，如下：
   `function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order{0, 1}";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10117';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}`

**Comment by blue68** [comment]
同上

**Comment by Bosn** [comment]
。。。。。

你没理解的东西，先别着急下定义说“有问题”。。。

用户手册，搜mockjsdata，仔细看看。
