### ISSUE TITLE
无法多人协作

### ISSUE THREAD

**Issue by crazycao** [thx/RAP#560]
RAP有一个锁定机制，一旦有人开始编辑某个项目，其他所有人都编辑不了，超级管理员也没办法。这样非常不利于团队开发。建议改成按接口锁定。也就是说锁定时，只锁定接口，而不锁定项目。这样就可以多人同时开发接口协议了。

**Comment by Bosn** [comment]
感谢亲的意见反馈，目前只支持项目级锁定。如果用户较多，建议拆分多个项目，然后通过项目路由去实现数据共享。

**Comment by aqqwiyth** [comment]
其实这个主要是底层DB的设计，一个项目一行记录，所有的接口都是大JSON存储的。
多人操作同一个接口容易出现冲突，可以通过类似SVN的版本号来临时解决这个问题，把粒度缩小到项目-接口级

**Comment by aqqwiyth** [comment]
周末刚接触RAP，我们团队正在试用中,解决前后端困扰的问题，如果这个问题在我们内部很强烈的话我们后续会提交PR:)
