### ISSUE TITLE
对象数组情况下，mock （@mock=$orde）多条数据异常

### ISSUE THREAD

**Issue by blue68** [thx/RAP#563]
当类型为 array<object>时， 字段类型为 任意类型， 在此以string为例， 描述为 @mock=$order("","")的时候，对外暴露  request starting url， 返回的json格式数据解析失败
<img width="1209" alt="2016-06-29 11 26 23" src="https://cloud.githubusercontent.com/assets/2271067/16439575/719a3f20-3dec-11e6-8ca0-337c6db0a905.png">

**Comment by Bosn** [comment]
不是异常，因为不是JSON（带function的值，不是标准JSON）。
浏览器当做JSON来读的时候“报错”，实际上没有问题。不影响使用。
