### ISSUE TITLE
Mock Object

### ISSUE THREAD

**Issue by magixsource** [thx/RAP#565]
我希望模拟从一组集合中随便取出两项作为结果响应，这样的需求在
mockjs那边的模板是：
Mock.mock({
  "object|2": {
    "310000": "上海市",
    "320000": "江苏省",
    "330000": "浙江省",
    "340000": "安徽省"
  }
})

我在RAP这里写成:
@mock={xxx}不管用，查看结果，把object当string看了。看了中文wiki，唯独object这块是没有示例的，请问下该如何写此mock标签。

rap version: 0.14.1

**Comment by Bosn** [comment]
object类型，变量名：object|2
备注：@mock={"3100...":"上海市".......安徽省"}  应该就可以呀

本质还是转换成Mock.js规则。你再试下。
如果被专义，尝试用@{mock}=xxx  来防止任何转义
