### ISSUE TITLE
大家在使用RAP的过程中是如何解决动态响应的问题的？

### ISSUE THREAD

**Issue by aqqwiyth** [thx/RAP#569]
RT 比如我们开发的约定
##### 调用成功
> {code:100, data:{obj....}}
##### 调用失败
>{code:0, "msg":"调用失败了...."}

在RAP中设置响应要设置如下
>code : @mock=@pick([100,0])
msg : @mock=调用失败了
data: @mock=....

这个时候每次请求都会有3个字段输出。我估计是我的姿势不对。

**Comment by k19421** [comment]
我之前遇到这种问题是通过在code这里写一个mock的function
function(){
var code = //可以根据boolean生成一个100或0;
if(code == 0){delete this["data"];this["msg"]="调用失败了..."}else{...}
return code;//一定要记得return
}

**Comment by nuysoft** [comment]
@aqqwiyth @k19421 正解，修改响应结构用自定义函数
