### ISSUE TITLE
nodejs端mock时,mock模板有问题

### ISSUE THREAD

**Issue by vegawong** [thx/RAP#572]
使用$order规则时,mock模板会返回一个function,函数体里面有一行代码定义window和使用`__rap__context__`属性时都假设该属性所属作用域是全局的window,也就是仅面向浏览器端使用 然后在nodejs端mock的时候, 会报异常,  定位代码:https://github.com/thx/RAP/blob/9f8e61924f770ba74da80d0f4797f958fb18386c/src/main/java/com/taobao/rigel/rap/mock/service/impl/MockMgrImpl.java  :889-:909  
修改建议:  1.定义window的时候  `return this; ==> return this || {};`
                  2. 所有`__rap__context__`前面都要显式加上`window.`  ==> `window.__rap__context__`

**Comment by Bosn** [comment]
感谢亲的BUG反馈， 转给墨汁老师 @nuysoft
