### ISSUE TITLE
自部署的rap 无法请求

### ISSUE THREAD

**Issue by jingqiu2180** [thx/RAP#573]
在centos上部署的rap
已安装 tomcat jdk redis mysql rap的war包

部署完成后能登录及访问（创建项目、团队等都可以），但是创建完接口后在页面上查看mock请求的调用时，点击  请求  无反应（如果正常 右下方会出现请求详细）。
请协助查询原因。谢谢。

**Comment by LieMengDade** [comment]
你好，我其实想问下，部署成功后登陆和访问的URL是什么，我看文档没提到的样子

> 部署完成后能登录及访问（创建项目、团队等都可以）

**Comment by Raincal** [comment]
@LieMengDade 本地部署的话访问localhost:8080就可以了~
