### ISSUE TITLE
RAP提交接口改动的时候，是以整个项目为单位一次性提交的性能问题

### ISSUE THREAD

**Issue by kelvin8906** [thx/RAP#574]
RAP提交接口改动的时候，是以整个项目为单位一次性提交的，导致在配置不好/浏览器版本低的电脑上，当项目太大的时候，导致浏览器提交假死。（checkIn.do的提交的formdata太大）。

请问有方法可以优化解决吗？

**Comment by k19421** [comment]
我猜作者这么做的是因为不好确定你当前在编辑哪个接口，并且支持多个接口同时编辑吧
一个项目不用那么大吧，你要是为了使用同一个项目id调用，可以添加路由

**Comment by nuysoft** [comment]
#593 #560 
项目接口太多建议拆分项目，通过项目路由共享数据。一个业务项目可以拆成多个rap项目。
