### ISSUE TITLE
rap.taobao.org挂了

### ISSUE THREAD

**Issue by mzvast** [thx/RAP#575]
最近该站间歇性无法访问。
请问是什么原因？

**Comment by bubble66** [comment]
是不是因为今天北京机房挂了的原因吧

**Comment by mzvast** [comment]
http://www.lanjingtmt.com/news/detail/17467.shtml

看到新闻了，可能阿里云内部软件升级搞出了什么bug吧，哎，不省心。

**Comment by yanxuedong** [comment]
现在能上么

**Comment by fs523577192** [comment]
现在rap.taobao.org能ping通，但http://rap.taobao.org不能访问，即80端口无法连通
