### ISSUE TITLE
如何实现自动化测试呢?

### ISSUE THREAD

**Issue by 20130605** [thx/RAP#577]
您好,在使用rap过程中,遇到以下问题,
1.我看通过现有的接口,实现自动化测试挺难的.比如说要获取某个接口的请求参考(目前只提供了所有接口的请求参考及返回值,没有单独根据某一个接口取相关的参考的).
2.这里的Rock可以模仿数据吗?如果是自动化,怎么实现?
以上,跪求解决.

**Comment by Bosn** [comment]
Open API里有校验接口的一些接口，可以通过 编写脚本，来跑所有的测试CASE。所有返回的JSON都通过，就是验证成功了。

不过其实意义不大，一般后端本身就有这种工具，RAP更大作用还是在于联调前的开发前期，以及后续的文档维护统一、MOCK数据管理等。
