### ISSUE TITLE
RAP 你们官网的登录服务挂了

### ISSUE THREAD

**Issue by decode-life** [thx/RAP#578]
如题，官网的登录出错了

**Comment by qingmingsang** [comment]
我看也是挂了

**Comment by qingmingsang** [comment]
RAP出错啦！
当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) at

**Comment by xrds** [comment]
只能等待解决了， 文档没办法进行了。

**Comment by fanxiushan** [comment]
到现在依然没有修好..... 以后谁还敢用啊.
