### ISSUE TITLE
Chrome 36.0/Windows导出文档时出现中文乱码

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#58]
Chrome 36.0/Windows导出文档时出现中文乱码

**Comment by abincai** [comment]
同样乱码

**Comment by abincai** [comment]
貌似是utf-8 与 utf-8 bom的问题。环境是window

**Comment by Bosn** [comment]
好的，我研究下。BOM这个坑之前在RAP别的功能上踩过。

**Comment by Bosn** [comment]
@abincai 有没有具体的CASE呢？在Windows Server 2008/Mac上都无法复现。

**Comment by Bosn** [comment]
@abincai 应该与特定的内容有关系。

**Comment by abincai** [comment]
win7 centos7 到遇到.具体事例,有点忘了,都是js乱码,解决方式都是 变成 utf-8 with BOM.当时就是看,哪里乱码,找js,换成utf-8 wiht BOM 就可以

**Comment by Bosn** [comment]
正常导出的时候会有乱码么？

好吧，我试试在export的时候，去掉BOM。
该问题在生成插件代码的时候也有遇到过。

**Comment by abincai** [comment]
js 里面包含中文,而且这些中文还显示在页面上的.就是正常导出的问题,然后我才改的.本以为是win7的问题,试了用centos7 也同样问题,然后找了下,几乎都是js的问题.所以就试着去改了

**Comment by Bosn** [comment]
js的问题.... 具体是指.......源代码js的问题么？
但是这个issue说的是导出文档啊，导出文档我是在后端做的。和JS乱码有什么关系呢？

你确定你讨论的问题和这个issue里所描述的是同一个问题嘛亲

**Comment by abincai** [comment]
sorry,文档 额 额

**Comment by Bosn** [comment]
源代码乱码的问题，一般设置UTF8编码格式就OK了哈...

如果还有啥别的问题开新issue哦。

**Comment by scapefish** [comment]
用户系统 OSX10.10 safari 0.8.7/chrome 41.0.2272.104,  RAP部署环境Ubuntu 14.04 Tomcat/8.0.24 JVM 1.8.0_45-b14 导出word文件被默认识别成US-ASCII码

**Comment by Bosn** [comment]
将下载文件后缀改为.html

看问题是否复现。
