### ISSUE TITLE
mock数据的结果，和 真的结果返回的值不一致

### ISSUE THREAD

**Issue by jonerxq** [thx/RAP#581]
![image](https://cloud.githubusercontent.com/assets/4024931/16679334/6a2df392-4519-11e6-94b5-e685d2f15ff4.png) 这个接口会把参数mock的规则带过来！
![image](https://cloud.githubusercontent.com/assets/4024931/16679350/87ea5e16-4519-11e6-9582-c10ad6f475e0.png)
用 平台的mock是正确的

**Comment by jijiqw** [comment]
你跟那谁一样，也不好好看文档
https://github.com/thx/RAP/wiki/user_manual_cn
用户手册里面搜索 mockjsdata

**Comment by noseew** [comment]
改了之后返回：{"errMsg":"\"Mock\" is not defined.","isOk":false}

**Comment by k19421** [comment]
改了之后返回这个说明
你定义的mock规则不能解析
你是不是自定义的function写错了？或者你修改的mock-min.js改错了？
我看不到图片分辨不出来你的错误

**Comment by liuwf2012** [comment]
也遇到了同样的问题

使用mockjs路径正常

![20160921150109](https://cloud.githubusercontent.com/assets/7323242/18700917/6bd6fa44-800c-11e6-89a9-64fd0ce6e4ba.png)

![20160921150101](https://cloud.githubusercontent.com/assets/7323242/18700944/8c5e94fc-800c-11e6-8ae8-75256296d642.png)

但切换到mockjsdata就出错了
![20160921150133](https://cloud.githubusercontent.com/assets/7323242/18700960/a57c2c2e-800c-11e6-93cf-b21f93cc4946.png)

![20160921150119](https://cloud.githubusercontent.com/assets/7323242/18700966/ac143e1e-800c-11e6-99e5-86d4526bf4c1.png)

接口定义也没什么问题

![image](https://cloud.githubusercontent.com/assets/7323242/18701084/40ccfb68-800d-11e6-8286-38a139d203ff.png)


问题在哪呢？
