### ISSUE TITLE
没办法添加header参数啊 

### ISSUE THREAD

**Issue by Alpha2016** [thx/RAP#582]
有些时候，header需要传token等参数，这个RAP有计划增加吗？

**Comment by zhoutaoo** [comment]
同问

**Comment by Alpha2016** [comment]
> 同问

等吧，估计不会支持这个功能了，只能自己来写

**Comment by Bosn** [comment]
写文档详情描述里就好啊，MOCK功能用不到的东西。。。。所有的特别需求都可以写在接口文档描述里。

除非。。。你有好的功能需求，比如加了这个header在验证接口格式上有什么作用。

当然，因为是跨域的，最终本质都是JSONP，所以header验证并没有太大意义。
