### ISSUE TITLE
每天都是这个界面，偶尔才能登录成功，实在是没sei了

### ISSUE THREAD

**Issue by luochj** [thx/RAP#585]
RAP出错啦！
当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) at com.sun.proxy.$Proxy45.validate(Unknown Source) at com.taobao.rigel.rap.account.web.action.AccountAction.doLogin(AccountAction.java:297) at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:891) at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1293) at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:117) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:108) at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1369) at ognl.ASTMethod.getValueBody(ASTMethod.java:90) at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) at ognl.SimpleNode.getValue(SimpleNode.java:258) at ognl.Ognl.getValue(Ognl.java:494) at ognl.Ognl.getValue(Ognl.java:458) at com.opensymphony.xwork2.ognl.OgnlUtil$2.execute(OgnlUtil.java:309) at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecute(OgnlUtil.java:340) at com.opensymphony.xwork2.ognl.OgnlUtil.getValue(OgnlUtil.java:307) at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:423) at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:287) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:250) at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at

**Comment by k19421** [comment]
额....
你看看你的tomcat\webapps\ROOT\WEB-INF\classes\config.properties

**Comment by pookpal** [comment]
数据库配置正确

**Comment by toniol** [comment]
@pookpal 你试试在 config.properties 配置文件中用 mysql 的 root 账户，我刚换 root 账户可以注册登陆了。之前按照部署教程用自建的rap账户一直报这个错。不知道是不是权限问题，这个折腾我好几天了。。。
系统：CentOS 6.5 64位

**Comment by lanhongjie** [comment]
我用了数据库root用户，不能登录，也无法注册

**Comment by k19421** [comment]
@lanhongjie 可以在部署RAP的机器上面，用mysql客户端使用RAP相同的连接配置去连接mysql数据库，确认下能否连上

**Comment by linkeyd** [comment]
@k19421 账户密码都是相同　Navicat和NODEJS写的测试用例也可以正常连接，这个是什么情况？

**Comment by k19421** [comment]
@linkeyd 不知道了，看错误信息是数据库连不上，我没遇到过这个问题，所以不知道怎么解决...

**Comment by linkeyd** [comment]
@k19421 我也觉得是这个问题，所以特地写了个NODEJS的数据连接用例来测试..话说那个MYSQL的端口号在JAVA那个链接驱动里面只能用3306吗？  还是可以更改的？ 因为我的端口号都被我修改了。

以下是在本地远程连接服务器数据库写的测试用例，自己手动添加了一条数据。。。
  untitled1:server Listening on port 3000 +0ms
[数据库连接成功]  succeed!
[ RowDataPacket {
    id: 1,
    account: 'llllll',
    password: '111111',
    name: 'Linwei',
    email: '',
    create_date: Wed Aug 17 2016 11:42:16 GMT+0800 (中国标准时间),
    is_locked_out: 0,
    is_hint_enabled: 1,
    last_login_date: '0000-00-00 00:00:00',
    incorrect_login_attempt: 0,
    realname: '',
    emp_id: '1',
    mock_num: 1 } ]

**Comment by k19421** [comment]
@linkeyd 
肯定可以啊
你的tomcat\webapps\ROOT\WEB-INF\classes\config.properties
修改第二行
`jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc\:mysql\://127.0.0.1\:3306/rap_db?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull&noAccessToProcedureBodies\=true
`

**Comment by linkeyd** [comment]
jdbc.url=jdbc\:mysql\://localhost\:'这边我修改成了自己的端口号'/rap_db?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull&noAccessToProcedureBodies\=true 

哎 还是没办法连接上，有毒了。  我在重新检查下看看吧。。。

**Comment by linkeyd** [comment]
@k19421 
jdbc.url=jdbc\:mysql\://localhost\:3306/rap_db?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior\=convertToNull&noAccessToProcedureBodies\=true 
基本上没错  我把3306换成了我自己的端口号。
tomcat\webapps\ROOT\WEB-INF\classes\config.properties

**Comment by k19421** [comment]
@linkeyd 所以是可以了还是？

**Comment by linkeyd** [comment]
@k19421 前面我早就这样做了  就是出了那个问题。我现在把项目重新部署再试试人品吧。  实在没辙了。

**Comment by nuysoft** [comment]
@linkeyd 现在呢？

**Comment by Bosn** [comment]
数据库配置问题的大锅别甩给RAP好嘛？检查下你的连接超时设置是不是太低了。
错误配置导致间歇性服务中断。

**Comment by coldsmalltwo** [comment]
绝对是一个有问题的war包，不然不会死一大批

**Comment by coldsmalltwo** [comment]
配置绝对是正确的    我的Navicat能连上mysql     redisDesktop能连上redis     但是项目一打开navicat就不能打开表结构了   提示连接数过多    我感觉是连到数据库了   但是连接池有问题

**Comment by Bosn** [comment]
@coldsmalltwo 
rap.taobao.org 和阿里内网版本跑了多少年了都没问题。这种数据库连接错误，基本都是环境配置或配置文件的错误。自行调试排查吧。
