### ISSUE TITLE
新功能建议：不同产品线间的接口可以复制或移动

### ISSUE THREAD

**Issue by wdmcygah** [thx/RAP#588]
不同产品线间的接口可以复制或移动~这里主要有两个原因：1、由于项目不能同时编辑，那同一个项目多个编辑的时候可以曲线救国，新建多个项目，同时编辑然后通过移动或复制功能进行合并；2、有些项目的产品线可能存在接口重复的情况，这时复制或移动功能就显得很实用了。

**Comment by Bosn** [comment]
已经提供给你项目导入导出了啊

任何地方的项目，导出，
任何地方的项目，导入

DONE
