### ISSUE TITLE
系统优化建议

### ISSUE THREAD

**Issue by wdmcygah** [thx/RAP#590]
现在的数据模拟是接口返回后通过mockjs生成模拟数据，但是需要引入mockjs才行。所有现在接口配置后有局限，只能使用rap自带的页面进行模拟，如果通过浏览器访问或http调用（web/app测试）时mockjs定义的规则不能生效，会直接在返回结果中，希望这种返回结果能够从后台动态生成，这样就没有依赖了。

**Comment by jijiqw** [comment]
你看看你，不好好看文档
 https://github.com/thx/RAP/wiki/user_manual_cn
用户手册里面搜索 mockjsdata

**Comment by wdmcygah** [comment]
这个靠谱~弱弱地问两个问题：1、既然后台支持了，为什么默认前面页面不统一用后台的地址？觉得默认mockjsdata更加靠谱。2、后台根据是如果根据规则生成的？

**Comment by wdmcygah** [comment]
@jijiqw 这个靠谱~好东东~~弱弱地问两个问题：1、既然后台支持了，为什么默认前面页面不统一用后台的地址？觉得默认mockjsdata更加靠谱。2、后台根据是如果根据规则生成的？

**Comment by jijiqw** [comment]
@wdmcygah   如何根据规则生成  请前往 mockjs.com ， rap用的也是别人写的库。
为什么不默认， 文档里面也说了3条原因 ，还有疑问的话，就只能问他们开发团队了

**Comment by wdmcygah** [comment]
@jijiqw 恩恩，还以为你是rap开发团队成员~回头有空看看源码，感谢不吝赐教~

**Comment by wdmcygah** [comment]
@jijiqw 后台用的Mozilla rhino执行的mockjs脚本生成的动态数据。

**Comment by df007df** [comment]
放在现在着东西真应该用node开发
