### ISSUE TITLE
response响应字段过多，导致一个项目保存的时候过多的sql语句执行

### ISSUE THREAD

**Issue by airclear** [thx/RAP#594]
我们有的接口响应字段总数超过300个
整个项目加起来，字段总数就超过1w个，这样每次保存触发的sql语句实在太多了
我这边用阿里云多rds一直失败。

希望改进一下

**Comment by nuysoft** [comment]
@airclear 收到，保存、协同锁定这块会调整。

**Comment by Bosn** [comment]
失败的话，看看是不是OutOfMemory了，配置好tomcat的启动参数。
字段超过300个不是问题，阿里这边一个直通车项目有500+个接口，是接口不是参数，保存2~3秒虽然也不快，但不至于300个参数就出现性能瓶颈。

除非。。。你的服务器。。。该。升。。级。。了。。。
