### ISSUE TITLE
保存数据很慢

### ISSUE THREAD

**Issue by kmdai** [thx/RAP#597]
现在我们项目变大后，接口保存会变的非常慢，即使是小的修改，保存也会很慢，这是我的配置有问题吗，还是其他
redis服务器是3.2
mysql是５.５
系统是ubuntu14.04

**Comment by nuysoft** [comment]
有多大呢？模块数、接口数、响应数据，多大的数量级呢？

**Comment by kmdai** [comment]
接口有573个，之前是在一个项目里，模块大概有7个，开始接口数量小的时候保存还比较快，当维护的人多了保存就变得相当慢（大概有3分钟），有时还会奔溃，保存不成功。所以现在就把之前的模块拆成了项目，数度快了一些。现在数据库有480M多



kmdaimail@163.com
 
发件人： 高云
发送时间： 2016-08-22 15:39
收件人： thx/RAP
抄送： kmdai; Author
主题： Re: [thx/RAP] 保存数据很慢 (#597)
有多大呢？模块数、接口数、响应数据，多大的数量级呢？

**Comment by Bosn** [comment]
用的多的话，就自己部署个RAP吧。技术架构我确实做的没那么精细，后续我加了很多缓存，但是实体特别多的时候还是比较慢。

其实现在想想JSON => POJO的转换没有意义，应该以Action为单位直接存JSON到数据库就足够了。不然增加了指数级的不必要运算。 @nuysoft
