### ISSUE TITLE
css js等没有加载

### ISSUE THREAD

**Issue by sinoguo** [thx/RAP#598]
你好！
我checkout了release代码，eclipse运行，发现网站JS，样式等都没有，空白的，请问这是什么问题造成的，如何处理

**Comment by nuysoft** [comment]
作者用 IDEA 开发调试，eclipse 需要自己摸索。
@sinoguo 如果解决了，请记录下你的解决过程。

**Comment by Bosn** [comment]
contextPath的问题，配置下contextPath为根目录，即：`/`
