### ISSUE TITLE
校验时报错

### ISSUE THREAD

**Issue by chlesh** [thx/RAP#599]
![qq 20160729114512](https://cloud.githubusercontent.com/assets/14902329/17237208/0348f108-5582-11e6-910e-aae07f425866.png)
![qq 20160729114520](https://cloud.githubusercontent.com/assets/14902329/17237218/167408a8-5582-11e6-869b-7d71895b974c.png)
看异常信息，js的路径根本没有拼对，少了几个分隔号

**Comment by k19421** [comment]
#412 
#600

**Comment by Bosn** [comment]
检查环境和系统根路径，从错误信息来看没有正确找到mock-min.js文件导致报错。具体搜下mock-min.js。
