### ISSUE TITLE
数据库表字段类型定义错误

### ISSUE THREAD

**Issue by ansiz** [thx/RAP#601]
ROOT/WEB-INF/classes/database/initialize.sql
中第521行CREATE TABLE tb_rule中的update_time的默认值NOW()在mariadb中已经不能使用了
是否应该改为update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

**Comment by Bosn** [comment]
mariadb不能使用。。。只是RAP明确写了，要求用MySQL啊。
不过感谢亲的经验分享。。。。。
