### ISSUE TITLE
返回的json数据里掺杂了一些js函数

### ISSUE THREAD

**Issue by kingofglory** [thx/RAP#602]
在官方创建api链接：http://rap.taobao.org/mockjs/5971/www.ruika.com?req_number=1&req_page=1。返回的json数据里掺杂了一些js函数，这是什么情况。下面是部分返回数据：
{"code":0,"code":0,"msg":"success","data":{"compose":"compose","goods":{"goods_list|10":[{"goods_price":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(23,23,23,23,23,23,23,23,23,23)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54350';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"compose_tag":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(true,true,true,true,true,true,true,true,true,true)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54351';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_pic":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\',\'thumb_pic_url\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54352';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_id":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54353';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_name":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54354';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}]},"token":"token","banner":{"banner_list|4":[{"banner_type":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1,1,1,1)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54355';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"banner_title":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'banner_title\',\'banner_title\',\'banner_title\',\'banner_title\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54356';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"banner_pic":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'banner_pic_url\',\'banner_pic_url\',\'banner_pic_url\',\'banner_pic_url\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54357';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"type":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1,1,1,1)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54358';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}],"banner_number":4}},"data":{"banner":{"banner_list|4":[{"banner_title":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'banner_title\',\'banner_title\',\'banner_title\',\'banner_title\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54359';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"banner_type":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1,1,1,1)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54360';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"type":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1,1,1,1)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54361';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"banner_pic":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'https:\/\/aecpm.alicdn.com\/simba\/img\/TB1GUoAKXXXXXbJXXXXSutbFXXX.jpg\',\'https:\/\/aecpm.alicdn.com\/simba\/img\/TB1_MBGKFXXXXa2aXXXSutbFXXX.jpg\',\'https:\/\/aecpm.alicdn.com\/simba\/img\/TB1vQ55KVXXXXatXVXXSutbFXXX.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54362';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}],"banner_number":4},"compose":"compose","goods":{"goods_list|10":[{"goods_id":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111,1111111)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54363';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_price":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(23,23,23,23,23,23,23,23,23,23)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54364';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"compose_tag":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(true,true,true,true,true,true,true,true,true,true)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54365';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_pic":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\',\'https:\/\/img.alicdn.com\/tps\/TB1LLhELXXXXXbUXFXXXXXXXXXX-520-280.jpg\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54366';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"goods_name":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\',\'goods_name\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '54367';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}]},"token":"token"},"msg":"success"}

**Comment by xinglie** [comment]
正常的，这是mock语法 ，并不是json对象，详细可以看这里：http://mockjs.com/examples.html#Function

返回的这个类json对象需要Mock解析转换的，Mock看这里https://github.com/nuysoft/Mock

**Comment by kingofglory** [comment]
@xinglie 我用的安卓，没办法使用你上面的链接库。想请教下安卓下有没有相关的解析库？

**Comment by kingofglory** [comment]
@xinglie 我觉得没必要把这个解析抛给客户端，服务端完全可以透明化，直接给客户端返回json就可以了，这样不合常理。我要用这个接口就是图个方便，结果还得学一门解析。

**Comment by xinglie** [comment]
@kingofglory 如果你需要服务端处理好的数据，可以直接使用
`http://rap.taobao.org/mockjsdata/5971/www.ruika.com?req_number=1&req_page=1`
就是把/mockjs/换成/mockjsdata/

另外解析放客户端我觉得主要是有以下2个原因吧
1. 传输的数据量小，因为只传输规则不传递数据，所以量不大
2. 在客户端根据规则生成数据，不占用服务端资源

**Comment by xinglie** [comment]
@kingofglory  https://github.com/thx/RAP/wiki/user_manual_cn#%E6%9C%89%E5%8A%9E%E6%B3%95%E8%AE%A9rap%E6%9C%8D%E5%8A%A1%E7%9B%B4%E6%8E%A5%E8%BF%94%E5%9B%9Emockjs%E6%95%B0%E6%8D%AE%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AFmockjs%E6%A8%A1%E6%9D%BF%E5%90%97%EF%BC%9F  文档里说到了如何传递数据而非规则，也列出了3点为什么这样做的原因，建议多看下文档吧

**Comment by kingofglory** [comment]
感谢@xinglie的耐心回答，问题解决方法如上面所述。
