### ISSUE TITLE
【Android 与 Ios】客户端应用是不能访问这个接口的？

### ISSUE THREAD

**Issue by linapex** [thx/RAP#603]
如果我们在RAP定义好接口，Android客户端与Ios端要访问怎么办？有什么方法吗？

**Comment by jdpxiaoming** [comment]
仔细看文档把骚年!

**Comment by noseew** [comment]
我也不会，也想问这个问题

**Comment by k19421** [comment]
我们这边处理这个问题是这么处理：
由后台访问RAP，然后把RAP的结果返回给前台

**Comment by TechQuery** [comment]
@noseew @k19421 
https://github.com/thx/RAP/issues/602#issuecomment-237115153

**Comment by k19421** [comment]
@TechQuery 
由前端ios或者android直接请求后台再由后台转发RAP结果
这样子当后台的接口开发完成后部署上去前端就可以无感知的访问到真实的数据接口了
因为对后端熟悉，所以我选择由后端来处理这一块的逻辑

**Comment by Bosn** [comment]
用mockjsdata接口直接访问mock数据就可以了哦

**Comment by Bosn** [comment]
具体用户手册搜下`mockjsdata`
