### ISSUE TITLE
新用户注册_提示正则匹配模式错误_无法正常注册

### ISSUE THREAD

**Issue by wuka77** [thx/RAP#610]
**步骤：**
1.注册
2.按照规则填写用户名、密码等信息，比如密码填写：abc123

**预期：**
注册成功

**实际：**
1.点击注册，页面被刷新，注册失败
2.控制台报错
错误如下：
无法检查<input pattern='[a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,4}'>因为模式不是有效的正则表达式：invalid identity escape in regular expression

**Comment by nuysoft** [comment]
未复现。
确认字符中没有不可见字符？

**Comment by Bosn** [comment]
麻烦用个不一样但类似的注册信息，来试试是否成功，如果不成，麻烦给出具体填写的截图，方便排查
