### ISSUE TITLE
关于REST URL的语义问题

### ISSUE THREAD

**Issue by magixsource** [thx/RAP#614]
情况是这样子的，我这里有个资源实体，ID是个字符串，不是数字。获取该资源我是这样写的：
请求类型 get
请求Url  /dict/kind/{id}
这个意思是将中括号中的值当成id，方便后面mock返回。

可是我在另一个模块，同样为了获取资源user时，也这样写：
请求类型 get
请求Url /user/{userId}

然后RAP报no matched action，我不知道为什么前面一个模块可以这样写，而后面的则报错。

为了不停下工作，我不得不把url改成/user/:userId，但是这个userID却仅能支持数字。
麻烦问下各位，我想让URL支持字符串，怎么做？谢谢。

**Comment by zhanglongqiang** [comment]
请问这种url中带变量的定义在RAP的哪里有说明吗？

**Comment by Bosn** [comment]
暂时不支持亲所说的match pattern哦，目前只提供:id数字及正则表达式匹配两种方式。

MOCK数据。。。不是开发，不要花费过多的时间在MOCK数据的逻辑编程上。

**Comment by magixsource** [comment]
看了源代码，:id只是简单粗暴地替换成1，而更多的场景都只能依靠正则表达式去匹配。
