### ISSUE TITLE
API4：校验真实数据的正确性, 接口无效

### ISSUE THREAD

**Issue by df007df** [thx/RAP#617]
host/validate/2/api/m/poi/near?json=

接口相对地址： api/m/poi/near

`
{
    "result": {
        "left": [
            {
                "type": "LOST",
                "property": "isOk",
                "namespace": "obj"
            },
            {
                "type": "LOST",
                "property": "errMsg",
                "namespace": "obj"
            }
        ],
        "right": [
            {
                "type": "LOST",
                "property": "success",
                "namespace": "obj"
            },
            {
                "type": "LOST",
                "property": "data",
                "namespace": "obj"
            }
        ]
    },
    "resultStr": "参数 obj.isOk 缺失\n参数 obj.errMsg 缺失\n参数 obj.success 未在接口文档中未定义。\n参数 obj.data 未在接口文档中未定义。"
}

`

无论修改项目ID ，还是 接口相对地址 都报这错误。此接口是否能用？

**Comment by Bosn** [comment]
贴详细点，你的接口文档是怎么写的。

**Comment by nuysoft** [comment]
提供更多信息后再打开。
