### ISSUE TITLE
RAP部署后访问报错

### ISSUE THREAD

**Issue by LieMengDade** [thx/RAP#619]
昨天刚部署完还没来得及测试就下班了，今天打开各种软甲和服务后，访问：

> localhost:22238(我改了tomcat8080的端口，改成22238)
发现有异常
具体如下：
`HTTP Status 500 - Unable to instantiate Action, com.taobao.rigel.rap.organization.web.action.OrganizationAction, defined for 'index' in namespace '/org'Failed to convert property value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr': no matching editors or conversion strategy found`
请问是我环境的问题，还是其他原因，怎么解决

**Comment by LieMengDade** [comment]
详细信息如下：
`type Exception report

message Unable to instantiate Action, com.taobao.rigel.rap.organization.web.action.OrganizationAction, defined for 'index' in namespace '/org'Failed to convert property value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr': no matching editors or conversion strategy found

description The server encountered an internal error that prevented it from fulfilling this request.

exception

Unable to instantiate Action, com.taobao.rigel.rap.organization.web.action.OrganizationAction,  defined for 'index' in namespace '/org'Failed to convert property value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr': no matching editors or conversion strategy found - action - file:/D:/ide/apache-tomcat-8.0.9/webapps/ROOT/WEB-INF/classes/com/taobao/rigel/rap/organization/web/action/struts.xml:9:117
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:314)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:395)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:194)
	org.apache.struts2.impl.StrutsActionProxy.prepare(StrutsActionProxy.java:63)
	org.apache.struts2.impl.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:37)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:58)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:554)
	org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.taobao.rigel.rap.common.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:118)
	org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	com.taobao.rigel.rap.common.filter.AuthCheckFilter.doFilter(AuthCheckFilter.java:122)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	com.alibaba.buc.sso.client.filter.SSOFilter.doFilter(SSOFilter.java:96)
root cause

org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr': no matching editors or conversion strategy found
	org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:591)
	org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:603)
	org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:204)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1527)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1486)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	com.opensymphony.xwork2.spring.SpringObjectFactory.autoWireBean(SpringObjectFactory.java:218)
	com.opensymphony.xwork2.spring.SpringObjectFactory.buildBean(SpringObjectFactory.java:198)
	com.opensymphony.xwork2.spring.SpringObjectFactory.buildBean(SpringObjectFactory.java:164)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:178)
	com.opensymphony.xwork2.factory.DefaultActionFactory.buildAction(DefaultActionFactory.java:22)
	com.opensymphony.xwork2.ObjectFactory.buildAction(ObjectFactory.java:148)
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:295)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:395)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:194)
	org.apache.struts2.impl.StrutsActionProxy.prepare(StrutsActionProxy.java:63)
	org.apache.struts2.impl.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:37)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:58)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:554)
	org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.taobao.rigel.rap.common.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:118)
	org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	com.taobao.rigel.rap.common.filter.AuthCheckFilter.doFilter(AuthCheckFilter.java:122)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	com.alibaba.buc.sso.client.filter.SSOFilter.doFilter(SSOFilter.java:96)
root cause

java.lang.IllegalStateException: Cannot convert value of type [com.sun.proxy.$Proxy44 implementing com.taobao.rigel.rap.account.service.AccountMgr,org.springframework.aop.SpringProxy,org.springframework.aop.framework.Advised] to required type [com.taobao.rigel.rap.account.service.AccountMgr] for property 'accountMgr': no matching editors or conversion strategy found
	org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:302)
	org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:576)
	org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:603)
	org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:204)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1527)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1486)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	com.opensymphony.xwork2.spring.SpringObjectFactory.autoWireBean(SpringObjectFactory.java:218)
	com.opensymphony.xwork2.spring.SpringObjectFactory.buildBean(SpringObjectFactory.java:198)
	com.opensymphony.xwork2.spring.SpringObjectFactory.buildBean(SpringObjectFactory.java:164)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:178)
	com.opensymphony.xwork2.factory.DefaultActionFactory.buildAction(DefaultActionFactory.java:22)
	com.opensymphony.xwork2.ObjectFactory.buildAction(ObjectFactory.java:148)
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:295)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:395)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:194)
	org.apache.struts2.impl.StrutsActionProxy.prepare(StrutsActionProxy.java:63)
	org.apache.struts2.impl.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:37)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:58)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:554)
	org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.taobao.rigel.rap.common.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:118)
	org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	com.taobao.rigel.rap.common.filter.AuthCheckFilter.doFilter(AuthCheckFilter.java:122)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	com.alibaba.buc.sso.client.filter.SSOFilter.doFilter(SSOFilter.java:96)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.9 logs.

`

**Comment by MonsterWang** [comment]
只用Nginx无法部署？

**Comment by nuysoft** [comment]
@LieMengDade 参照这套版本部署：
* apache-tomcat 8.0.33
* redis 3.2.0
* mysql 5.6.21

如果不在这个范围内，需要自行解决。
