### ISSUE TITLE
数据库连接无法关闭,日志线程无法关闭(应该是这样翻译的)

### ISSUE THREAD

**Issue by liutaoyxz** [thx/RAP#624]
我直接用的war启动,但是tomcat老是无法正常启动项目,应该是说数据库连接无法关闭,还有日志线程无法关闭可能引起内存泄漏然后项目就不启动了.这是怎么回事啊

**Comment by liutaoyxz** [comment]
15:27:41.497 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.
RapServletContextListener - RAP Server initializing...
15:27:41.498 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.
RapServletContextListener - Initializing Jedis Server...
11-Aug-2016 15:27:41.550 SEVERE [localhost-startStop-1] org.apache.catalina.core
.StandardContext.startInternal One or more listeners failed to start. Full detai
ls will be found in the appropriate container log file
11-Aug-2016 15:27:41.551 SEVERE [localhost-startStop-1] org.apache.catalina.core
.StandardContext.startInternal Context [] startup failed due to previous errors
15:27:41.560 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.
RapServletContextListener - Context destroyed.
11-Aug-2016 15:27:41.574 WARNING [localhost-startStop-1] org.apache.catalina.loa
der.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registe
red the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the
 web application was stopped. To prevent a memory leak, the JDBC Driver has been
 forcibly unregistered.
11-Aug-2016 15:27:41.575 WARNING [localhost-startStop-1] org.apache.catalina.loa
der.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appe
ars to have started a thread named [Log4j2-Log4j2Scheduled-1] but has failed to
stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNano
s(Unknown Source)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown
Source)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown
Source)
 java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.lang.Thread.run(Unknown Source)
11-Aug-2016 15:27:41.576 WARNING [localhost-startStop-1] org.apache.catalina.loa
der.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appe
ars to have started a thread named [MySQL Statement Cancellation Timer] but has
failed to stop it. This is very likely to create a memory leak. Stack trace of t
hread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:503)
 java.util.TimerThread.mainLoop(Unknown Source)
 java.util.TimerThread.run(Unknown Source)
11-Aug-2016 15:27:41.576 WARNING [localhost-startStop-1] org.apache.catalina.loa
der.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appe
ars to have started a thread named [commons-pool-EvictionTimer] but has failed t
o stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Unknown Source)
 java.util.TimerThread.run(Unknown Source)
11-Aug-2016 15:27:41.582 INFO [localhost-startStop-1] org.apache.catalina.startu
p.HostConfig.deployDirectory Deployment of web application directory D:\tomcat\a
pache-tomcat-8.5.4\webapps\ROOT has finished in 9,403 ms
11-Aug-2016 15:27:41.585 INFO [main] org.apache.coyote.AbstractProtocol.start St
arting ProtocolHandler [http-nio-8880]
11-Aug-2016 15:27:41.594 INFO [main] org.apache.coyote.AbstractProtocol.start St
arting ProtocolHandler [ajp-nio-8809]
11-Aug-2016 15:27:41.597 INFO [main] org.apache.catalina.startup.Catalina.start
Server startup in 9460 ms


应该是这样的

**Comment by lordpeas** [comment]
同上

**Comment by 18458155220** [comment]
同上，请问如何解决

**Comment by Bosn** [comment]
tomcat配置问题，把RAP项目去掉，来确认下是否是RAP导致。
