### ISSUE TITLE
导出word功能  为何导出来的是HTML

### ISSUE THREAD

**Issue by cxXavier** [thx/RAP#627]
rap   更多功能 --> 导出word --->导出来的是HTML   这样是对的吗？

**Comment by songhlc** [comment]
导出的html还丢失了 请求的type

**Comment by nuysoft** [comment]
功能缺陷。先当作导出 HTML 使用吧。

**Comment by cxXavier** [comment]
其实不算是bug  导出来的html   把文件 .html后缀改成 .doc就可以了

**Comment by TechQuery** [comment]
@cxXavier M$ Word 在 Office 97/2K 时代就能直接打开 HTML 吧？

**Comment by Bosn** [comment]
最早为了方便实现，就是导出html内容，文件名改为.doc就可以被识别。但是在Mac系统里这样不支持，所以干脆直接导出.html文件了。
