### ISSUE TITLE
RAP很烂，或者说ALI的开放出来的产品很烂，大家散了吧。

### ISSUE THREAD

**Issue by magixsource** [thx/RAP#628]
RT

**Comment by codering** [comment]
又是一个无人维护？

**Comment by magixsource** [comment]
你看我做的这个实验，说阿里的坏话，两天都没有一个官方的人来回复我。明显是“又”一个了。

**Comment by njleonzhang** [comment]
阿里做开源确实老师烂尾啊。东西都挺好的，做着做着没人了。

**Comment by mgcnrx11** [comment]
用户比维护者还活跃

**Comment by boafantasy** [comment]
这个项目的维护者不是离开阿里，开健身馆去了嘛。。。

**Comment by nuysoft** [comment]
接下来一段时间我会投入大部分精力到 RAP 的更新、维护和答疑上。

开源项目最初都是开发者投入业余精力和时间进行维护的，如果对你有用有启发，但是作者不维护了，可以自己 fork 分支继续啊。

**Comment by huangjunGo** [comment]
比如dubbo，要考虑商业利益啊
