### ISSUE TITLE
希望能加入跨域配置

### ISSUE THREAD

**Issue by ahcheqiu** [thx/RAP#629]
希望能加入配置跨域时OPTIONS方法返回的Access-Control-Allow-Headers和Access-Control-Allow-Origin的功能

**Comment by nuysoft** [comment]
现在发送请求走的 JSONP 已经支持跨域，你提的跨域访问用在什么场景呢？

**Comment by ahcheqiu** [comment]
不使用jsonp的情况下，使用preflight的OPTIONS请求
浏览器会自动在原请求之前发送一个OPTIONS请求，然后根据response header决定是否允许跨域。
详细点的可以看这个https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
预请求部分

其实我的意思就是希望能够自己配置返回时的HTTP header

**Comment by nuysoft** [comment]
## CORS
理解你说的 CROS，需要在服务端配置允许的域名列表。作为公开服务，无法预期请求来自什么域名，而一律配置成 `*` 又会带来很大的安全隐患。所以不会考虑增加对 CROS 的支持。

## 响应头
RAP 只会提供 JSON 一种响应格式，目前看不到自定义响应头的需求场景。

如果你有觉得很必要的自定义响应头需求，请补充在后面。

**Comment by ahcheqiu** [comment]
目前用到的要求设置header主要是在RESTful里面
1、资源重定向时设置location
2、设置Accept的JSON格式版本号
做为一个mock server的话这2个其实可以忽略，所以用到的不多
主要是目前前端没有支持jsonp，所以提这样一个issue

安全方面的话我想不出有什么问题，确实把允许域名设置成*有隐患，但是一个mock-server配置正确的话应该不会有问题的吧。虽然我现在想不出来，但是我觉得肯定是有办法解决怎样不将允许域名配置为*的
而且JSONP是只支持GET请求的，那么你们提供的选择请求的METHOD就毫无意义了。

那既然已经确定不考虑加入CROS的支持，那只能说RAP对RESTful完全不支持了
RAP确实可以，但是不能符合我的需求，只能去找其他东西代替了，谢谢解答

**Comment by TechQuery** [comment]
@nuysoft 

**RAP** 只是个**模拟接口**的服务，又不**写数据库**，能有什么**安全隐患**？

**Comment by nuysoft** [comment]
@TechQuery 不是这方面的专家，不在这里展开讨论。只提我了解的：
1. 通配符 `*` 很难通过安全审查；
2. 除了**写数据库**，常见的安全问题还有 cookie 劫持。

**Comment by TechQuery** [comment]
@nuysoft **模拟接口**和 **Cookie 劫持**又有什么关系……？模拟一下都要这么复杂吗？

**Comment by Veitor** [comment]
我觉得这个问题还是有必要的，本打算和我们公司前端用RAP的，结果对angular不支持，也不能配置Access-Control-Allow-Origin之类的
