### ISSUE TITLE
删除接口功能无效

### ISSUE THREAD

**Issue by tcsthyc** [thx/RAP#631]
v0.14.2beta，删除接口后，无论快存还是慢存都无效，接口依然存在。
update：
删一次就多一个一模一样的接口，删了4次，不仅没有删除，还复制了4个。

**Comment by nuysoft** [comment]
未直接复现。
有必然复现的步骤吗？是否有和其他人一起协同修改？

**Comment by nuysoft** [comment]
提供更多信息后再打开。
