### ISSUE TITLE
保存以后多了无效字段

### ISSUE THREAD

**Issue by tcsthyc** [thx/RAP#632]
v0.14.2 beta
编辑的时候是这样的
![1](https://img.alicdn.com/tps/TB1U4PhLpXXXXcwXVXXXXXXXXXX-660-345.png)
保存以后成了这样：
![2](https://img.alicdn.com/tps/TB1YsPfLpXXXXaCXpXXXXXXXXXX-482-847.png)

**Comment by nuysoft** [comment]
@tcsthyc  是用的线上服务还是自己部署的呢？

**Comment by Bosn** [comment]
吓死宝宝了，稳定复现么，请贴出详细技术信息。。。没后文的issue关闭了哦
