### ISSUE TITLE
使用webpack+ vue 如何引入 Rap

### ISSUE THREAD

**Issue by wulmm** [thx/RAP#637]
我在index.html中引入但是不好使，请问该如何使用？

**Comment by nuysoft** [comment]
请用 <http://rap.taobao.org/> 上的服务建一个可复现的场景 <http://jsfiddle.net/>

**Comment by nuysoft** [comment]
#636

**Comment by nuysoft** [comment]
超时关闭。
请提供可复现场景后再打开。

**Comment by zhuobinggang** [comment]
个人愚见。webpack打包之后build.js内部对index是不可见的，同样你在index里引入rap插件，是没办法作用到内部ajax上的。我想到的解决方法只有：在index里引入jquery和rap插件，然后提供一个全局mock函数，供build.js内部调用(一个好的方案是，在ajax的error方法里调用该mock函数，这样产品上线后也不用改)。
