### ISSUE TITLE
Could not display my project

### ISSUE THREAD

**Issue by nbgyf** [thx/RAP#641]
Problem 1:
The index page could not display my project after I create a project.
Cause:
The logo_url column is null in the tb_corporation when I create my team.
Solution:
Add a logo url in the new team page.

The index page may display my project after I insert any data to logo_url column.

Problem 2:
The my team page could not display my product line  after I log in again.

**Comment by nuysoft** [comment]
@nbgyf 从你的问题描述看，应该是自己部署了一套 RAP。

> The index page could not display my project after I create a project.

字段 `logo_url` 目前都是 `null`。你部署的版本是多少？

> The my team page could not display my product line after I log in again.

数据库中的记录正常吗？

**Comment by nbgyf** [comment]
我部署的版本是v0.14.1  beta。

**Comment by nbgyf** [comment]
目前当我随意输入任意值到logo_url column，首页可以显示我已建项目；
但是当点击进入我的团队时，已创建的【产品线】却无法显示，数据库中能够查到已创建的产品线及分组。

**Comment by nuysoft** [comment]
@nbgyf 浏览器控制台和 Tomcat 有相关的报错吗？有的话贴一下。

**Comment by nuysoft** [comment]
参考 #557 看能否解决你的问题。

**Comment by Bosn** [comment]
Use the newest version of RAP will resolve your issue.
It seems that your problem caused by Redis Cache module didn't handle the data result correctly.
After you create your team instance, cache doesn't flushed... so....

I'd fixed this problem in the newest version.
