### ISSUE TITLE
后端渲染的页面，少个填模板地址的字段

### ISSUE THREAD

**Issue by cuidingfeng** [thx/RAP#643]
我们想做前后端分离，前端和后端对接的就有两种请求了，一种是后端渲染的页面，一种是ajax请求。
现在RAP的功能，对ajax请求没有任何问题，但是对后端渲染的页面，少个填模板地址的字段。建议能多加这么个“模板路径”字段。

**Comment by nuysoft** [comment]
『模板地址』的模板是指页面？

**Comment by Bosn** [comment]
补充信息再reopen
