### ISSUE TITLE
服务是否只能部署到本地

### ISSUE THREAD

**Issue by gitdust** [thx/RAP#644]
1.公司服务器部署了 RAP，http://ip:port
2.我们前端项目用 express 等启动了服务器并在 RAP 中 mock 一个API，“请求Url”为 /path/to/api
结果
在 js 里面 ajax 请求 http://ip:port/path/to/api 不成功，改如何解决

**Comment by nuysoft** [comment]
参考 [引入插件](https://github.com/thx/RAP/wiki/user_manual_cn#%E5%BC%95%E5%85%A5%E6%8F%92%E4%BB%B6) 检查下 jQuery、RAP 的引用顺序是否正确？
