### ISSUE TITLE
接口无法连接

### ISSUE THREAD

**Issue by xiaoyu07** [thx/RAP#645]
![46084efe-6f99-11e6-918c-2f405244d5ee](https://cloud.githubusercontent.com/assets/20808736/18153271/f4d31d2a-702e-11e6-863b-5fa07a5d2b77.png)

**Comment by nuysoft** [comment]
@xiaoyu07  贴下导出的 JSON 代码。

**Comment by Bosn** [comment]
补充信息再reopen
