### ISSUE TITLE
模块、页面和接口参数的排序问题

### ISSUE THREAD

**Issue by wanglvchun** [thx/RAP#647]
现在的模块、页面和接口参数的顺序是按照名字的字符顺序来排序，对于对接口协议有编号和以及参数顺序有要求的接口来说，这个按字符顺序排序非常令人蛋疼，建议直接按照建立的先后顺序排序就很好。
另外一点，在每次新建一个参数的时候，新建的参数框框自动排在第一个，非常不符合正常建立由上及下的顺序习惯。
自己通过修改rap.js中的排序规则，解决了以上的问题，希望后续版本能够考虑下顺序问题

**Comment by nuysoft** [comment]
亲 分享下解决方案

**Comment by Bosn** [comment]
众口难调，有的要按照自己的顺序，有的按照先后顺序。
RAP是阿里员工业余时间搞的应用，这个非核心功能不在产品规划重点，亲感兴趣可以自己实现哦
