### ISSUE TITLE
用户权限问题

### ISSUE THREAD

**Issue by wangyining1992** [thx/RAP#650]
1、超级管理员admin创建一个团队，并在该团队下建了项目A和用户a;
2、同团队下的另一个用户a建立了另一个项目B；
超管admin在主页看不到项目B是否正常？
超管admin对项目B无修改权限是否正常？（用户手册中描述“项目所在团队的管理员对项目有写权限”）

谢谢！

**Comment by nuysoft** [comment]
**首页非常明确的写明了『我的项目』和『我加入的项目』，并不是『我能看到的所有项目』。**

请点击顶部导航『团队』浏览。
