### ISSUE TITLE
mock查看的 json  上下一样啊

### ISSUE THREAD

**Issue by ganmk** [thx/RAP#655]
![1](https://cloud.githubusercontent.com/assets/6767533/18374965/262c6024-7684-11e6-9190-2c5d0ceee75f.png)
![2](https://cloud.githubusercontent.com/assets/6767533/18374966/262c8f4a-7684-11e6-9238-c294afaf331d.png)

**Comment by nuysoft** [comment]
`cityCode` 也一样吗？

**Comment by Bosn** [comment]
你不写规则当然一样了，比如你把数组变量名改为：arr|2，类似的，你有了规则，规则和值才不一样。

你规则就是单纯的固定key/value，值当然没变化。
