### ISSUE TITLE
http://rapapi.net/  域名过期了啊

### ISSUE THREAD

**Issue by lxlneo** [thx/RAP#659]
域名过期了啊~ 谁在维护啊~

**Comment by nuysoft** [comment]
@Bosn 这个域名是指向 rap.taobao.org 的吗？

**Comment by Bosn** [comment]
因为阿里这边规定必须用rap.taobao.org，不让用自己的域名，所以rapapi.netd对外后来都不宣传了。统一用rap.taobao.org就可以
