### ISSUE TITLE
接口定义问题：POST,PUT方法请求body参数如何定义呢？

### ISSUE THREAD

**Issue by zhanglongqiang** [thx/RAP#663]
使用现有的请求参数定义方式，mock时，参数都在url中传递

**Comment by Bosn** [comment]
从定义角度，你写GET就表示在参数中，选择POST就是在BODY中

对于MOCK数据，MOCK服务器是不区分GET/POST的，只要是过来的参数都会被解析，然后识别和处理。所以不用担心这个问题。
