### ISSUE TITLE
团队以及邮件问题

### ISSUE THREAD

**Issue by shang7053** [thx/RAP#664]
团队想要删除，页面没有这个功能，是需要从数据库删除？邮件通知功能什么时候能出？

**Comment by Bosn** [comment]
我也想知道什么时候出....  我现在创业了，所以新功能开发被暂缓。
亲们可以自己fork一下自己实现，其实并不难。

都等着作者搞全部功能，就失去开源意义啦

**Comment by shang7053** [comment]
@Bosn 看来只能这样的，谢谢
