### ISSUE TITLE
关于跨域问题提一个小建议

### ISSUE THREAD

**Issue by ahcheqiu** [thx/RAP#668]
之前提过一个 #629 因为担心安全原因被关了。
可以看出来大家还是很期待RAP能做好的，但是以目前的情况还是使用限制很多。

既然开源了，那么可以这样
加入这个功能，但是线上为大家提供的版本不开启。
自己下载了以后去部署的可以允许开启，但是后果由使用者自己承担。
这样既能避免你担心的安全问题，也可以让有需求的人有解决办法。

或者把提供跨域功能作为一项付费功能，用收费的方式作为出现安全问题风险的补偿。

**Comment by Bosn** [comment]
安全问题没那么简单哈，对跨域或功能有特别需求自己部署个RAP就好了，线上的RAP，安全是底线。
让用户使用前签什么协议不具备可行性。
