### ISSUE TITLE
特殊参数会照成url链接 “&” 变成“”

### ISSUE THREAD

**Issue by LeiHen** [thx/RAP#671]
![image](https://cloud.githubusercontent.com/assets/4099706/18907644/ffcd2ea2-859e-11e6-9bcb-bb7bb8f900f9.png)

当- 和 编码一起出现是 就有问题
例如
&timestamp=2016-07-18+15%3A06%3A48
变成
xtimestamp=2016-07-18+15%3A06%3A48

也试过没编码的
&timestamp=2016-07-18 15:06:48
也不行 也是变成
xtimestamp=2016-07-18 15:06:48

具体可看图

求解决:sob:

**Comment by LeiHen** [comment]
估计是后台编码的问题，把“空格“当成“+” 用的是很老的编码，“空格”应该编码成“%20” ，这就没问题，这样就能获取后台返回来的数据。
虽然现在能获取到后台放回来的数据 ， 但是 那个变x 的问题还是没有解决

**Comment by Bosn** [comment]
请求链接的参数不要写在URL里，接口定义的是格式，不是具体参数值。

参数值信息可以放在请求参数列表里。

**Comment by LeiHen** [comment]
后端提供过来的  请求地址 就是带参数的
