### ISSUE TITLE
数据模型是array<object>的时候，$order()数据出错,求解，有图。

### ISSUE THREAD

**Issue by zyj1022** [thx/RAP#672]
如题，新建数据模型格式如预览图
![11](https://cloud.githubusercontent.com/assets/641885/18947217/bc4c3026-8664-11e6-802b-8625831542d5.png)

这个时候，到控制台数据请求是正确的，可是直接访问请求数据的链接是错误的～！！！

<img width="880" alt="22" src="https://cloud.githubusercontent.com/assets/641885/18947267/eeb5fc9a-8664-11e6-8ccc-4235a1b455a4.png">

如上图所示，这个错误是bug吧，测试多次都这样啊。

**Comment by Bosn** [comment]
老生常谈。。。。  其实没错，因为输出的本来就不是JSON
而是JavaScript字符串，因为有函数。

自己试一试....

**Comment by zyj1022** [comment]
谢谢解答，还有不明白的，请指教，
1、我在数据模型处用了函数就不能正常访问请求链接拿到json字符串了？
2、如果1成立，那么意味着我的json格式就需要调整了,**或者怎么才能得到我想要的json字符串呢？**

再上个图吧。
![000](https://cloud.githubusercontent.com/assets/641885/18978741/2c31a75c-86f8-11e6-8bb8-26d3b835afb5.png)
