### ISSUE TITLE
注册时Chrome报出检验Email的正则表达式错误

### ISSUE THREAD

**Issue by fs523577192** [thx/RAP#674]
URL：/account/doRegister.do
浏览器：Chrome 53.0.2785.116 m
浏览器User Agent：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

表单参数：
账号：yupingwu
名字：伍裕平
Email：448445223@qq.com

点击【提交】按钮，在Email字段提示“请与所请求的格式保持一致”
Console报错：
Pattern attribute value [a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2.4} is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2.4}/: Invalid escape

建议检查[这里](https://github.com/thx/RAP/blob/release/src/main/webapp/account/register.vm#L38)和[这里](https://github.com/thx/RAP/blob/release/src/main/webapp/account/myAccount.vm#L43)

**Comment by fs523577192** [comment]
应该是需要去掉"@"前面的"\"

**Comment by nuysoft** [comment]
#610
