### ISSUE TITLE
注册不成功，提示信息莫名其妙

### ISSUE THREAD

**Issue by pod4g** [thx/RAP#675]
其实早在今年年初，有人推荐RAP，然后我看了一下，注册，但是一直不成功，时间太长了，具体记不清什么原因了。然后今天又看到一篇文章介绍RAP，然后就又注册了，但是还是注册不成功。我简直是服了你们。

注意：我帐号字段改成`pod4g_`也不能成功。

![4367e499-c7df-404c-8bf5-08463eb72f72](https://cloud.githubusercontent.com/assets/12889190/19210016/87a348dc-8d49-11e6-8204-039b947c6a2f.png)

**Comment by TechQuery** [comment]
Email 最后多了个空格？

**Comment by pod4g** [comment]
@TechQuery 并不是空格的问题

**Comment by ChiHoc** [comment]
![image](https://cloud.githubusercontent.com/assets/4478983/19295886/27ce9762-906a-11e6-9910-1eaf3d6bd9fd.png)

**Comment by nuysoft** [comment]
#610
