### ISSUE TITLE
搭建的RAP访问超慢

### ISSUE THREAD

**Issue by FlyingSailor** [thx/RAP#677]
访问内页很慢，是否需要配置什么信息？

**Comment by nuysoft** [comment]
检查下浏览器控制台，看看是哪些请求拖慢了速度，是请求 RAP 服务慢，还是请求其他静态资源慢？

**Comment by FlyingSailor** [comment]
的确有一个统计的网址（http://v1.cnzz.com）占着速度，给去掉了，现在好了，非常感谢
