### ISSUE TITLE
希望能增强后台接口测试功能

### ISSUE THREAD

**Issue by zj198547** [thx/RAP#686]
前期编辑好文档后可以生成针对前端接口的mock，等到后端接口实现后，如何能在mock数据与真实接口调用的数据更好的衔接呢，类似swagger，可以直接调用真实接口

**Comment by nuysoft** [comment]
#685 以前是支持的，但是有安全隐患。
在 RAP 系统中，访问第三方真实接口可能会返回带有攻击性的脚本或者内容，所以这个功能已经关闭。
如果需要，需要自己修改了，并且对可能潜在的攻击负责。
