### ISSUE TITLE
请问使用vue-resource如何接入Mock 插件？

### ISSUE THREAD

**Issue by IssaTan1990** [thx/RAP#688]
我看到之前有相同的issue，但是没有解决方案。
现在jsfiddle.net 已经是`HTTPS`的了，于是无法重现。
代码如下：

html:
```bash
<script src="https://npmcdn.com/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/vue.resource/1.0.3/vue-resource.min.js"></script>
<script src="http://rap.taobao.org/rap.plugin.js?projectId=7943"></script>
<div id="app">
    {{ message }}
</div>
```

javascirpt:
```bash
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }  
})
Vue.http.get('/getDefault').then((response) => {
  console.log(response)
  // success callback
}, (response) => {
  // error callback
});
```
我在JSBin 上做了个[链接](http://jsbin.com/yitohabola/1/edit?html,js,console,output)
按这样的设置，我在项目里拦截不了的。
直接使用MockJs 是可以拦截 `getDefault` 的请求，我看了下`createPluginScript.action`这个`js`，貌似只对`jQuery` ，`KISSY`， 和 `SeaJs` 做了处理？

**Comment by nuysoft** [comment]
> 貌似只对jQuery ，KISSY， 和 SeaJs 做了处理？
是的，默认只支持这些。

其他库需要自己重写发送请求的方法。覆盖方式参考对 jQuery、KISSY 的处理。

**Comment by IssaTan1990** [comment]
ok, 已自我处理

**Comment by chenming142** [comment]
已能处理么？求代码

**Comment by shuleihust** [comment]
vue-webpack中使用rap，返回的是带有function的字符串数据，怎么转换呢，求解决方案

**Comment by shuleihust** [comment]
如果遇到返回的数据中带有function的情况，在main.js中加上下面这段就好了：

Vue.http.interceptors.push((request, next) => {
  var url=request.url;
  var mockHost = 'http://' + RAP.getHost() + '/mockjsdata/' + RAP.getProjectId();
  var mockUrl = mockHost + url;
  request.url=mockUrl;
  next();
});
