### ISSUE TITLE
制造接口时能不能通过不同的json数据返回不同的数据。

### ISSUE THREAD

**Issue by hhskt1** [thx/RAP#692]
我们的接口地址都是一个，通过JSON的一个键值action的不同返回不同的数据。我再测试的时候发现，只有通过URL传递的参数可以在地址上面设置。通过application/json传输的data能够解析返回不同的数据吗。

**Comment by nuysoft** [comment]
可以，用自定义函数 + [根据请求参数来动态生成MockJS模板](https://github.com/thx/RAP/wiki/user_manual_cn#%E6%A0%B9%E6%8D%AE%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0%E6%9D%A5%E5%8A%A8%E6%80%81%E7%94%9F%E6%88%90mockjs%E6%A8%A1%E6%9D%BF) 实现。
