### ISSUE TITLE
页面 js 报错，邮箱验证问题 

### ISSUE THREAD

**Issue by DeadLion** [thx/RAP#699]
Pattern attribute value [a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,4} is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,4}/: Invalid escape

更改密码的时候会提示邮箱格式问题，注册独立页面的时候也会有同样的问题！

**Comment by nuysoft** [comment]
#610
