### ISSUE TITLE
什么时候给 redis 配上密码

### ISSUE THREAD

**Issue by yansheng723** [thx/RAP#703]
这个还是需要配的,否则有些坑.我已经把你这块改了. 你竟然 rigel 都不改...

**Comment by yansheng723** [comment]
String password = SystemConstant.getConfig("redis.password");
jedisPool = new JedisPool(poolConfig, host, port, 0, password);

**Comment by nuysoft** [comment]
> 你竟然 rigel 都不改...

什么意思？

**Comment by nuysoft** [comment]
#673

**Comment by herrdu** [comment]
我们需要在config.properties  进行配置吗？

**Comment by yansheng723** [comment]
我贴的是要改的代码.配置里要写"redis.password"的
