### ISSUE TITLE
部署出现部分html片段乱码，以及mock生成数据乱码问题

### ISSUE THREAD

**Issue by catalsdevelop** [thx/RAP#705]
jdk 1.8.0_112
redis 3.2.4
tomcat 8.0.38
maven 3.3.9

都是默认设置

部署和发布没有问题，但是遇到几个小问题
- 乱码问题，以下界面会乱码，最后一个连接，我刷新的话，也不会产生随机数据，都是这段乱码，同样的配置，在线上测试的时候就没问题
  1. ![](http://7xvcf8.com1.z0.glb.clouddn.com/luan1.PNG)
  2. ![](http://7xvcf8.com1.z0.glb.clouddn.com/luan2.PNG)
  3. ![](http://7xvcf8.com1.z0.glb.clouddn.com/luan3.PNG)
- 版本列表那里，我采用秒存的方式保存后，立刻打开的话， 获取不到刚才的信息，需要等一段时间，这个是不是异步存储在redis中的？因为我现在系统部署在虚拟机的容器中，所以我看到redis过一会才有数据记录进来

**Comment by nuysoft** [comment]
搜索 issues，参考之前的解决方案。
