### ISSUE TITLE
点击接口链接报错

### ISSUE THREAD

**Issue by MTTTM** [thx/RAP#709]
数据出不来，点击接口链接会直接出现报错页面

![image](https://cloud.githubusercontent.com/assets/8638001/19712537/58519fee-9b71-11e6-86b5-3ae91bdf9362.png)
![image](https://cloud.githubusercontent.com/assets/8638001/19712561/8a0d64be-9b71-11e6-8615-ff52d9a6a291.png)

![image](https://cloud.githubusercontent.com/assets/8638001/19712533/5185ebca-9b71-11e6-9d95-ca933af4eb5e.png)

**Comment by nuysoft** [comment]
打开你的项目看了，未复现。

**Comment by nuysoft** [comment]
有新进展再打开。

**Comment by lensh** [comment]
怎么关闭这个提示啊
