### ISSUE TITLE
post body data能被劫持到responsedata里么

### ISSUE THREAD

**Issue by hufangyuan** [thx/RAP#715]
post body data能被劫持到responsedata里么；
比如post body data 里面参数{orderNo：B0001}返回到responsedata中去{orderNo：B0001}

**Comment by nuysoft** [comment]
看文档去。

**Comment by liangjingyang** [comment]
貌似不支持 body里的参数, 只支持url params

**Comment by liangjingyang** [comment]
看了下源码, 应该是不支持 body里的:

**Comment by hufangyuan** [comment]
恩，看了下要是专门mock还是wiremock功能更全；如果想不改动源码的话只能后面做一层转接把body的值放到queryparams里面去了，谢谢你的回复。
