### ISSUE TITLE
关与支持简单测试的想法：

### ISSUE THREAD

**Issue by zhengheh** [thx/RAP#724]
1. 在线测试，在每个接口的请求界面，蓝色的 “请求” 按钮旁边加一个 新按钮 “请求实际服务”， 点击这个按钮，就会调用实际的接口， 就相当于 在web端，通过rap.plugin.js 以mode=0 (不拦截这个模式) 调用这个接口，这样方便利用rap.plugin.js 里的校验功能

2. 自动化测试
     * 在项目，模块，页面级别分别都加一个“测试实际接口” ，用于自动触发所有接口
     * 把 现有基于浏览器版本的 rap.plugin.js 改造成一个 nodejs 的module， 支持用来开发 自动化脚本

**Comment by Bosn** [comment]
很好的想法，感谢亲的分享哦

**Comment by zhengheh** [comment]
会考虑实现么，  后者我们实现了，你们会接收么

**Comment by nuysoft** [comment]
@zhengheh 抱歉，官方版本不会接受。因为实际服务返回的内容不可预期，存在安全问题。
