### ISSUE TITLE
redis应该能支持密码

### ISSUE THREAD

**Issue by yueshenginfo** [thx/RAP#725]

**Comment by Bosn** [comment]
可以支持的呀，自己设置就好了。

**Comment by yueshenginfo** [comment]
好的，谢谢！



杜厚亚
项目总监
山东悦升信息技术有限公司
地址：山东省济南市高新区颖秀路2755号，同缘大厦502、505室。
网址：www.yueshenginfo.com
邮箱：duhouya@yueshenginfo.com
电话：0531-88950816
手机：15098817304

德州分公司：
德州仁众网络信息技术有限公司
地址：德州市康博大道中旺大厦4楼622室。

投诉或建议请发邮件：
system@yueshenginfo.com
    
 
发件人： Bosn
发送时间： 2016-11-07 12:39
收件人： thx/RAP
抄送： 山东悦升信息技术有限公司; Author
主题： Re: [thx/RAP] redis应该能支持密码 (#725)
可以支持的呀，自己设置就好了。
―
