### ISSUE TITLE
依赖包找不到，求大神指导！！！！！！！！！

### ISSUE THREAD

**Issue by yangyuanchao** [thx/RAP#726]
compile group: 'nl.flotsam', name:'xeger', version:'1.0.0-SNAPSHOT'
compile group: 'com.alibaba', name:'buc.sso.common', version:'0.4.4'
compile group: 'com.alibaba', name:'buc.sso.client', version:'0.3.9'

**Comment by Bosn** [comment]
使用release分支就好了，master分支下这几个包是阿里集团内部的版本，包是不对外提供的。
