### ISSUE TITLE
在mockjs后边加上data后返回失败

### ISSUE THREAD

**Issue by duguyin** [thx/RAP#728]
在访问路径中，../mockjs/...加上data后访问：../mockjsdata/..，结果返回始终为：
{"errMsg":"\"Mock\" is not defined.","isOk":false}

**Comment by Bosn** [comment]
mock-min.js文件没有正常加载，在部分os或tomcat中出现。请来java文件搜索关键字mock-min修正路径

**Comment by mkc-leslie** [comment]
我也遇到这个问题，解决办法能再详细点吗？多谢
