### ISSUE TITLE
有人使用rap模拟C端，验证真实后台环境的准确性嘛？

### ISSUE THREAD

**Issue by huangjunGo** [thx/RAP#730]
把rap的请求直接指向后台服务，验证所传参数的准确性，请问如何实现啊？谢谢~

**Comment by huangjunGo** [comment]
接口自动化测试 ： 这块我想是在已定义的接口中，能够调用真实的环境，对输入、输出参数进行校验，并输出报告。
请问有小伙伴实现了么~谢谢

**Comment by Bosn** [comment]
接口级别是可以的，找找市面上成熟的UT框架，加入访问RAP比较接口格式的用例。可以访问mockjsdata接口自己比较，我可以看下OpenAPI部分由RAP Server比较并返回结果
