### ISSUE TITLE
“项目”和“模块”有没有感觉重复了的？

### ISSUE THREAD

**Issue by huanggongping** [thx/RAP#732]
感觉层级比较多，团队 -》 产品线 -》 分组 -》 项目 -》 模块 -》 页面 -》 接口

团队 -》 产品线 -》 分组，这个组织结构可以理解，一个公司有多个开发团队，一个团队负责多个产品线，一个产品分为多个开发小组，然后应该是一个小组负责多个模块，中间又加了一个项目的概念，有点不知道该怎么组织了，请大神们给点建议，谢谢！

**Comment by Bosn** [comment]
团队，业务线，分组其实是rap默认给出的三层框架，自己完全可以根据需要去设计。

比如简单团队只需要两层，分组里只要有一个项目就够了。

**Comment by Bosn** [comment]
也就是说并不是给你三层你就非要三层。。你也可以把分组作为团队来组织项目。业务线和分组只是默认的业务拆分叫法。

**Comment by huanggongping** [comment]
感谢回复，另外，我们是做产品，项目可以作为产品迭代来对待吗？分组是只人员分组还是接口的分组？谢谢。

**Comment by huanggongping** [comment]
这里的接口管理按说应该没有产品开发的迭代概念吧？不然会有很多重复的吧？如果是这样，那么项目这个概念应该怎么理解？项目和产品线是什么区别和关系？

**Comment by Bosn** [comment]
这个是自己定义的，如果只想简单的处理，那就业务线A模块A就好了。
