### ISSUE TITLE
Mock测试服务请求接口增加header参数

### ISSUE THREAD

**Issue by hun2008hun** [thx/RAP#737]
![image](https://cloud.githubusercontent.com/assets/8822016/20171408/74b30ffa-a76b-11e6-8e9c-e4f24832487f.png)

**Comment by fireinjava** [comment]
+1 我也想知道有没这个功能

**Comment by luhaikong** [comment]
我也遇到同样的问题了，扫了下所有的Issues，关于这种问题都没有人回答哎

**Comment by Bosn** [comment]
暂时还不支持header哦，技术可实现行我在调研，确实这块儿需求挺大的，如果可以实现我会尽快规划到下一个版本。
