### ISSUE TITLE
mock正则RESTful API返回奇怪数据

### ISSUE THREAD

**Issue by tan-hui** [thx/RAP#740]
mock正则RESTful API返回奇怪数据 ,数据中包含js代码,
地址:http://rap.taobao.org/workspace/myWorkspace.do?projectId=10118#76165

数据如下:

{"obj":{"needCommuPassWord":false,"verifyCodeStyle":1,"autoVerifyCode":true,"verifyCodeUrl":"\/jlcweb\/api\/spider\/cgws\/v1\/verifyCode.jpg","inputFieldItems|2":[{"hint":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'\u8bf7\u8f93\u5165\u60a8\u5728\u6b64\u7ad9\u70b9\u7684\u767b\u5f55\u7528\u6237\u540d\',\'\u8bf7\u8f93\u5165\u60a8\u5728\u6b64\u7ad9\u70b9\u7684\u767b\u5f55\u5bc6\u7801\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10000';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"inputType":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(0,1)";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10001';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"labelName":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'\u7528\u6237\u540d\',\'\u5bc6\u7801\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10002';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);},"name":function() {   var window = function(){return this;}();	function geneVal(key) {		var o = __rap__context__[key];		var arr = o.arr;		return arr[o.index++ % arr.length];	}	if (!window.__rap__context__) {		window.__rap__context__ = {};	}	var orderCmd = "$order(\'userName\',\'password\')";	var orderArr = eval('[' + orderCmd.substring(7, orderCmd.length - 1) + ']');	var key = '10003';	if (!__rap__context__[key]) {		__rap__context__[key] = {			arr : orderArr,			index : 0		};	}	return geneVal(key);}}]},"code":0,"msg":""}

**Comment by Bosn** [comment]
不奇怪啊，可以用的。导入数据为了重现被RAP编译成自定义函数了
