### ISSUE TITLE
部署报错问题

### ISSUE THREAD

**Issue by sll347** [thx/RAP#742]
有人用war包部署成功过吗？

**Comment by Bosn** [comment]
有，我成功过

**Comment by sll347** [comment]
我现在也成功了，但是注册或者登陆的时候报这个错，Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction;
你有没有遇到过，能不能指导一下

**Comment by Bosn** [comment]
楼上是数据库配置错误

**Comment by sll347** [comment]
已经好了，Session默认的是60，我改大了一点改成了160，就正常了

**Comment by mkc-leslie** [comment]
是改的web.xml文件里的<session-timeout>160</session-timeout>？？

**Comment by sll347** [comment]
是该session-config节点
