### ISSUE TITLE
部署成功后，注册报错

### ISSUE THREAD

**Issue by sll347** [thx/RAP#743]
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

org.springframework.transaction.CannotCreateTransactionException:

**Comment by sll347** [comment]
问题已经解决，session默认的是60，我改大了一点，改成160就好了

**Comment by mkc-leslie** [comment]
我也遇到了跟你一样的问题，index页面一登录就报这个错误，请问你怎么解决的，能说详细点不？谢谢

**Comment by sll347** [comment]
web.xml中的session-config改成160，我是这么改的，你可以试试

**Comment by mkc-leslie** [comment]
谢谢你，已经好了
