### ISSUE TITLE
rap小助手里点击mockjs示例出错

### ISSUE THREAD

**Issue by flywan123** [thx/RAP#754]
显示为：
RAP出错啦！
technical details
Unknown Exception
java.lang.NullPointerException at com.taobao.rigel.rap.organization.service.impl.OrganizationMgrImpl.canUserManageProject(OrganizationMgrImpl.java:198) at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
.....

打印了出错的栈信息

**Comment by Bosn** [comment]
要给出具体的测试数据哦
