### ISSUE TITLE
导入json数据后，变为数组

### ISSUE THREAD

**Issue by imkratos** [thx/RAP#756]
```json
{"code":"00000","msg":"success","data":[]}
```
这是我响应的json数据，导入到响应参数中之后
![image](https://cloud.githubusercontent.com/assets/3302461/20614333/412c53d2-b308-11e6-87e2-68b2a8b4ecc6.png)显示是这个样子的没有问题。

但在调用时显示数据如下：
![image](https://cloud.githubusercontent.com/assets/3302461/20614368/86228948-b308-11e6-9e23-1688ac68a632.png)

返回的数据是数组格式的。

1. 给你的数据最外层加一层，比如你现在的数据是{data}，修改为：{"json":{data}}
2. 导入到响应参数; 
3. 新增一个请求参数，在第一列输入json(也就是同名)后ctrl + enter来执行一键复制;
4. 删掉响应参数里的json参数。

我也按照文档试了下，如果加成{"json":data}但这不是我真实需要的数据啊。

求解答是我哪里没有配置对吗。

**Comment by Bosn** [comment]
请参考最外层的MOCK数据规则：https://github.com/thx/RAP/wiki/user_manual_cn#%E5%A6%82%E4%BD%95%E6%8E%A7%E5%88%B6%E6%9C%80%E5%A4%96%E5%B1%82%E7%9A%84mock%E6%95%B0%E6%8D%AE%E8%A7%84%E5%88%99
