### ISSUE TITLE
当值为数组时，无法按顺序生成数据。

### ISSUE THREAD

**Issue by guan6** [thx/RAP#757]
变量名：index|+1
类型：string
value(备注)：@mock=["a","b","c"]

生成的数据，index并没有按照数据顺序递增。

**Comment by Bosn** [comment]
这取决于mock规则，本就是随机选取一个。若想要按顺序，请参考mock.js官方文档中的说明哦。如果Mock.js官网不提供该方法，建议参考使用@order指令，具体亲可以自己用json导入功能导入一组数据，就知道具体用法了哟。
