### ISSUE TITLE
MOCK数据异常

### ISSUE THREAD

**Issue by guodefu909** [thx/RAP#758]
按照示例设置
入参：page number
出参：pageRes	number	@mock=${page=1008}
           page1		number	@mock=function(){return ${page}+100;}
mock页面设置page为222
返回数据：
{
    "pageRes":1008,"page1":100
}
直接访问接口返回数据：
{"pageRes":222,"page1":function(){return 222+100;}}

**Comment by guodefu909** [comment]
http://rap.taobao.org/tester/pageTester.do?id=27529

**Comment by guodefu909** [comment]
『BUG 报告』

**Comment by ddkwing** [comment]
如果想看实际结果，将url中mockjs改为mockjsdata即可。具体请参考官方Q&A，里面有一个“为什么RAP服务直接返回的是MockJS模板，而不是MockJS数据”。

**Comment by Bosn** [comment]
感谢楼上同学的热心回复
