### ISSUE TITLE
rap 接口添加参数，参数只能自动排序么？

### ISSUE THREAD

**Issue by testtester1** [thx/RAP#759]
rap 接口添加参数，参数只能自动排序么？
我想按照自己的规则 排序，不知道怎么操作

**Comment by testtester1** [comment]
rap 接口添加参数，参数只能自动排序么？
我想按照自己的规则 排序，不知道怎么操作

**Comment by E-lai** [comment]
看来这个问题大家都有

**Comment by xiaoxing598** [comment]
可以考虑在图中箭头所指示的位置加一个上下移动的箭头，但目前  `tb_parameter` 表中并没有这个排序字段，例如 `sort`。如果过段时间没那么忙了，我考虑可以加上，又或者可能其它人愿意提前完成这个功能。
![qq 20170103144846](https://cloud.githubusercontent.com/assets/5615719/21601316/1ecc574e-d1c4-11e6-930b-57a0353e7c06.png)

**Comment by Bosn** [comment]
目前默认按照字母顺序排序哦，拖拽排序涉及较大的改动，未来版本我们会考虑实现，不过暂时还没有哦亲。
