### ISSUE TITLE
教程里讲响应参数用${parameters}方法关联请求参数为何无效？

### ISSUE THREAD

**Issue by mqhe2007** [thx/RAP#765]
请求参数：carID; number
响应参数备注配置@mock=${carID=1}
请求的时候响应参数并没有接收到carID传的值
教程里可是这样讲的可以接收到啊

**Comment by R-Richie** [comment]
我也是相同的情况，按照教程做，不起效果，但赋默认值还是起效的

**Comment by ddkwing** [comment]
为什么没人来解答。。。

**Comment by ddkwing** [comment]
如果想看实际结果，将url中mockjs改为mockjsdata即可。具体请参考官方Q&A，里面有一个“为什么RAP服务直接返回的是MockJS模板，而不是MockJS数据”。

**Comment by liangjingyang** [comment]
#715
