### ISSUE TITLE
编辑被某一账户锁定，即使将其从项目中删除依然无法解锁

### ISSUE THREAD

**Issue by yunnysunny** [thx/RAP#767]
我们的项目地址：http://rap.taobao.org/workspace/myWorkspace.do?projectId=10031
现在出现一个问题，我们项目中原来加了一个灵寿狼的帐号，然后我们发现编辑被锁定（提示`该项目目前正被灵寿狼锁定.`），我们将这个用户从项目成员中删除了，但是现在依然不能编辑，都好几天了.

**Comment by alexfeng** [comment]
我也碰到这种情况，每个项目有中都有管理人员，我有个项目A被另一个项目B下管理人锁定了，不知道如何解决了

**Comment by Bosn** [comment]
这个主要是项目没有好的解锁机制导致的，比如A进入锁定状态后异常关闭，导致项目被锁定。这种情况一般需要多等待一段时间，或者让锁定该项目的用户重新编辑再退出即可恢复。
