### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by imkratos** [thx/RAP#768]
![image](https://cloud.githubusercontent.com/assets/3302461/20794273/6e38080a-b806-11e6-9419-7c9b767aaec6.png)
第一次启动时，可以正常启动，可是第二次再启动时显示此错误，并且主页打不开。
在网上查了下，说是jdbc注册的问题，不知道其他各位遇没遇到这个错误？
如果各位都有这种错误的话，那我感觉可以提交一个Pull Request 不用这种数据源的连接方式了。
系统open suse
容器tomcat8.5.8
jdk 1.8.0

**Comment by imkratos** [comment]
自问自答，我是redis里设置了密码，在config.properties里配置了密码也没用。我去看下源码在哪里配置，或者更新一下最新release。

**Comment by fanfengping** [comment]
请问这个问题解决了么 ？我也发生了同样的问题
谢谢！

**Comment by imkratos** [comment]
@fanfengping 我是解决了的，是因为redis设置了密码，但是在config里配置redis.password没有作用，我把redis密码去掉就可以了。

**Comment by imkratos** [comment]
这个报错很奇怪，明明是redis的问题。。但显示的却是另外的错误，所以不太好排查。所以如果发生了这个问题，你想下自己动过了什么。根据显示的这个问题查，多半都是说hibernate配置数据源的问题。
