### ISSUE TITLE
Mock规则@cname,@ctitle等随机的中文字符不能显示

### ISSUE THREAD

**Issue by wfshine** [thx/RAP#769]
例如：
规则
{
    "name": "@cname",
    "data|1": [
        {
            "href": "@url",
            "imgUrl": "@IMAGE(640x320,@COLOR,'home-slider')"
        }
    ],
    "errorCode": "0",
    "status": "1"
}
数据
{
    "name": "@cname",
    "data": [
        {
            "href": "http://xlsu.co.uk/pxyi",
            "imgUrl": "http://dummyimage.com/640x320/e5202a&text='home-slider'"
        }
    ],
    "errorCode": "0",
    "status": "1"
}

**Comment by iahu** [comment]
+1

**Comment by kuangzhibin** [comment]
+1 #459 插件之前引入新版Mockjs不起作用

**Comment by xheartx** [comment]
建议作者，把mockjs的版本升级一下吧

**Comment by Bosn** [comment]
版本升级我会尽快进行
