### ISSUE TITLE
DataDaoImpl.getUserTrendByMonth SQL分组异常

### ISSUE THREAD

**Issue by yinzhaohua** [thx/RAP#774]
StringBuilder sql = new StringBuilder();
        sql
                .append("SELECT MONTH(create_date) AS month, COUNT(id) as num, create_date ")
                .append("FROM tb_user ")
                .append("WHERE create_date BETWEEN DATE_ADD(NOW(), INTERVAL -1 YEAR) AND NOW() ")
                .append("GROUP BY MONTH(create_date) ")
                .append("ORDER BY create_date");

这段代码拼装的sql语句不对。这样写分组是错的。

**Comment by Eddie-he** [comment]
我在创建项目的时候无法创建分组，单独创建分组的是时候没有任何反应。
