### ISSUE TITLE
问题如下所示，数据不支持，不知道什么情况

### ISSUE THREAD

**Issue by yinzhaohua** [thx/RAP#775]
![image](https://cloud.githubusercontent.com/assets/4084518/20880900/cebb3498-bb14-11e6-8707-5d74ed32337f.png)

**Comment by ddkwing** [comment]
同样的问题，有人能解答一下吗

**Comment by ddkwing** [comment]
@yinzhaohua 我知道为什么了，怪没有好好看文档。你通过右下角区域链接，看到的是mock规则的结果。如果想看实际结果，将url中mockjs改为mockjsdata即可。具体请参考官方Q&A，里面有一个“为什么RAP服务直接返回的是MockJS模板，而不是MockJS数据”。

**Comment by Bosn** [comment]
右边是规则，左边是数据。
