### ISSUE TITLE
数据->今日统计->活跃用户出现一个非我们团队的用户

### ISSUE THREAD

**Issue by huyue6255** [thx/RAP#776]
JDK 1.7 
系统：win7
redis 3.3.2
mysql ：5.5.6
tomcat 7
rap版本  v0.14.1Beta
数据->今日统计->活跃用户出现一个非我们团队的用户，第五个用户复活的肉山不是我们团队的
![image](https://cloud.githubusercontent.com/assets/9364420/20909531/5731f38e-bb97-11e6-899f-4283251dd2a7.png)

**Comment by krisbai** [comment]
目前系统好像只支持在页面注册的形式，如果暴露在公网访问的话这块是没法避免的。建议收拢在内网访问。后边看支不支持LDAP的注册模式。

**Comment by Bosn** [comment]
出现该人物说明您有意或无意的在公开项目中引入了该用户。
