### ISSUE TITLE
页面卡在load workspace please wait

### ISSUE THREAD

**Issue by bestboylm** [thx/RAP#778]
你好，我在RAP（自己搭的服务）里点击一个项目，页面停在load workspace please wait的状态，就不动了。信息请见附件。请问如何解决？

**Comment by bestboylm** [comment]
![image](https://cloud.githubusercontent.com/assets/18669928/21038430/78631c10-be10-11e6-89e6-196c8393a4d0.png)

**Comment by krisbai** [comment]
遇到了同样的问题，请问解决了么？

**Comment by krisbai** [comment]
遇到了同样的问题，请问解决了么？

**Comment by krisbai** [comment]
遇到了同样的问题，请问解决了么？

**Comment by ZhengXiaoWu** [comment]
I solved this question by add memory of tomcat

**Comment by Bosn** [comment]
如最后回复，内存不足导致对象导出失败。
