### ISSUE TITLE
【页面测试失效】发送请求无反应

### ISSUE THREAD

**Issue by laurent-wang** [thx/RAP#779]
我是自己搭建的RAP环境，数据库等都是好的，可以正常添加团队以及接口。
编辑完某个接口以后，点击mock数据，可以正常看到mock出来的结果。但是点击到测试页面时，输入了参数以后就没有反应了，看到视频里面应该是有mock值返回，并且右下角应该有个灰色区域有请求链接的，请问这个是什么问题啊？

**Comment by Bosn** [comment]
请仔细看下控制台及服务器日志中的错误信息，如果还未解决，请贴出详细错误信息再reopen谢谢
