### ISSUE TITLE
部署报错，看不出是什么问题，求教。

### ISSUE THREAD

**Issue by canghai908** [thx/RAP#783]
tomcat 日志报错，看不出是什么问题，该配置的地方都配置了
系统：centos 6
jdk：jdk 1.8
tomcat：tomcat 8.5.9
war：https://github.com/thx/RAP/releases/tag/v0.14.1.war
修改成ROOT.war ，启动taomcat 之后 报错：

19-Dec-2016 12:36:47.651 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.9
19-Dec-2016 12:36:47.653 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 5 2016 20:18:12 UTC
19-Dec-2016 12:36:47.653 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.9.0
19-Dec-2016 12:36:47.653 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            2.6.32-573.18.1.el6.x86_64
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/jdk1.8.0_101/jre
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_101-b13
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /db/tomcat-7.0.73-8121
19-Dec-2016 12:36:47.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /db/tomcat-7.0.73-8121
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/db/tomcat-7.0.73-8121/conf/logging.properties
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/db/tomcat-7.0.73-8121
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/db/tomcat-7.0.73-8121
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/db/tomcat-7.0.73-8121/temp
19-Dec-2016 12:36:47.655 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
19-Dec-2016 12:36:47.772 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8122"]
19-Dec-2016 12:36:47.786 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
19-Dec-2016 12:36:47.789 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8124"]
19-Dec-2016 12:36:47.790 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
19-Dec-2016 12:36:47.790 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 460 ms
19-Dec-2016 12:36:47.811 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
19-Dec-2016 12:36:47.812 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.9
19-Dec-2016 12:36:47.820 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /db/tomcat-7.0.73-8121/webapps/ROOT
19-Dec-2016 12:36:49.417 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
12:36:50.491 [localhost-startStop-1] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.0.6.Final}
12:36:50.493 [localhost-startStop-1] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
12:36:50.495 [localhost-startStop-1] INFO  org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
12:36:50.516 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.072 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.081 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.089 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.099 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.108 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.121 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.125 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.131 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.136 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.143 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.148 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.152 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.157 [localhost-startStop-1] WARN  org.hibernate.orm.deprecation - HHH90000012: Recognized obsolete hibernate namespace http://hibernate.sourceforge.net/hibernate-mapping. Use namespace http://www.hibernate.org/dtd/hibernate-mapping instead.  Support for obsolete DTD/XSD namespaces may be removed at any time.
12:36:51.191 [localhost-startStop-1] INFO  org.hibernate.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
12:36:51.563 [localhost-startStop-1] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
12:36:51.602 [localhost-startStop-1] INFO  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl - HHH000423: Disabling contextual LOB creation as JDBC driver reported JDBC version [3] less than 4
12:36:52.441 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.RapServletContextListener - RAP Server initializing...
12:36:52.441 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.RapServletContextListener - Initializing Jedis Server...
12:36:52.441 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.RapServletContextListener - Initializing Jedis Server...
19-Dec-2016 12:36:52.488 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
19-Dec-2016 12:36:52.501 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
12:36:52.504 [localhost-startStop-1] INFO  com.taobao.rigel.rap.common.listener.RapServletContextListener - Context destroyed.
19-Dec-2016 12:36:52.529 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
19-Dec-2016 12:36:52.531 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Log4j2-Log4j2Scheduled-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
19-Dec-2016 12:36:52.531 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [MySQL Statement Cancellation Timer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 java.util.TimerThread.mainLoop(Timer.java:526)
 java.util.TimerThread.run(Timer.java:505)
19-Dec-2016 12:36:52.532 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
19-Dec-2016 12:36:52.538 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /db/tomcat-7.0.73-8121/webapps/ROOT has finished in 4,720 ms
19-Dec-2016 12:36:52.539 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-8122]
19-Dec-2016 12:36:52.544 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-8124]
19-Dec-2016 12:36:52.545 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 4755 ms

!!解决了，是redis问题。。

**Comment by LinLeyang** [comment]
hello 怎么解决的

**Comment by canghai908** [comment]
redis 能连接，不可用，后来换了一个redis就好了。。。

**Comment by LinLeyang** [comment]
恩恩 我的也是redis 问题 redis启动后竟然不能ctrl+c退出 退了就关闭了
