### ISSUE TITLE
导出的json无法解析

### ISSUE THREAD

**Issue by Pipikachu** [thx/RAP#856]
我用 *http://{domainName}/api/queryRAPModel.do?projectId={projectId}* 这个开放的api获取到json格式的接口信息，我这边想把它解析出成js对象，但是json.parse无法解析，
一个简单的接口返回的数据是这样:

```
{"modelJSON":"{\"createDateStr\":\"2017-03-22\",\"user\":{\"name\":\"fdfdd\",\"id\":24},\"id\":7,\"version\":\"0.0.0.1\",\"introduction\":\"ceshi\",\"name\":\"ceshi\",\"moduleList\":[]}","code":200,"mockjsMap":{},"msg":0}
```
里面的modelJSON我不知道怎么解析，尝试去除转义,bom之后也不可以。。。有没有什么方法能解析出导出的json

**Comment by xiaoxing598** [comment]
你把导出的json贴出来看一看

**Comment by Pipikachu** [comment]
已经更新问题了

**Comment by xiaoxing598** [comment]
项目使用的gson-2.3.1.jar，应该不用出现解析不了的情况。

```
public String toJson(Object src) {
        return src == null?this.toJson((JsonElement)JsonNull.INSTANCE):this.toJson((Object)src, (Type)src.getClass());
}
```

**Comment by Pipikachu** [comment]
麻烦能详细讲一下吗? 是我这边的rap配置有问题吗，我做前端的，java这边不是很了解

**Comment by Pipikachu** [comment]
补充一下：我解析 是用Node解析的。但我不知道是什么原因 导致解析不了

**Comment by xiaoxing598** [comment]
你获取modelJSON键对应的值得到一个json字符串，然后解析这个字符串，应该是可以的。

**Comment by Pipikachu** [comment]
这个字符串解析不了，尝试转义以及去除bom都出错

**Comment by xiaoxing598** [comment]
我这边专门测试一下，是可以的，你自己再研究一下吧。

```
var str = "{\"createDateStr\":\"2017-03-22\",\"user\":{\"name\":\"fdfdd\",\"id\":24},\"id\":7,\"version\":\"0.0.0.1\",\"introduction\":\"ceshi\",\"name\":\"ceshi\",\"moduleList\":[]}";
console.info(JSON.parse(str));
```

![image](https://cloud.githubusercontent.com/assets/5615719/24179929/16ed81f4-0eed-11e7-9068-e198ac09fb02.png)

**Comment by Pipikachu** [comment]
嗯 好的，我自己再尝试一下，谢谢
