### ISSUE TITLE
0.14.16部署失败

### ISSUE THREAD

**Issue by callmepeanut** [thx/RAP#888]
采用的这里的方法部署：https://github.com/thx/RAP/wiki/deploy_on_centos_cn
0.14.1能够成功部署，但是0.14.16部署失败
看日志好像是webapp.root不对，但是没找到修改的地方

**Comment by callmepeanut** [comment]
又部署成功了，要注意保留之前版本的WEB-INF/classes/config.properties

**Comment by limitLam** [comment]
请问你是怎么搞定的呢？我这边部署0.14.16版本，502，找不到解决方法，config.properties配置也是一样的

**Comment by callmepeanut** [comment]
我的不是5xx，都看不到任何页面。5xx的话看日志应该有信息

**Comment by xihadandan** [comment]
我的也是0.14.1能够成功部署，但是0.14.16部署失败
你是怎么解决的？用之前版本的config.properties？

**Comment by callmepeanut** [comment]
@xihadandan 是的，用之前版本的

**Comment by xihadandan** [comment]
0.14.16部署成功
