### ISSUE TITLE
URL路由模糊匹配带来的问题

### ISSUE THREAD

**Issue by hsxiaoma** [thx/RAP#92]
在实际使用过程中,有以下两个路径:
/ui-desktop/getUserInfoWinList      
/ui-desktop/getUserInfo
在使用mock数据时, 都统一返回的是/ui-desktop/getUserInfoWinList 里的数据,而无法得到/ui-desktop/getUserInfo数据,建议采用精确匹配.

**Comment by Bosn** [comment]
已完成修复，下个版本上线。
在模糊匹配URL时，精准匹配的请求优先选取。
