### ISSUE TITLE
 Loading workspace... Please wait...

### ISSUE THREAD

**Issue by guodooo** [thx/RAP#922]
V0.14.1，我有两个项目，一个可以进去，一个进不去.
我尝试重新部署了下，发现问题没有解决，我觉得可能是数据库里面的数据错乱了。我不知道怎么处理。
我有尝试更新到最新版本V0.14.6，但是我需要我原来数据库的数据，因此我采用旧的数据库，结果发现不行，预计新得版本有新的数据表或字段。好尴尬，一直用得好好的，突然出问题。是哪个数据表的数据有问题，我接下来想试试删除数据，不知道有没有用

**Comment by guodooo** [comment]
我感觉蛮幸运的，我讲数据库tb_check_in的数据全部删除，竟然可以进去了。

**Comment by ZJM6658** [comment]
> 我感觉蛮幸运的，我讲数据库tb_check_in的数据全部删除，竟然可以进去了。

感谢，删掉后同样感受到了幸运，不过请问一下你们有更换其他接口管理工具吗？
