### ISSUE TITLE
交互小问题

### ISSUE THREAD

**Issue by freestyle21** [thx/RAP#93]
rap进入主页，点击“我加入的项目”中的某一个，期望在当前页面打开。

每次都要手动关闭前一个tab也很不爽啊啊啊。。

原谅处女座。。

**Comment by Bosn** [comment]
我在想这么搞完了会不会用人经常打开多个问能不能开新链接-   。-~~~~

好吧，先赞着亲的提议实现下，如果有人想打开新窗口让它Ctrl+click好了。

**Comment by yisibl** [comment]
http://www.zhihu.com/question/20957838

**Comment by Bosn** [comment]
新窗这个设计很体贴，不过我如果没有花时间看过一整片文章，并仔细的找半天（那链接内容有点多）真心不太容易发现这个新窗，并且也很难知道其想表达的意思。

对于RAP，用户大都了解互联网，大都知道新开窗口的办法。所以确实默认在当页打开更为合适。

**Comment by Bosn** [comment]
已完成修改，下个版本上线。

**Comment by freestyle21** [comment]
谢谢。
