### ISSUE TITLE
noCache优化

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#95]
因增加mock数据缓存，根据请求参数输出结果的功能不能正常使用。
目前解决方案是noCache=true设置参数，
可优化：当发现参数列表备注有用到$page这种请求变量时，自动内部设置noCache禁用缓存。

**Comment by cctestss** [comment]
目前解决方案是noCache=true设置参数  在哪里设置呢？

**Comment by Bosn** [comment]
只要在请求信息的“请求链接”里设置就好了

例如，请求链接/data/get，这样写时默认会缓存具体的MockJS模板。
写成/data/get?noCache=true，这样MockJS模板每次都是动态生成。

**Comment by Bosn** [comment]
### 技术设计

为避免每次mock请求计算是否需缓存，增大负担。在每次CheckIn提交新文档时，会计算参数@mock数据是否包含$xxx和${xxx}语法的联动结构，若包含，则设置disableCache=1

增加tb_action表中的字段：disable_cache tinyint NOT NULL DEFAULT 0

### 数据库更新脚本
```sql
ALTER TABLE tb_action
ADD COLUMN disable_cache TINYINT NOT NULL
    DEFAULT 0；

-- 默认先全部disable_cache
UPDATE tb_action
SET disable_cache = 1
WHERE id != 0
```

以上脚本`需在下一版迁移手册`中说明。

### 技术细节
在WorkspaceAction.checkIn方法调用时（文档提交），遍历Action阶段，计算@mock中是否包含$page，若包含，将该Action使用了联动参数，则将tb_action.disable_cache设置为1，反之为0.

**Comment by Bosn** [comment]
已完成cache优化。将在下一个版本更新，已合入master。
