### ISSUE TITLE
当创建接口的mock数据中有数组（length>1）数据时，模拟请求出错

### ISSUE THREAD

**Issue by occultskyrong** [thx/RAP#965]
### 数字数组
- 当`数字数组的长度为1`时，
```
{
    "a": 1,
    "b": [
        {
            "b": 1,
            "c": 2
        }
    ]
}
```
模拟请求没问题
![image](https://user-images.githubusercontent.com/8370006/27569037-f26dd54a-5b27-11e7-8eaa-8100483a157e.png)

- 当`数字数组的长度>1`时，
```
{
    "a": 1,
    "b": [
        {
            "b": 1,
            "c": 2
        }
    ],
    "c": [
        {
            "c": 1,
            "d": 2
        },
        {
            "c": 3,
            "d": 4
        }
    ]
}
```
模拟请求出现错误
![image](https://user-images.githubusercontent.com/8370006/27569080-156b0158-5b28-11e7-8f59-b3ad60ace35c.png)

**Comment by occultskyrong** [comment]
### 中文数组 ，相同的问题
- 长度=1的数组，没问题
![2](https://user-images.githubusercontent.com/8370006/27569159-9b21699a-5b28-11e7-80ad-7a3c6c3f5c78.png)


- 长度>1的数组，出错
```
{
    "a":1,"d":[
    {
        "d":"呵呵"
    }
    ],"e":[
    {
        "e":"嘿嘿"
    }
    ,
    {
        "e":"哈哈"
    }
    ]
}
```

![1](https://user-images.githubusercontent.com/8370006/27569163-9cab54f6-5b28-11e7-8873-d3cebdabb1fb.png)

**Comment by occultskyrong** [comment]
查看该项目的commit时间，最后是4.8日，该项目作者貌似从阿里离职？项目不维护了？？

**Comment by TomCruiseYang** [comment]
也遇到这个问题了,同问

**Comment by occultskyrong** [comment]
@TomCruiseYang 
RAP2应该是解决了这个问题
http://rap2.taobao.org/
