### ISSUE TITLE
支持用户录入mockjs语义化标签用于if-test平台的测试校验

### ISSUE THREAD

**Issue by paolier** [thx/RAP#97]

**Comment by Bosn** [comment]
### 完成进度
[ ] IF-TEST模式-前端开发
[ ] IF-TEST模式-数据模型tb_parameter新增iftest字段、对应service/dao处理
[ ] MockJS模式-前端开发
[ ] MockJS模式-数据模型tb_parameter新增mockjs字段、对应service/dao处理
[ ] 可视化MockJS编辑模式

### 需求设计

#### IF-TEST
右上角新增新增IF-TEST按钮，当点亮时进入IF-TEST编辑模式。
此状态下备注会变为“IF-TEST”，其中内容直接填写IF-TEST规则即可。
@paolier 

#### MockJS
右上角Mock按钮变更为MockJS按钮，当点亮时进入MockJS编辑模式。
此状态下备注会变为"MockJS"，备注中的内容即为MockJS规则的对应字段的`值`。
从此不再使用@mock标签。

引入MockJS的JSON模板编辑模式，结构不允许变动，仅可修改key和value。

#### 其它
MockJS/IF-TEST模式互斥，不可同时启用

**Comment by Bosn** [comment]
也请 @nuysoft 墨汁老师看看如上修改是否满意，有什么建议和意见尽早提哦

**Comment by Bosn** [comment]
在2015年RAP v0.12版本的规划里，不单独列了。
