### ISSUE TITLE
打开或关闭验证码功能

### ISSUE THREAD

**Issue by ahan** [thx/RAP#988]
因为 rap 每隔一段时间会登录 session 失效，然后重新登录
在开发程序前期写 rap时，半天左右时间可能要反复登录好几次

登录时，chrome 是可以记住用户名密码的，但还要再输一个验证码

考虑到是本地部署 rap，对验证码的需求不大，反而会多加额外的操作去登录

可否可以有个地方可以配置一下，自定义打开或关闭验证码功能？

**Comment by WWQ1993** [comment]
我也遇到这个问题了，在看后端代码，把session过期时间设置久一点

**Comment by callmepeanut** [comment]
@WWQ1993 在哪里可以设置？

**Comment by WWQ1993** [comment]
@callmepeanut 不知道，失败了。要改源码才行，感觉产品体验不太成熟

**Comment by zhanghengtodo** [comment]
com.taobao.rigel.rap.account.web.action.AccountAction的doLogin里面309-313行注释掉，自己编译下部署就可以了。

**Comment by euktv** [comment]
验证码错误在吗解决
![image](https://user-images.githubusercontent.com/24917984/31620243-090b2a66-b297-11e7-826a-8767cefeda90.png)
