### ISSUE TITLE
incorrect response for RESTful API 

### ISSUE THREAD

**Issue by ken8271** [thx/RAP#99]
in case there will be a restful api looks like 
/articles/:id
then it will get the no matched action error
but as the /articles/:id/view
it will get the correct response

as i debug the code , it seems that when matching the real url with defined pattern url in db , it will make it un-match , since the real url will replace /123/ with / , but for our case , the real url is /articles/123 , it will un-match the regex , so it will not do the replacement

**Comment by Bosn** [comment]
Thx for your reply! This's obviously a bug. I didn't hanlde well on the '/' char, I'll fix it ASAP.
BTW, I guess u r using branch release-en, right?

**Comment by ken8271** [comment]
sorry , i am using the branch of release

**Comment by Bosn** [comment]
But release is in Chinese... 
So... you can speak Chinese?

**Comment by ken8271** [comment]
不好意思，习惯了英文，可以用中文的

**Comment by testxin** [comment]
我也是醉了！

**Comment by Bosn** [comment]
@ken8271 I've fixed this issue on master, I'll merge it into branch release in weeks.
You can also see the diff, only one file "StringUtils.java" changed.

**Comment by Bosn** [comment]
@ken8271 DIFF HERE https://github.com/thx/RAP/commit/31486e6d7634a6de45b7da307b320b577b38e5c7

**Comment by Bosn** [comment]
Merge complete, you can pull from release branch now...

**Comment by xierenyuan** [comment]
强势插入，楼主好人 1024  我的邮箱mao@pao.com
