### ISSUE TITLE
这个工具还在维护吗？是不是已经被废弃了

### ISSUE THREAD

**Issue by YuriTu** [thx/RAP#998]
最新的fixbug都4个月了，issues很多都没有回复，不太敢用啊...
要是废弃了我就用转Swagger了...

**Comment by cnfi** [comment]
同问

**Comment by kenChen1992** [comment]
阿里巴巴放弃的东西才会开源吧

**Comment by sx1989827** [comment]
可以参考这个项目，免费开源，专门做接口管理的 https://github.com/sx1989827/DOClever doclever.cn

**Comment by Bosn** [comment]
没放弃，RAP2用React 重构完了，放出来之前要做一些改动。
